ECS 160 Project: CAIPlayer Class Reference
CAIPlayer Class Reference
#include <AIPlayer.h>
Public Member Functions
CAIPlayer (std::shared_ptr< CPlayerData > playerdata, int downsample)
Constructor for CAIPlayer.
void CalculateCommand (SPlayerCommandRequest &command)
Decides what actions the AI should take.
Protected Member Functions
bool SearchMap (SPlayerCommandRequest &command)
bool FindEnemies (SPlayerCommandRequest &command)
Function used by the AI to find enemies by searching assets that are visible to it on the map.
bool AttackEnemies (SPlayerCommandRequest &command)
Function used by the AI to select fighters and attack the enemy.
bool BuildTownHall (SPlayerCommandRequest &command)
Function used by the AI to build a Town Hall. Returns true or false, depending on whether it was able to build or not.
bool BuildBuilding (SPlayerCommandRequest &command, EAssetType buildingtype, EAssetType neartype)
Function used by the AI to build a building other than the Town Hall. Returns true or false, depending on whether it was able to build or not.
bool ActivatePeasants (SPlayerCommandRequest &command, bool trainmore)
Function used by the AI to produce peasants and to make them gather resources.
bool ActivateFighters (SPlayerCommandRequest &command)
Selects fighting units that will be able to receive orders as a group. Returns true or false depending on whether it was able to select any fighters or not.
bool TrainFootman (SPlayerCommandRequest &command)
Function used by the AI to train Footmen.
bool TrainArcher (SPlayerCommandRequest &command)
Function used by the AI to train Archers.
Protected Attributes
std::shared_ptr< CPlayerData > DPlayerData
int DCycle
int DDownSample
Detailed Description
Definition at line 28 of file AIPlayer.h.
Constructor & Destructor Documentation
CAIPlayer()
CAIPlayer::CAIPlayer (std::shared_ptr< CPlayerData > playerdata, int downsample)
Constructor for CAIPlayer.
Parameters
DPlayerData - Holds data about the AI player (gold, lumber, etc.).
DCycle - Clock that increments whenever the AI tries to make a decision.
DDownSample - Determines how often the AI can perform an action.
How It Works
It sets all the parameters to their default values.
For more information about how DCycle and DDownSample work check CAIPlayer::CalculateCommand.
Definition at line 96 of file AIPlayer.cpp.
References DCycle, DDownSample, and DPlayerData.
{
     // Sets the AI Player's data to default values (e.g. lumber = 0, etc.)
     DPlayerData = playerdata;
     // Sets the current cycle to 0.
     DCycle = 0;
     // Initializes to DDownSample
     DDownSample = downsample;
 }
Member Function Documentation
ActivateFighters()
bool CAIPlayer::ActivateFighters (SPlayerCommandRequest & command) protected
Selects fighting units that will be able to receive orders as a group. Returns true or false depending on whether it was able to select any fighters or not.
How It Works
The function looks through all the idle assets it has and checks whether they have a speed property and whether they are not a peasant. Then it checks whether the asset is not currently standing ground. If the asset is not standing ground, it is added to a list of actors (assets that can perform actions). The function checks whether that list is empty and if it isn't it will make all the actors on the list stand ground.
Definition at line 574 of file AIPlayer.cpp.
References aaStandGround, actStandGround, atPeasant, SPlayerCommandRequest::DAction, SPlayerCommandRequest::DActors, and DPlayerData.
Referenced by CalculateCommand().
{
     // Variable that holds the idle assets of the player.
     auto IdleAssets = DPlayerData->IdleAssets();
     // Searches through all the IdleAssets.
     // ":" is the range operator in c++ 11. It goes through all the elements
     // in a list.
     for(auto WeakAsset : IdleAssets){
         // Checks whether the asset can be assigned to the current asset.
         // lock() checks whether the pointer is valid.
         if(auto Asset = WeakAsset.lock()){
             // Checks whether the current asset has a speed property and that
             // it is not a peasant. If those two things are true, then the unit
             // should be a fighter.
             if(Asset->Speed() && (atPeasant != Asset->Type())){
                 // Checks if the asset is currently not standing ground.
                 if(!Asset->HasAction(aaStandGround) && !Asset->HasActiveCapability(actStandGround)){
                     // If the unit is not standing ground it is added to a list
                     // of actors (assets that can act) which will perform an
                     // action as a group.
                     command.DActors.push_back(Asset);
                 }
             }
         }
     }
     // Checks whether there are any actors ready to receive orders.
     if(command.DActors.size()){
         // Makes the fighters Stand Ground
         command.DAction = actStandGround;
         // returns true because it was able to activate some fighters
         return true;
     }
     // returns false if there are no fighters to activate
     return false;
 }
ActivatePeasants()
bool CAIPlayer::ActivatePeasants (SPlayerCommandRequest & command, bool trainmore) protected
Function used by the AI to produce peasants and to make them gather resources.
How It Works
The function checks if there are any peasants that are idle or if there are any that could be interrupted from what they are doing. Then it has some logic that determines whether the peasants should be gathering wood or gold. For example if the AI currently has too much gold or too many gold miners, those peasants will be reassigned to harvest lumber. If there are no idle peasants or none that need to be switched, but trainmore is true, the function will check if the AI has enough resources to train a peasant, and if it can it will do so.
Definition at line 439 of file AIPlayer.cpp.
References aaHarvestLumber, aaMineGold, aaNone, actBuildPeasant, actConvey, actMine, atGoldMine, SPlayerCommandRequest::DAction, SPlayerCommandRequest::DActors, DPlayerData, SPlayerCommandRequest::DTargetColor, SPlayerCommandRequest::DTargetLocation, SPlayerCommandRequest::DTargetType, CPlayerCapability::FindCapability(), SearchMap(), CPosition::SetFromTile(), CTerrainMap::ttTree, and CPosition::X().
Referenced by CalculateCommand().
{
     //auto IdleAssets = DPlayerData->IdleAssets();
     std::shared_ptr< CPlayerAsset > MiningAsset;
     std::shared_ptr< CPlayerAsset > InterruptibleAsset;
     std::shared_ptr< CPlayerAsset > TownHallAsset;
     int GoldMiners = 0;
     int LumberHarvesters = 0;
     bool SwitchToGold = false;
     bool SwitchToLumber = false;
     // Iterates through all of the AI's assets.
     for(auto WeakAsset : DPlayerData->Assets()){
         // Checks that the asset pointer is valid.
         if(auto Asset = WeakAsset.lock()){
             // Checks if the asset has the ability to mine (is a peasant).
             if(Asset->HasCapability(actMine)){
                 // Checks there is no peasant mining and if the current asset
                 // is idle.
                 if(!MiningAsset && (aaNone == Asset->Action())){
                     MiningAsset = Asset;
                 }
                 // Checks if the asset is currently mining.
                 if(Asset->HasAction(aaMineGold)){
                     GoldMiners++;
                     // Checks if the asset can be interrupted (stopped from its
                     // current action), and if it is not idle.
                     if(Asset->Interruptible() && (aaNone != Asset->Action())){
                         InterruptibleAsset = Asset;
                     }
                 }
                 // Checks if the asset is currently harvesting wood.
                 else if(Asset->HasAction(aaHarvestLumber)){
                     LumberHarvesters++;
                     if(Asset->Interruptible() && (aaNone != Asset->Action())){
                         InterruptibleAsset = Asset;
                     }
                 }
             }
             // Checks if the asset is a Town Hall and whether it is idle.
             if(Asset->HasCapability(actBuildPeasant) && (aaNone == Asset->Action())){
                 TownHallAsset = Asset;
             }
         }
     }
     if((2 <= GoldMiners)&&(0 == LumberHarvesters)){
         SwitchToLumber = true;
     }
     else if((2 <= LumberHarvesters)&&(0 == GoldMiners)){
         SwitchToGold = true;
     }
     // Checks if there is an idle peasant, or if a peasant must switch from
     // gathering wood to gathering gold, or vice versa.
     if(MiningAsset || (InterruptibleAsset && (SwitchToLumber || SwitchToGold))){
         // Checks if there is a peasant that just finished gathering a resource.
         if(MiningAsset && (MiningAsset->Lumber() || MiningAsset->Gold())){
             // Makes that peasant take the resources back to Town Hall.
             command.DAction = actConvey;
             command.DTargetColor = TownHallAsset->Color();
             command.DActors.push_back(MiningAsset);
             command.DTargetType = TownHallAsset->Type();
             command.DTargetLocation = TownHallAsset->Position();
         }
         else{
             // Checks if there are no idle peasants.
             if(!MiningAsset){
                 // Since the function got here, it means that the AI needs to
                 // gather a different resource, but there are no idle peasants,
                 // so one of them must be interrupted.
                 MiningAsset = InterruptibleAsset;
             }
             // Finds the nearest gold mine.
             auto GoldMineAsset = DPlayerData->FindNearestAsset(MiningAsset->Position(), atGoldMine);
             // Checks if there are peasants gathering gold and either the
             // AI has three times more gold than lumber, or there
             // are too many peasants mining gold.
             if(GoldMiners && ((DPlayerData->Gold() > DPlayerData->Lumber() * 3) || SwitchToLumber)){
                 // Finds the nearest tree tile location
                 CPosition LumberLocation = DPlayerData->PlayerMap()->FindNearestReachableTileType(MiningAsset->TilePosition(), CTerrainMap::ttTree);
                 // Checks if a tree tile was found.
                 if(0 <= LumberLocation.X()){
                     // Makes the peasant start gathering wood.
                     command.DAction = actMine;
                     command.DActors.push_back(MiningAsset);
                     command.DTargetLocation.SetFromTile(LumberLocation);
                 }
                 else{
                     // If no wood was found, the map must be explored so wood is
                     // found.
                     return SearchMap(command);
                 }
             }
             else{
                 // If there aren't too many gold miners or if the AI doesn't
                 // have too much gold, the peasants will be given the command
                 // to mine gold.
                 command.DAction = actMine;
                 command.DActors.push_back(MiningAsset);
                 command.DTargetType = atGoldMine;
                 command.DTargetLocation = GoldMineAsset->Position();
             }
         }
         // Peasants successfully activated.
         return true;
     }
     // If no changes must be made regarding gathering, but more peasants must
     // be produced.
     else if(TownHallAsset && trainmore){
         auto PlayerCapability = CPlayerCapability::FindCapability(actBuildPeasant);
         // Checks if the AI player has the capability to produce peasants.
         if(PlayerCapability){
             // Checks if the AI has enough resources to produce a peasant.
             if(PlayerCapability->CanApply(TownHallAsset, DPlayerData, TownHallAsset)){
                 command.DAction = actBuildPeasant;
                 command.DActors.push_back(TownHallAsset);
                 command.DTargetLocation = TownHallAsset->Position();
                 // Successfully started producing a peasant.
                 return true;
             }
         }
     }
     // Was unable to make peasants gather or to produce any peasants.
     return false;
 }
AttackEnemies()
bool CAIPlayer::AttackEnemies (SPlayerCommandRequest & command) protected
Function used by the AI to select fighters and attack the enemy.
How It Works
The function looks through all the assets of the AI and tries to find fighters that are not currently fighting, and adds them to a list. If the list isn't empty, all those fighters are ordered to attack the nearest enemy. If none are found, the AI starts searching the map.
Definition at line 184 of file AIPlayer.cpp.
References aaAttack, actAttack, atArcher, atFootman, atRanger, SPlayerCommandRequest::DAction, SPlayerCommandRequest::DActors, DPlayerData, SPlayerCommandRequest::DTargetColor, SPlayerCommandRequest::DTargetLocation, SPlayerCommandRequest::DTargetType, CPosition::IncrementX(), CPosition::IncrementY(), SearchMap(), CPosition::X(), and CPosition::Y().
Referenced by CalculateCommand().
{
     CPosition AverageLocation(0,0);
     // The functions searches through all of the AI's assets to find fighters.
     for(auto WeakAsset : DPlayerData->Assets()){
         if(auto Asset = WeakAsset.lock()){
             if((atFootman == Asset->Type())||(atArcher == Asset->Type())||(atRanger == Asset->Type())){
                 // Checks if the fighter is currently not attacking.
                 if(!Asset->HasAction(aaAttack)){
                     // The fighter is added to a list of actors, ready to
                     // receive orders.
                     command.DActors.push_back(Asset);
                     AverageLocation.IncrementX(Asset->PositionX());
                     AverageLocation.IncrementY(Asset->PositionY());
                 }
             }
         }
     }
     // Checks if there are any actors on the list.
     if(command.DActors.size()){
         // The average location of the group is calculated, since every unit
         // is on a different tile.
         AverageLocation.X(AverageLocation.X() / command.DActors.size());
         AverageLocation.Y(AverageLocation.Y() / command.DActors.size());
         // Finds the location of the nearest enemy.
         auto TargetEnemy = DPlayerData->FindNearestEnemy(AverageLocation, -1).lock();
         // If there are no nearby enemies, get back to searching the map.
         if(!TargetEnemy){
             command.DActors.clear();
             return SearchMap(command);
         }
         // Attacks the enemy.
         command.DAction = actAttack;
         command.DTargetLocation = TargetEnemy->Position();
         command.DTargetColor = TargetEnemy->Color();
         command.DTargetType = TargetEnemy->Type();
         // Successfully attacked the enemy.
         return true;
     }
     // Failed to attack the enemy.
     return false;
 }
BuildBuilding()
bool CAIPlayer::BuildBuilding (SPlayerCommandRequest & command, EAssetType buildingtype, EAssetType neartype) protected
Function used by the AI to build a building other than the Town Hall. Returns true or false, depending on whether it was able to build or not.
How It Works
First he function tries to find a builder, the Town Hall and the building next to which it is supposed to build. The functions has multiple checks for determining whether a building is currently being built. If another building is being built, the function returns false. Otherwise it can proceed. In case no neartype was passed in, the building will be constructed next to the town hall. The building will be built such that the AI expands its base toward the center of the map. This means that for example, if the center of the map is to the North-West of the AI's Town Hall, the building will be constructed to the North-West of the neartype building.
Definition at line 294 of file AIPlayer.cpp.
References aaConstruct, aaNone, actBuildBarracks, actBuildBlacksmith, actBuildFarm, actBuildLumberMill, actBuildPeasant, atBarracks, atBlacksmith, atLumberMill, SPlayerCommandRequest::DAction, SPlayerCommandRequest::DActors, CPosition::DecrementX(), CPosition::DecrementY(), DPlayerData, SPlayerCommandRequest::DTargetLocation, CPlayerCapability::FindCapability(), CPosition::IncrementX(), CPosition::IncrementY(), SearchMap(), CPosition::SetFromTile(), CPosition::X(), and CPosition::Y().
Referenced by CalculateCommand().
{
     std::shared_ptr< CPlayerAsset > BuilderAsset;
     std::shared_ptr< CPlayerAsset > TownHallAsset;
     std::shared_ptr< CPlayerAsset > NearAsset;
     EAssetCapabilityType BuildAction;
     bool AssetIsIdle = false;
     // Assigns an action based on the type of building that must be built.
     switch(buildingtype){
         case atBarracks:    BuildAction = actBuildBarracks;
                             break;
         case atLumberMill:  BuildAction = actBuildLumberMill;
                             break;
         case atBlacksmith:  BuildAction = actBuildBlacksmith;
                             break;
         default:            BuildAction = actBuildFarm;
                             break;
     }
     // Loops through all the AI's assets.
     for(auto WeakAsset : DPlayerData->Assets()){
         // Checks that the asset pointer is valid.
         if(auto Asset = WeakAsset.lock()){
             // Checks if the asset is able to build a specific building,
             // and whether it can be interrupted from whatever it is doing.
             if(Asset->HasCapability(BuildAction) && Asset->Interruptible()){
                 // Checks if no builder was assinged yet, or if there is a
                 // mismatch between the local bool AssetIsIdle and whether
                 // the asset really is idle.
                 if(!BuilderAsset || (!AssetIsIdle && (aaNone == Asset->Action()))){
                     BuilderAsset = Asset;
                     // Sets AssetIsIdle to true if the asset isn't doing
                     // anything.
                     AssetIsIdle = aaNone == Asset->Action();
                 }
             }
             // Checks if the asset can build peasants (basically looking for a
             // Town Hall).
             if(Asset->HasCapability(actBuildPeasant)){
                 TownHallAsset = Asset;
             }
             // Checks if the asset is currently building.
             if(Asset->HasActiveCapability(BuildAction)){
                 // Returns false, most likely because it can better determine
                 // what it needs to do after the building is completed. It might
                 // change where this building should be built, or whether it
                 // should be built at all.
                 return false;
             }
             // Checks if this asset is a building of type neartype, and if
             // that building isn't currently being contructed.
             if((neartype == Asset->Type())&&(aaConstruct != Asset->Action())){
                 NearAsset = Asset;
             }
             // Checks if the asset is a building of type buildingtype.
             if(buildingtype == Asset->Type()){
                 // Checks if the building is currently being built.
                 if(aaConstruct == Asset->Action()){
                     // Returns false to avoid building more buildings than
                     // needed.
                     return false;
                 }
             }
         }
     }
     //Checks if the building the AI is trying to build is not the same as the
     // building it is supposed to be build near, and  if there is no building
     // of the neartype.
     if((buildingtype != neartype) && !NearAsset){
         // Returns false because there is no building that buildingtype can be
         // built near.
         return false;
     }
     // Checks if there is a builder (peasant).
     if(BuilderAsset){
         auto PlayerCapability = CPlayerCapability::FindCapability(BuildAction);
         // Sets the position where to build at the Town Hall, in case no
         // neartype is passed in.
         CPosition SourcePosition = TownHallAsset->TilePosition();
         CPosition MapCenter(DPlayerData->PlayerMap()->Width()/2, DPlayerData->PlayerMap()->Height()/2);
         // If a neartype is passed in, it sets the source to that.
         if(NearAsset){
             SourcePosition = NearAsset->TilePosition();
         }
         /*
             The next four if statements are used to determine how to adjust the
             source position. The adjustment is calculated based on where the
             center of the map is. The source position is adjusted in such a way
             that the AI will expand its base toward the center of the map.
         */
         if(MapCenter.X() < SourcePosition.X()){
             SourcePosition.DecrementX(TownHallAsset->Size()/2);
         }
         else if(MapCenter.X() > SourcePosition.X()){
             SourcePosition.IncrementX(TownHallAsset->Size()/2);
         }
         if(MapCenter.Y() < SourcePosition.Y()){
             SourcePosition.DecrementY(TownHallAsset->Size()/2);
         }
         else if(MapCenter.Y() > SourcePosition.Y()){
             SourcePosition.IncrementY(TownHallAsset->Size()/2);
         }
         // Finds the best location to build, based on the source position.
         CPosition Placement = DPlayerData->FindBestAssetPlacement(SourcePosition, BuilderAsset, buildingtype, 1);
         // Checks if a placement was not found.
         if(0 > Placement.X()){
             // Searches the map for another place where it could build.
             return SearchMap(command);
         }
         // Checks if the AI Player is capable of building.
         if(PlayerCapability){
             // Checks if the AI Player can start building, based on the chosen
             // peasant and the AI's current resources.
             if(PlayerCapability->CanInitiate(BuilderAsset, DPlayerData)){
                 // Checks if a placement was found.
                 if(0 <= Placement.X()){
                     // The builder is commanded to build at the chosen position,
                     // and true is returned.
                     command.DAction = BuildAction;
                     command.DActors.push_back(BuilderAsset);
                     command.DTargetLocation.SetFromTile(Placement);
                     return true;
                 }
             }
         }
     }
     // Returns false if it was unable to build the building.
     return false;
 }
BuildTownHall()
bool CAIPlayer::BuildTownHall (SPlayerCommandRequest & command) protected
Function used by the AI to build a Town Hall. Returns true or false, depending on whether it was able to build or not.
How It Works
First the function looks through all the AI's assets to find one that can build things. Once a builder is found, the function looks for the closest gold mine to the builder. Next, it determines the best position to build the Town Hall. Usually that is right next to the mine, so the peasants can mine gold faster. If it finds a good position, it commands that builder to build a Town Hall. If it can't find a placement for the building, it will search the map. If a Town Hall can't be built, the function returns false.
Definition at line 236 of file AIPlayer.cpp.
References actBuildTownHall, atGoldMine, atTownHall, SPlayerCommandRequest::DAction, SPlayerCommandRequest::DActors, DPlayerData, SPlayerCommandRequest::DTargetLocation, SearchMap(), CPosition::SetFromTile(), and CPosition::X().
Referenced by CalculateCommand().
{
     // Creates a list of the AI's idle assets.
     auto IdleAssets = DPlayerData->IdleAssets();
     // Declares a pointer to an asset.
     std::shared_ptr< CPlayerAsset > BuilderAsset;
     // Looks through every idle asset
     for(auto WeakAsset : IdleAssets){
         // Checks whether the asset pointer is valid and assigns it to Asset.
         if(auto Asset = WeakAsset.lock()){
             // Checks whether the asset is able to build a Town Hall.
             if(Asset->HasCapability(actBuildTownHall)){
                 // If the asset can build a Town Hall, the BuilderAsset will be
                 // set to point to that asset.
                 BuilderAsset = Asset;
                 break;
             }
         }
     }
     // Checks if an asset that can build was found (or peasant).
     if(BuilderAsset){
         // Find the gold mine that is nearest to the peasant and assign it to a
         // variable.
         auto GoldMineAsset = DPlayerData->FindNearestAsset(BuilderAsset->Position(), atGoldMine);
         // Finds the best place to build the Town Hall, based on the gold mine's
         // position.
         CPosition Placement = DPlayerData->FindBestAssetPlacement(GoldMineAsset->TilePosition(), BuilderAsset, atTownHall, 1);
         // Checks if a position for the Town Hall was found
         if(0 <= Placement.X()){
             // Assigns up the command to execute (Build Town Hall).
             command.DAction = actBuildTownHall;
             // Adds the actor who is supposed to perform the action to DActors.
             command.DActors.push_back(BuilderAsset);
             // Sets the location where the action should be performed.
             command.DTargetLocation.SetFromTile(Placement);
             // Returns true because the peasant started building.
             return true;
         }
         else{
             // Searches the map to find another position. Possible reason
             // could be that there was no gold mine nearby. Returns the result
             // of that search.
             return SearchMap(command);
         }
     }
     // Returns false if it couldn't build a Town Hall.
     return false;
 }
CalculateCommand()
void CAIPlayer::CalculateCommand (SPlayerCommandRequest & command)
Decides what actions the AI should take.
How It Works
Explanation of how it works on AI Main Page.
Definition at line 714 of file AIPlayer.cpp.
References ActivateFighters(), ActivatePeasants(), actNone, atArcher, atBarracks, atCastle, atFarm, atFootman, atGoldMine, atKeep, atLumberMill, atNone, atPeasant, atRanger, AttackEnemies(), atTownHall, BuildBuilding(), BuildTownHall(), SPlayerCommandRequest::DAction, SPlayerCommandRequest::DActors, DCycle, DDownSample, DPlayerData, SPlayerCommandRequest::DTargetColor, SPlayerCommandRequest::DTargetType, FindEnemies(), pcNone, SearchMap(), TrainArcher(), and TrainFootman().
{
     command.DAction = actNone;
     command.DActors.clear();
     command.DTargetColor = pcNone;
     command.DTargetType = atNone;
     // Checks if the AI is allowed to take an action yet.
     if((DCycle % DDownSample) == 0){
         // Checks if the AI has any gold left in the local gold mine.
         if(0 == DPlayerData->FoundAssetCount(atGoldMine)){
             // Search for gold mine
             SearchMap(command);
         }
         // Checks if there is a Town Hall
         else if((0 == DPlayerData->PlayerAssetCount(atTownHall))&&(0 == DPlayerData->PlayerAssetCount(atKeep))&&(0 == DPlayerData->PlayerAssetCount(atCastle))){
             BuildTownHall(command);
         }
         // Checks if the AI has fewer than five peasants
         else if(5 > DPlayerData->PlayerAssetCount(atPeasant)){
             // Makes the peasants gather resources/ produce more peasants.
             ActivatePeasants(command, true);
         }
         // Checks if the AI has enough map visibility.
         else if(12 > DPlayerData->VisibilityMap()->SeenPercent(100)){
             // Starts searching the map to get more visibility.
             SearchMap(command);
         }
         else{
             // CompletedAction is initialized to false, and set to true if the
             // AI has completed an action. To prevent the AI from completing
             // multiple actions in one cycle, every if statement checks
             // !CompletedAction
             bool CompletedAction = false;
             int BarracksCount = 0;
             int FootmanCount = DPlayerData->PlayerAssetCount(atFootman);
             int ArcherCount = DPlayerData->PlayerAssetCount(atArcher)+DPlayerData->PlayerAssetCount(atRanger);
             // Checks whether the food consumption of units is bigger than
             // the food production
             if(!CompletedAction && (DPlayerData->FoodConsumption() >= DPlayerData->FoodProduction())){
                 // Builds a farm to have more food production
                 CompletedAction = BuildBuilding(command, atFarm, atFarm);
             }
             if(!CompletedAction){
                 // Makes peasants go back to gathering, because they will be
                 // idle after building a farm.
                 CompletedAction = ActivatePeasants(command, false);
             }
             // Checks whether the AI has a Barracks
             if(!CompletedAction && (0 == (BarracksCount = DPlayerData->PlayerAssetCount(atBarracks)))){
                 // Builds a Barracks next to a Farm
                 CompletedAction = BuildBuilding(command, atBarracks, atFarm);
             }
             // Checks if there are fewer than five Footmen
             if(!CompletedAction && (5 > FootmanCount)){
                 // Trains a footman
                 CompletedAction = TrainFootman(command);
             }
             // Checks whether the AI has a Lumber Mill
             if(!CompletedAction && (0 == DPlayerData->PlayerAssetCount(atLumberMill))){
                 // Builds a Lumber Mill next to the Barracks
                 CompletedAction = BuildBuilding(command, atLumberMill, atBarracks);
             }
             // Checks whether the AI has fewer than five archers
             if(!CompletedAction &&  (5 > ArcherCount)){
                 // Trains an Archer
                 CompletedAction = TrainArcher(command);
             }
             // It checks whether it has a Footman.
             if(!CompletedAction && DPlayerData->PlayerAssetCount(atFootman)){
                 // Sends the Footman to find the enemy.
                 CompletedAction = FindEnemies(command);
             }
             if(!CompletedAction){
                 // Selects the fighters
                 CompletedAction = ActivateFighters(command);
             }
             // Checks if the AI has at least five Footmen and five Archers.
             if(!CompletedAction && ((5 <= FootmanCount) && (5 <= ArcherCount))){
                 CompletedAction = AttackEnemies(command);
             }
         }
     }
     DCycle++;
 }
FindEnemies()
bool CAIPlayer::FindEnemies (SPlayerCommandRequest & command) protected
Function used by the AI to find enemies by searching assets that are visible to it on the map.
How It Works
It first finds a Town Hall of the AI, then it searches in a range around that building. The range in this case is unlimited. The function calls CPlayerData::FindNearestEnemy, which iterates through all the assets the AI can see on the map and checks whether its player color is different than the AI's. It also checks if that asset it found is alive. If the pointer to the nearest enemy is expired, the function returns the result of SearchMap. It returns false if it can't find anything.
Definition at line 150 of file AIPlayer.cpp.
References actBuildPeasant, DPlayerData, and SearchMap().
Referenced by CalculateCommand().
{
     std::shared_ptr< CPlayerAsset > TownHallAsset;
     // This loop looks through assets to find a Town Hall.
     for(auto WeakAsset : DPlayerData->Assets()){
         if(auto Asset = WeakAsset.lock()){
             if(Asset->HasCapability(actBuildPeasant)){
                 TownHallAsset = Asset;
                 break;
             }
         }
     }
     // Checks if the pointer to the enemy has expired (was deleted).
     // It starts searching for an enemy from the Town Hall.
     // The range is unlimited (-1).
     // FindNearestEnemy searches for an asset on the map that has a different
     // color than the AI and that is alive.
     if(DPlayerData->FindNearestEnemy(TownHallAsset->Position(), -1).expired()){
         // If the asset pointer is expired it starts exploring the map.
         return SearchMap(command);
     }
     // Returns false if it didn't find an enemy.
     return false;
 }
SearchMap()
bool CAIPlayer::SearchMap (SPlayerCommandRequest & command) protected
Definition at line 106 of file AIPlayer.cpp.
References actMove, SPlayerCommandRequest::DAction, SPlayerCommandRequest::DActors, DPlayerData, SPlayerCommandRequest::DTargetLocation, CPosition::SetFromTile(), CTerrainMap::ttNone, and CPosition::X().
Referenced by ActivatePeasants(), AttackEnemies(), BuildBuilding(), BuildTownHall(), CalculateCommand(), and FindEnemies().
{
     auto IdleAssets = DPlayerData->IdleAssets();
     std::shared_ptr< CPlayerAsset > MovableAsset;
     // This loop searches through all the idle assets of the AI to find one that
     // can move.
     for(auto WeakAsset : IdleAssets){
         if(auto Asset = WeakAsset.lock()){
             if(Asset->Speed()){
                 MovableAsset = Asset;
                 break;
             }
         }
     }
     // Checks if a unit was found.
     if(MovableAsset){
         // Finds the nearest tile that is still covered by fog of war.
         CPosition UnknownPosition = DPlayerData->PlayerMap()->FindNearestReachableTileType(MovableAsset->TilePosition(), CTerrainMap::ttNone);
         // Checks if it has found an unexplored tile.
         if(0 <= UnknownPosition.X()){
             //printf("Unkown Position (%d, %d)\n", UnknownPosition.X(), UnknownPosition.Y());
             // Moves the unit toward that tile.
             command.DAction = actMove;
             command.DActors.push_back(MovableAsset);
             command.DTargetLocation.SetFromTile(UnknownPosition);
             // Successfully explored more of the map.
             return true;
         }
     }
     // Couldn't explore more of the map.
     return false;
 }
TrainArcher()
bool CAIPlayer::TrainArcher (SPlayerCommandRequest & command) protected
Function used by the AI to train Archers.
How It Works
The function first checks whether the AI has an idle asset which can train Archers. Then it checks whether the AI has the ability to train archers and the resources necessary to do so. If those conditions are met, the Barracks is given a command to build a Footman.
Definition at line 663 of file AIPlayer.cpp.
References actBuildArcher, actBuildRanger, SPlayerCommandRequest::DAction, SPlayerCommandRequest::DActors, DPlayerData, SPlayerCommandRequest::DTargetLocation, and CPlayerCapability::FindCapability().
Referenced by CalculateCommand().
{
     auto IdleAssets = DPlayerData->IdleAssets();
     std::shared_ptr< CPlayerAsset > TrainingAsset;
     EAssetCapabilityType BuildType = actBuildArcher;
     // Searches through a list of all idle assets for one which has the
     // capability of training Archers (Lumber Mill).
     for(auto WeakAsset : IdleAssets){
         if(auto Asset = WeakAsset.lock()){
             if(Asset->HasCapability(actBuildArcher)){
                 TrainingAsset = Asset;
                 BuildType = actBuildArcher;
                 break;
             }
             if(Asset->HasCapability(actBuildRanger)){
                 TrainingAsset = Asset;
                 BuildType = actBuildRanger;
                 break;
             }
         }
     }
     // Checks if Lumber Mill was found.
     if(TrainingAsset){
         // Finds the AI's ability to train Archers.
         auto PlayerCapability = CPlayerCapability::FindCapability(BuildType);
         if(PlayerCapability){
             // Checks if the AI has enough resources to train an Archer.
             if(PlayerCapability->CanApply(TrainingAsset, DPlayerData, TrainingAsset)){
                 // Gives the Lumber Mill the command to train an archer
                 command.DAction = BuildType;
                 command.DActors.push_back(TrainingAsset);
                 command.DTargetLocation = TrainingAsset->Position();
                 // Returns true because it was successful.
                 return true;
             }
         }
     }
      // Returns false because it was unable to train an Archer.
     return false;
 }
TrainFootman()
bool CAIPlayer::TrainFootman (SPlayerCommandRequest & command) protected
Function used by the AI to train Footmen.
How It Works
The function first checks whether the AI has an idle asset which can train Footmen. Then it checks whether the AI has the ability to train footmen and the resources necessary to do so. If those conditions are met, the Barracks is given a command to build a Footman.
Definition at line 618 of file AIPlayer.cpp.
References actBuildFootman, SPlayerCommandRequest::DAction, SPlayerCommandRequest::DActors, DPlayerData, SPlayerCommandRequest::DTargetLocation, and CPlayerCapability::FindCapability().
Referenced by CalculateCommand().
{
     auto IdleAssets = DPlayerData->IdleAssets();
     std::shared_ptr< CPlayerAsset > TrainingAsset;
     // Searches through a list of all idle assets for one which has the
     // capability of training Footmen (Barracks).
     for(auto WeakAsset : IdleAssets){
         if(auto Asset = WeakAsset.lock()){
             if(Asset->HasCapability(actBuildFootman)){
                 TrainingAsset = Asset;
                 break;
             }
         }
     }
     // Checks if a Barracks was found
     if(TrainingAsset){
         // Finds the AI's ability to train Footmen
         auto PlayerCapability = CPlayerCapability::FindCapability(actBuildFootman);
         // Checks if the AI has the capability of training Footmen.
         if(PlayerCapability){
             // Checks if the AI has enough resources to train a Footman.
             if(PlayerCapability->CanApply(TrainingAsset, DPlayerData, TrainingAsset)){
                 // Gives the Barracks the command to train a Footman.
                 command.DAction = actBuildFootman;
                 command.DActors.push_back(TrainingAsset);
                 command.DTargetLocation = TrainingAsset->Position();
                 // Returns true because it was successful.
                 return true;
             }
         }
     }
     // Returns false because it was unable to train a Footman.
     return false;
 }
Member Data Documentation
DCycle
int CAIPlayer::DCycle protected
Definition at line 31 of file AIPlayer.h.
Referenced by CAIPlayer(), and CalculateCommand().
DDownSample
int CAIPlayer::DDownSample protected
Definition at line 32 of file AIPlayer.h.
Referenced by CAIPlayer(), and CalculateCommand().
DPlayerData
std::shared_ptr< CPlayerData > CAIPlayer::DPlayerData protected
Definition at line 30 of file AIPlayer.h.
Referenced by ActivateFighters(), ActivatePeasants(), AttackEnemies(), BuildBuilding(), BuildTownHall(), CAIPlayer(), CalculateCommand(), FindEnemies(), SearchMap(), TrainArcher(), and TrainFootman().
The documentation for this class was generated from the following files:
include/AIPlayer.h
src/AIPlayer.cpp