ECS 160 Project: CPosition Class Reference
CPosition Class Reference
#include <Position.h>
Public Member Functions
CPosition ()=default
CPosition (int x, int y)
CPosition (const CPosition &pos)=default
CPosition & operator= (const CPosition &pos)=default
bool operator== (const CPosition &pos) const
bool operator!= (const CPosition &pos) const
int X () const
int X (int x)
int IncrementX (int x)
int DecrementX (int x)
int Y () const
int Y (int y)
int IncrementY (int y)
int DecrementY (int y)
void SetFromTile (const CPosition &pos)
void SetXFromTile (int x)
void SetYFromTile (int y)
void SetToTile (const CPosition &pos)
void SetXToTile (int x)
void SetYToTile (int y)
bool TileAligned () const
EDirection TileOctant () const
EDirection AdjacentTileDirection (const CPosition &pos, int objsize=1) const
CPosition ClosestPosition (const CPosition &objpos, int objsize) const
EDirection DirectionTo (const CPosition &pos) const
int DistanceSquared (const CPosition &pos)
int Distance (const CPosition &pos)
Static Public Member Functions
static void SetTileDimensions (int width, int height)
static int TileWidth ()
static int TileHeight ()
static int HalfTileWidth ()
static int HalfTileHeight ()
Protected Attributes
int DX
int DY
Static Protected Attributes
static int DTileWidth = 1
static int DTileHeight = 1
static int DHalfTileWidth = 0
static int DHalfTileHeight = 0
static std::vector< std::vector< EDirection > > DOctant
static std::vector< std::vector< EDirection > > DTileDirections
Detailed Description
Definition at line 22 of file Position.h.
Constructor & Destructor Documentation
CPosition() [1/3]
CPosition::CPosition () default
CPosition() [2/3]
CPosition::CPosition (int x, int y)
Definition at line 29 of file Position.cpp.
References DX, and DY.
{
     DX = x;
     DY = y;
 }
CPosition() [3/3]
CPosition::CPosition (const CPosition & pos) default
Member Function Documentation
AdjacentTileDirection()
EDirection CPosition::AdjacentTileDirection (const CPosition & pos, int objsize = 1) const
Definition at line 151 of file Position.cpp.
References ClosestPosition(), dMax, DTileDirections, DX, DY, SetFromTile(), and SetToTile().
Referenced by TileAligned().
{
     if(1 == objsize){
         int DeltaX = pos.DX - DX;
         int DeltaY = pos.DY - DY;
         if((1 < (DeltaX * DeltaX))||(1 < (DeltaY * DeltaY))){
             return dMax;
         }
         return DTileDirections[DeltaY+1][DeltaX+1];
     }
     else{
          CPosition ThisPosition;
          CPosition TargetPosition;
          ThisPosition.SetFromTile(*this);
          TargetPosition.SetFromTile(pos);
          TargetPosition.SetToTile( ThisPosition.ClosestPosition(TargetPosition, objsize) );
          return AdjacentTileDirection(TargetPosition, 1);
     }
 }
ClosestPosition()
CPosition CPosition::ClosestPosition (const CPosition & objpos, int objsize) const
Definition at line 174 of file Position.cpp.
References DistanceSquared(), IncrementX(), IncrementY(), TileHeight(), TileWidth(), and X().
Referenced by AdjacentTileDirection(), CPlayerAsset::ClosestPosition(), and TileAligned().
{
     CPosition CurPosition(objpos);
     CPosition BestPosition;
     int BestDistance = -1;
     for(int YIndex = 0; YIndex < objsize; YIndex++){
         for(int XIndex = 0; XIndex < objsize; XIndex++){
             int CurDistance = CurPosition.DistanceSquared(*this);
             if((-1 == BestDistance)||(CurDistance < BestDistance)){
                 BestDistance = CurDistance;
                 BestPosition = CurPosition;
             }
             CurPosition.IncrementX(CPosition::TileWidth());
         }
         CurPosition.X(objpos.X());
         CurPosition.IncrementY(CPosition::TileHeight());
     }
     return BestPosition;
 }
DecrementX()
int CPosition::DecrementX (int x) inline
Definition at line 75 of file Position.h.
References DX.
Referenced by CAIPlayer::BuildBuilding(), and CRouterMap::FindRoute().
{
             DX -= x;
             return DX;
         };
DecrementY()
int CPosition::DecrementY (int y) inline
Definition at line 93 of file Position.h.
References DY, SetFromTile(), SetToTile(), SetXFromTile(), SetXToTile(), SetYFromTile(), and SetYToTile().
Referenced by CAIPlayer::BuildBuilding(), and CRouterMap::FindRoute().
{
             DY -= y;
             return DY;
         };
DirectionTo()
EDirection CPosition::DirectionTo (const CPosition & pos) const
Definition at line 193 of file Position.cpp.
References DX, DY, HalfTileHeight(), HalfTileWidth(), TileHeight(), TileOctant(), and TileWidth().
Referenced by TileAligned().
{
     CPosition DeltaPosition(pos.DX - DX, pos.DY - DY);
     int DivX = DeltaPosition.DX / HalfTileWidth();
     int DivY = DeltaPosition.DY / HalfTileHeight();
     int Div;
     DivX = 0 > DivX ? -DivX : DivX;
     DivY = 0 > DivY ? -DivY : DivY;
     Div = DivX > DivY ? DivX : DivY;
     if(Div){
         DeltaPosition.DX /= Div;
         DeltaPosition.DY /= Div;
     }
     DeltaPosition.DX += HalfTileWidth();
     DeltaPosition.DY += HalfTileHeight();
     if(0 > DeltaPosition.DX){
         DeltaPosition.DX = 0;
     }
     if(0 > DeltaPosition.DY){
         DeltaPosition.DY = 0;
     }
     if(TileWidth() <= DeltaPosition.DX){
         DeltaPosition.DX = TileWidth() - 1;
     }
     if(TileHeight() <= DeltaPosition.DY){
         DeltaPosition.DY = TileHeight() - 1;
     }
     return DeltaPosition.TileOctant();
 }
Distance()
int CPosition::Distance (const CPosition & pos)
Definition at line 230 of file Position.cpp.
References DistanceSquared().
Referenced by TileAligned().
{
     // Code from http://www.codecodex.com/wiki/Calculate_an_integer_square_root
     unsigned int Op, Result, One;
     Op = DistanceSquared(pos);
     Result = 0;
     One = 1 << (sizeof(unsigned int) * 8 - 2);
     while(One > Op){
         One >>= 2;
     }
     while(0 != One){
         if(Op >= Result + One){
             Op -= Result + One;
             Result += One << 1;  // <-- faster than 2 * one
         }
         Result >>= 1;
         One >>= 2;
     }
     return Result;
 }
DistanceSquared()
int CPosition::DistanceSquared (const CPosition & pos)
Definition at line 223 of file Position.cpp.
References DX, and DY.
Referenced by ClosestPosition(), Distance(), CAssetDecoratedMap::FindAssetPlacement(), CRouterMap::FindRoute(), TileAligned(), and CGameModel::Timestep().
{
     int DeltaX = pos.DX - DX;
     int DeltaY = pos.DY - DY;
     return DeltaX * DeltaX + DeltaY * DeltaY;
 }
HalfTileHeight()
static int CPosition::HalfTileHeight () inline static
Definition at line 58 of file Position.h.
References DHalfTileHeight.
Referenced by DirectionTo(), CAssetRenderer::DrawAssets(), CAssetRenderer::DrawOverlays(), CAssetRenderer::DrawPlacement(), CAssetRenderer::DrawSelections(), and CGameModel::Timestep().
{
             return DHalfTileHeight;
         };
HalfTileWidth()
static int CPosition::HalfTileWidth () inline static
Definition at line 54 of file Position.h.
References DHalfTileWidth.
Referenced by DirectionTo(), CAssetRenderer::DrawAssets(), CAssetRenderer::DrawOverlays(), CAssetRenderer::DrawPlacement(), CAssetRenderer::DrawSelections(), and CGameModel::Timestep().
{
             return DHalfTileWidth;
         };
IncrementX()
int CPosition::IncrementX (int x) inline
Definition at line 70 of file Position.h.
References DX.
Referenced by CAIPlayer::AttackEnemies(), CAIPlayer::BuildBuilding(), ClosestPosition(), CAssetRenderer::DrawPlacement(), and CPlayerAsset::MoveStep().
{
             DX += x;
             return DX;
         };
IncrementY()
int CPosition::IncrementY (int y) inline
Definition at line 88 of file Position.h.
References DY.
Referenced by CAIPlayer::AttackEnemies(), CAIPlayer::BuildBuilding(), ClosestPosition(), CAssetRenderer::DrawPlacement(), CPlayerAsset::MoveStep(), and CApplicationData::ProcessInputGameMode().
{
             DY += y;
             return DY;
         };
operator!=()
bool CPosition::operator!= (const CPosition & pos) const
Definition at line 38 of file Position.cpp.
References DX, and DY.
{
     return (DX != pos.DX) || (DY != pos.DY);
 }
operator=()
CPosition& CPosition::operator= (const CPosition & pos) default
operator==()
bool CPosition::operator== (const CPosition & pos) const
Definition at line 34 of file Position.cpp.
References DX, and DY.
{
     return (DX == pos.DX) && (DY == pos.DY);
 }
SetFromTile()
void CPosition::SetFromTile (const CPosition & pos)
Definition at line 121 of file Position.cpp.
References DHalfTileHeight, DHalfTileWidth, DTileHeight, DTileWidth, DX, and DY.
Referenced by CAIPlayer::ActivatePeasants(), AdjacentTileDirection(), CAIPlayer::BuildBuilding(), CAIPlayer::BuildTownHall(), DecrementY(), CAssetRenderer::DrawPlacement(), CApplicationData::ProcessInputGameMode(), CAIPlayer::SearchMap(), CPlayerAsset::TilePosition(), and CGameModel::Timestep().
{
     DX = pos.DX * DTileWidth + DHalfTileWidth;
     DY = pos.DY * DTileHeight + DHalfTileHeight;
 }
SetTileDimensions()
void CPosition::SetTileDimensions (int width, int height) static
Definition at line 42 of file Position.cpp.
References dEast, DHalfTileHeight, DHalfTileWidth, dMax, dNorth, dNorthEast, dNorthWest, DOctant, dSouth, dSouthEast, dSouthWest, DTileHeight, DTileWidth, dWest, X(), and Y().
Referenced by CApplicationData::Init().
{
     if((0 < width)&&(0 < height)){
         DTileWidth = width;
         DTileHeight = height;
         DHalfTileWidth = width / 2;
         DHalfTileHeight = height / 2;
         DOctant.resize(DTileHeight);
         for(auto &Row : DOctant){
             Row.resize(DTileWidth);
         }
         for(int Y = 0; Y < DTileHeight; Y++){
             for(int X = 0; X < DTileWidth; X++){
                 int XDistance = X - DHalfTileWidth;
                 int YDistance = Y - DHalfTileHeight;
                 bool NegativeX = XDistance < 0;
                 bool NegativeY = YDistance > 0; // Top of screen is 0
                 double SinSquared;
                 XDistance *= XDistance;
                 YDistance *= YDistance;
                 if(0 == (XDistance + YDistance)){
                     DOctant[Y][X] = dMax;
                     continue;
                 }
                 SinSquared = (double)YDistance / (XDistance + YDistance);
                 if(0.1464466094 > SinSquared){
                     // East or West
                     if(NegativeX){
                         DOctant[Y][X] = dWest; // West
                     }
                     else{
                         DOctant[Y][X] = dEast; // East
                     }
                 }
                 else if(0.85355339059 > SinSquared){
                     // NE, SE, SW, NW
                     if(NegativeY){
                         if(NegativeX){
                             DOctant[Y][X] = dSouthWest; // SW
                         }
                         else{
                             DOctant[Y][X] = dSouthEast; // SE
                         }
                     }
                     else{
                         if(NegativeX){
                             DOctant[Y][X] = dNorthWest; // NW
                         }
                         else{
                             DOctant[Y][X] = dNorthEast; // NE
                         }
                     }
                 }
                 else{
                     // North or South
                     if(NegativeY){
                         DOctant[Y][X] = dSouth; // South
                     }
                     else{
                         DOctant[Y][X] = dNorth; // North
                     }
                 }
             }
         }
         /*
         for(auto &Row : DOctant){
             for(auto &Cell : Row){
                 printf("%d ", Cell);
             }
             printf("\n");
         }
         */
     }
 }
SetToTile()
void CPosition::SetToTile (const CPosition & pos)
Definition at line 134 of file Position.cpp.
References DTileHeight, DTileWidth, DX, and DY.
Referenced by AdjacentTileDirection(), CPlayerCapabilityBuildNormal::ApplyCapability(), CPlayerCapabilityTrainNormal::ApplyCapability(), CPlayerCapabilityBuildRanger::ApplyCapability(), CPlayerData::CreateMarker(), DecrementY(), CAssetRenderer::DrawPlacement(), CRouterMap::FindRoute(), CPlayerAsset::MoveStep(), CPlayerAsset::Position(), CApplicationData::ProcessInputGameMode(), and CGameModel::Timestep().
{
     DX = pos.DX / DTileWidth;
     DY = pos.DY / DTileHeight;
 }
SetXFromTile()
void CPosition::SetXFromTile (int x)
Definition at line 126 of file Position.cpp.
References DHalfTileWidth, DTileWidth, and DX.
Referenced by DecrementY(), CApplicationData::MiniMapToDetailedMap(), and CPlayerAsset::TilePositionX().
{
     DX = x * DTileWidth + DHalfTileWidth;
 }
SetXToTile()
void CPosition::SetXToTile (int x)
Definition at line 139 of file Position.cpp.
References DTileWidth, and DX.
Referenced by DecrementY(), and CPlayerAsset::PositionX().
{
     DX = x / DTileWidth;
 }
SetYFromTile()
void CPosition::SetYFromTile (int y)
Definition at line 130 of file Position.cpp.
References DHalfTileHeight, DTileHeight, and DY.
Referenced by DecrementY(), CApplicationData::MiniMapToDetailedMap(), and CPlayerAsset::TilePositionY().
{
     DY = y * DTileHeight + DHalfTileHeight;
 }
SetYToTile()
void CPosition::SetYToTile (int y)
Definition at line 143 of file Position.cpp.
References DTileHeight, and DY.
Referenced by DecrementY(), and CPlayerAsset::PositionY().
{
     DY = y / DTileHeight;
 }
TileAligned()
bool CPosition::TileAligned () const inline
Definition at line 105 of file Position.h.
References AdjacentTileDirection(), ClosestPosition(), DirectionTo(), Distance(), DistanceSquared(), DTileHeight, and TileOctant().
Referenced by CPlayerAsset::TileAligned().
{
             return ((DX % DTileWidth) == DHalfTileWidth) && ((DY % DTileHeight) == DHalfTileHeight);
         };
TileHeight()
static int CPosition::TileHeight () inline static
Definition at line 50 of file Position.h.
References DTileHeight.
Referenced by ClosestPosition(), DirectionTo(), CAssetRenderer::DrawSelections(), CPlayerAsset::MoveStep(), CSoundEventRenderer::OnScreen(), and CApplicationData::ProcessInputGameMode().
{
             return DTileHeight;
         };
TileOctant()
EDirection CPosition::TileOctant () const
Definition at line 147 of file Position.cpp.
References DOctant, DTileHeight, DTileWidth, DX, and DY.
Referenced by DirectionTo(), CPlayerAsset::MoveStep(), and TileAligned().
{
     return DOctant[DY % DTileHeight][DX % DTileWidth];
 }
TileWidth()
static int CPosition::TileWidth () inline static
Definition at line 46 of file Position.h.
References DTileWidth.
Referenced by ClosestPosition(), DirectionTo(), CAssetRenderer::DrawSelections(), CPlayerAsset::MoveStep(), CSoundEventRenderer::OnScreen(), CApplicationData::ProcessInputGameMode(), RangeToDistanceSquared(), and CGameModel::Timestep().
{
             return DTileWidth;
         };
X() [1/2]
int CPosition::X () const inline
Definition at line 62 of file Position.h.
References DX.
Referenced by CAIPlayer::ActivatePeasants(), CAIPlayer::AttackEnemies(), CAIPlayer::BuildBuilding(), CAIPlayer::BuildTownHall(), CAssetDecoratedMap::CanPlaceAsset(), CViewportRenderer::CenterViewport(), CTerrainMap::ChangeTileType(), ClosestPosition(), CViewportRenderer::DetailedPosition(), CAssetRenderer::DrawPlacement(), CPlayerData::FindBestAssetPlacement(), CAssetDecoratedMap::FindNearestReachableTileType(), CTerrainMap::FindNearestTileType(), CRouterMap::FindRoute(), CApplicationData::FindUIComponentType(), CPixelType::GetPixelType(), CAssetDecoratedMap::LoadMap(), CApplicationData::MiniMapToDetailedMap(), CPlayerAsset::MoveStep(), CSoundEventRenderer::OnScreen(), CPlayerAsset::PositionX(), CApplicationData::ProcessInputGameMode(), CApplicationData::RenderGameMode(), CSoundEventRenderer::RightBias(), CApplicationData::ScreenToMiniMap(), CApplicationData::ScreenToUnitAction(), CApplicationData::ScreenToUnitDescription(), CApplicationData::ScreenToViewport(), CAIPlayer::SearchMap(), CUnitActionRenderer::Selection(), CUnitDescriptionRenderer::Selection(), SetTileDimensions(), CPlayerAsset::TilePositionX(), CTerrainMap::TileType(), CGameModel::Timestep(), CVisibilityMap::Update(), and CAssetDecoratedMap::UpdateMap().
                      {
             return DX;
         };
X() [2/2]
int CPosition::X (int x) inline
Definition at line 66 of file Position.h.
                     {
             return DX = x;
         };
Y() [1/2]
int CPosition::Y () const inline
Definition at line 80 of file Position.h.
References DY.
Referenced by CAIPlayer::AttackEnemies(), CAIPlayer::BuildBuilding(), CAssetDecoratedMap::CanPlaceAsset(), CViewportRenderer::CenterViewport(), CTerrainMap::ChangeTileType(), CViewportRenderer::DetailedPosition(), CAssetRenderer::DrawPlacement(), CPlayerData::FindBestAssetPlacement(), CAssetDecoratedMap::FindNearestReachableTileType(), CTerrainMap::FindNearestTileType(), CRouterMap::FindRoute(), CApplicationData::FindUIComponentType(), CPixelType::GetPixelType(), CAssetDecoratedMap::LoadMap(), CApplicationData::MiniMapToDetailedMap(), CPlayerAsset::MoveStep(), CSoundEventRenderer::OnScreen(), CPlayerAsset::PositionY(), CApplicationData::ProcessInputGameMode(), CApplicationData::RenderGameMode(), CApplicationData::ScreenToMiniMap(), CApplicationData::ScreenToUnitAction(), CApplicationData::ScreenToUnitDescription(), CApplicationData::ScreenToViewport(), CUnitActionRenderer::Selection(), CUnitDescriptionRenderer::Selection(), SetTileDimensions(), CPlayerAsset::TilePositionY(), CTerrainMap::TileType(), CGameModel::Timestep(), CVisibilityMap::Update(), and CAssetDecoratedMap::UpdateMap().
                      {
             return DY;
         };
Y() [2/2]
int CPosition::Y (int y) inline
Definition at line 84 of file Position.h.
                     {
             return DY = y;
         };
Member Data Documentation
DHalfTileHeight
int CPosition::DHalfTileHeight = 0 static protected
Definition at line 30 of file Position.h.
Referenced by HalfTileHeight(), SetFromTile(), SetTileDimensions(), and SetYFromTile().
DHalfTileWidth
int CPosition::DHalfTileWidth = 0 static protected
Definition at line 29 of file Position.h.
Referenced by HalfTileWidth(), SetFromTile(), SetTileDimensions(), and SetXFromTile().
DOctant
std::vector< std::vector< EDirection > > CPosition::DOctant static protected
Definition at line 31 of file Position.h.
Referenced by SetTileDimensions(), and TileOctant().
DTileDirections
std::vector< std::vector< EDirection > > CPosition::DTileDirections static protected
Definition at line 32 of file Position.h.
Referenced by AdjacentTileDirection().
DTileHeight
int CPosition::DTileHeight = 1 static protected
Definition at line 28 of file Position.h.
Referenced by SetFromTile(), SetTileDimensions(), SetToTile(), SetYFromTile(), SetYToTile(), TileAligned(), TileHeight(), and TileOctant().
DTileWidth
int CPosition::DTileWidth = 1 static protected
Definition at line 27 of file Position.h.
Referenced by SetFromTile(), SetTileDimensions(), SetToTile(), SetXFromTile(), SetXToTile(), TileOctant(), and TileWidth().
DX
int CPosition::DX protected
Definition at line 24 of file Position.h.
Referenced by AdjacentTileDirection(), CPosition(), DecrementX(), DirectionTo(), DistanceSquared(), IncrementX(), operator!=(), operator==(), SetFromTile(), SetToTile(), SetXFromTile(), SetXToTile(), TileOctant(), and X().
DY
int CPosition::DY protected
Definition at line 25 of file Position.h.
Referenced by AdjacentTileDirection(), CPosition(), DecrementY(), DirectionTo(), DistanceSquared(), IncrementY(), operator!=(), operator==(), SetFromTile(), SetToTile(), SetYFromTile(), SetYToTile(), TileOctant(), and Y().
The documentation for this class was generated from the following files:
include/Position.h
src/Position.cpp