ECS 160 Project: CPlayerCapabilityPatrol Class Reference
CPlayerCapabilityPatrol Class Reference
Classes
class CActivatedCapability
class CRegistrant
Public Member Functions
virtual ~CPlayerCapabilityPatrol ()
bool CanInitiate (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata)
bool CanApply (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
bool ApplyCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
Public Member Functions inherited from CPlayerCapability
virtual ~CPlayerCapability ()
std::string Name () const
EAssetCapabilityType AssetCapabilityType () const
ETargetType TargetType () const
Protected Member Functions
CPlayerCapabilityPatrol ()
Protected Member Functions inherited from CPlayerCapability
CPlayerCapability (const std::string &name, ETargetType targettype)
Static Protected Attributes
static CRegistrant DRegistrant
Additional Inherited Members
Public Types inherited from CPlayerCapability
enum ETargetType {
ttNone = 0, ttAsset, ttTerrain, ttTerrainOrAsset,
ttPlayer
}
typedef enum CPlayerCapability::ETargetType * ETargetTypeRef
Static Public Member Functions inherited from CPlayerCapability
static std::shared_ptr< CPlayerCapability > FindCapability (EAssetCapabilityType type)
static std::shared_ptr< CPlayerCapability > FindCapability (const std::string &name)
static EAssetCapabilityType NameToType (const std::string &name)
static std::string TypeToName (EAssetCapabilityType type)
Static Protected Member Functions inherited from CPlayerCapability
static std::unordered_map< std::string, std::shared_ptr< CPlayerCapability > > & NameRegistry ()
static std::unordered_map< int, std::shared_ptr< CPlayerCapability > > & TypeRegistry ()
static bool Register (std::shared_ptr< CPlayerCapability > capability)
Protected Attributes inherited from CPlayerCapability
std::string DName
EAssetCapabilityType DAssetCapabilityType
ETargetType DTargetType
Detailed Description
Definition at line 542 of file BasicCapabilities.cpp.
Constructor & Destructor Documentation
CPlayerCapabilityPatrol()
CPlayerCapabilityPatrol::CPlayerCapabilityPatrol () protected
Definition at line 577 of file BasicCapabilities.cpp.
                                                  : CPlayerCapability(std::string("Patrol"), ttTerrain){
 }
~CPlayerCapabilityPatrol()
virtual CPlayerCapabilityPatrol::~CPlayerCapabilityPatrol () inline virtual
Definition at line 564 of file BasicCapabilities.cpp.
References CPlayerCapabilityConvey::ApplyCapability(), CPlayerCapabilityConvey::CanApply(), CPlayerCapabilityConvey::CanInitiate(), and DRegistrant.
 {};
Member Function Documentation
ApplyCapability()
bool CPlayerCapabilityPatrol::ApplyCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target) virtual
Implements CPlayerCapability.
Definition at line 589 of file BasicCapabilities.cpp.
References aaCapability, CPlayerCapability::AssetCapabilityType(), SAssetCommand::DAction, SAssetCommand::DActivatedCapability, SAssetCommand::DAssetTarget, and SAssetCommand::DCapability.
Referenced by CPlayerCapabilityAttack::~CPlayerCapabilityAttack().
{
     if(actor->TilePosition() != target->TilePosition()){
         SAssetCommand NewCommand;
         NewCommand.DAction = aaCapability;
         NewCommand.DCapability = AssetCapabilityType();
         NewCommand.DAssetTarget = target;
         NewCommand.DActivatedCapability = std::make_shared< CActivatedCapability >(actor, playerdata, target);
         actor->ClearCommand();
         actor->PushCommand(NewCommand);
         return true;
     }
     return false;
 }
CanApply()
bool CPlayerCapabilityPatrol::CanApply (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target) virtual
Implements CPlayerCapability.
Definition at line 585 of file BasicCapabilities.cpp.
Referenced by CPlayerCapabilityAttack::~CPlayerCapabilityAttack().
{
     return actor->Speed() > 0;
 }
CanInitiate()
bool CPlayerCapabilityPatrol::CanInitiate (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata) virtual
Implements CPlayerCapability.
Definition at line 581 of file BasicCapabilities.cpp.
Referenced by CPlayerCapabilityAttack::~CPlayerCapabilityAttack().
{
     return actor->Speed() > 0;
 }
Member Data Documentation
DRegistrant
CPlayerCapabilityPatrol::CRegistrant CPlayerCapabilityPatrol::DRegistrant static protected
Definition at line 548 of file BasicCapabilities.cpp.
Referenced by ~CPlayerCapabilityPatrol().
The documentation for this class was generated from the following file:
src/BasicCapabilities.cpp