ECS 160 Project: CTokenizer Class Reference
CTokenizer Class Reference
#include <Tokenizer.h>
Public Member Functions
CTokenizer (std::shared_ptr< CDataSource > source, const std::string delimiters="")
bool Read (std::string &token)
Static Public Member Functions
static void Tokenize (std::vector< std::string > &tokens, const std::string &data, const std::string delimiters="")
Protected Attributes
std::shared_ptr< CDataSource > DDataSource
std::string DDelimiters
Detailed Description
Definition at line 24 of file Tokenizer.h.
Constructor & Destructor Documentation
CTokenizer()
CTokenizer::CTokenizer (std::shared_ptr< CDataSource > source, const std::string delimiters = "")
Definition at line 19 of file Tokenizer.cpp.
References DDataSource, and DDelimiters.
{
     DDataSource = source;
     if(delimiters.length()){
         DDelimiters = delimiters;
     }
     else{
         DDelimiters = " \t\r\n";
     }
 }
Member Function Documentation
Read()
bool CTokenizer::Read (std::string & token)
Definition at line 29 of file Tokenizer.cpp.
References DDataSource, and DDelimiters.
{
     char TempChar;
     token.clear();
     while(true){
         if(0 < DDataSource->Read(&TempChar, 1)){
             if(std::string::npos != DDelimiters.find(TempChar)){
                 token += TempChar;
             }
             else if(token.length()){
                 return true;
             }
         }
         else{
             return 0 < token.length();
         }
     }
 }
Tokenize()
void CTokenizer::Tokenize (std::vector< std::string > & tokens, const std::string & data, const std::string delimiters = "") static
Definition at line 48 of file Tokenizer.cpp.
Referenced by CCursorSet::LoadCursors(), CFontTileset::LoadFont(), CAssetDecoratedMap::LoadMap(), CTerrainMap::LoadMap(), and CGraphicTileset::LoadTileset().
{
     std::string Delimiters, TempString;
     if(delimiters.length()){
         Delimiters = delimiters;
     }
     else{
         Delimiters = " \t\r\n";
     }
     tokens.clear();
     for(size_t Index = 0; Index < data.length(); Index++){
         if(std::string::npos == Delimiters.find(data[Index])){
             TempString += data[Index];
         }
         else if(TempString.length()){
             tokens.push_back(TempString);
             TempString.clear();
         }
     }
     if(TempString.length()){
         tokens.push_back(TempString);
     }
 }
Member Data Documentation
DDataSource
std::shared_ptr< CDataSource > CTokenizer::DDataSource protected
Definition at line 26 of file Tokenizer.h.
Referenced by CTokenizer(), and Read().
DDelimiters
std::string CTokenizer::DDelimiters protected
Definition at line 27 of file Tokenizer.h.
Referenced by CTokenizer(), and Read().
The documentation for this class was generated from the following files:
include/Tokenizer.h
src/Tokenizer.cpp