ECS 160 Project: CViewportRenderer Class Reference
CViewportRenderer Class Reference
#include <ViewportRenderer.h>
Public Member Functions
CViewportRenderer (std::shared_ptr< CMapRenderer > maprender, std::shared_ptr< CAssetRenderer > assetrender, std::shared_ptr< CFogRenderer > fogrender)
~CViewportRenderer ()
void InitViewportDimensions (int width, int height)
int ViewportX () const
int ViewportX (int x)
int ViewportY () const
int ViewportY (int y)
gint LastViewportWidth () const
gint LastViewportHeight () const
void CenterViewport (const CPosition &pos)
CPosition DetailedPosition (const CPosition &pos) const
void PanNorth (int pan)
void PanEast (int pan)
void PanSouth (int pan)
void PanWest (int pan)
void DrawViewport (GdkDrawable *drawable, GdkDrawable *typedrawable, const std::list< std::weak_ptr< CPlayerAsset > > &selectionmarkerlist, const SRectangle &selectrect, EAssetCapabilityType curcapability)
Protected Attributes
std::shared_ptr< CMapRenderer > DMapRenderer
std::shared_ptr< CAssetRenderer > DAssetRenderer
std::shared_ptr< CFogRenderer > DFogRenderer
int DViewportX
int DViewportY
gint DLastViewportWidth
gint DLastViewportHeight
Detailed Description
Definition at line 23 of file ViewportRenderer.h.
Constructor & Destructor Documentation
CViewportRenderer()
CViewportRenderer::CViewportRenderer (std::shared_ptr< CMapRenderer > maprender, std::shared_ptr< CAssetRenderer > assetrender, std::shared_ptr< CFogRenderer > fogrender)
Definition at line 19 of file ViewportRenderer.cpp.
References DAssetRenderer, DFogRenderer, DLastViewportHeight, DLastViewportWidth, DMapRenderer, DViewportX, and DViewportY.
{
     DMapRenderer = maprender;
     DAssetRenderer = assetrender;
     DFogRenderer = fogrender;
     DViewportX = 0;
     DViewportY = 0;
     DLastViewportWidth = maprender->DetailedMapWidth();
     DLastViewportHeight = maprender->DetailedMapHeight();
 }
~CViewportRenderer()
CViewportRenderer::~CViewportRenderer ()
Definition at line 29 of file ViewportRenderer.cpp.
{
 }
Member Function Documentation
CenterViewport()
void CViewportRenderer::CenterViewport (const CPosition & pos)
Definition at line 56 of file ViewportRenderer.cpp.
References DLastViewportHeight, DLastViewportWidth, ViewportX(), ViewportY(), CPosition::X(), and CPosition::Y().
Referenced by LastViewportHeight().
{
     ViewportX(pos.X() - DLastViewportWidth/2);
     ViewportY(pos.Y() - DLastViewportHeight/2);
 }
DetailedPosition()
CPosition CViewportRenderer::DetailedPosition (const CPosition & pos) const inline
Definition at line 60 of file ViewportRenderer.h.
References DrawViewport(), DViewportX, DViewportY, PanEast(), PanNorth(), PanSouth(), PanWest(), CPosition::X(), and CPosition::Y().
{
             return CPosition(pos.X() + DViewportX, pos.Y() + DViewportY);
         };
DrawViewport()
void CViewportRenderer::DrawViewport (GdkDrawable * drawable, GdkDrawable * typedrawable, const std::list< std::weak_ptr< CPlayerAsset > > & selectionmarkerlist, const SRectangle & selectrect, EAssetCapabilityType curcapability)
Definition at line 84 of file ViewportRenderer.cpp.
References actBuildBarracks, actBuildBlacksmith, actBuildFarm, actBuildLumberMill, actBuildScoutTower, actBuildTownHall, atBarracks, atBlacksmith, atFarm, atLumberMill, atNone, atScoutTower, atTownHall, DAssetRenderer, DFogRenderer, SRectangle::DHeight, DLastViewportHeight, DLastViewportWidth, DMapRenderer, DViewportX, DViewportY, SRectangle::DWidth, SRectangle::DXPosition, and SRectangle::DYPosition.
Referenced by DetailedPosition().
{
     SRectangle TempRectangle;
     EAssetType PlaceType = atNone;
     std::shared_ptr< CPlayerAsset > Builder;
     gdk_pixmap_get_size(drawable, &DLastViewportWidth, &DLastViewportHeight);
     if(DViewportX + DLastViewportWidth >= DMapRenderer->DetailedMapWidth()){
         DViewportX = DMapRenderer->DetailedMapWidth() - DLastViewportWidth;
     }
     if(DViewportY + DLastViewportHeight >= DMapRenderer->DetailedMapHeight()){
         DViewportY = DMapRenderer->DetailedMapHeight() - DLastViewportHeight;
     }
     TempRectangle.DXPosition = DViewportX;
     TempRectangle.DYPosition = DViewportY;
     TempRectangle.DWidth = DLastViewportWidth;
     TempRectangle.DHeight = DLastViewportHeight;
     switch(curcapability){
         case actBuildFarm:          PlaceType = atFarm;
                                     break;
         case actBuildTownHall:      PlaceType = atTownHall;
                                     break;
         case actBuildBarracks:      PlaceType = atBarracks;
                                     break;
         case actBuildLumberMill:    PlaceType = atLumberMill;
                                     break;
         case actBuildBlacksmith:    PlaceType = atBlacksmith;
                                     break;
         case actBuildScoutTower:    PlaceType = atScoutTower;
                                     break;
         default:                    break;
     }
     DMapRenderer->DrawMap(drawable, typedrawable, TempRectangle, 0);
     DAssetRenderer->DrawSelections(drawable, TempRectangle, selectionmarkerlist, selectrect, atNone != PlaceType);
     DAssetRenderer->DrawAssets(drawable, typedrawable, TempRectangle);
     DMapRenderer->DrawMap(drawable, typedrawable, TempRectangle, 1);
     DAssetRenderer->DrawOverlays(drawable, TempRectangle);
     if(selectionmarkerlist.size()){
         Builder = selectionmarkerlist.front().lock();
     }
     DAssetRenderer->DrawPlacement(drawable, TempRectangle, CPosition(selectrect.DXPosition, selectrect.DYPosition), PlaceType, Builder);
     DFogRenderer->DrawMap(drawable, TempRectangle);
 }
InitViewportDimensions()
void CViewportRenderer::InitViewportDimensions (int width, int height) inline
Definition at line 37 of file ViewportRenderer.h.
{
             DLastViewportWidth = width;
             DLastViewportHeight = height;
         };
LastViewportHeight()
gint CViewportRenderer::LastViewportHeight () const inline
Definition at line 55 of file ViewportRenderer.h.
References CenterViewport(), and DLastViewportHeight.
{
             return DLastViewportHeight;
         };
LastViewportWidth()
gint CViewportRenderer::LastViewportWidth () const inline
Definition at line 52 of file ViewportRenderer.h.
References DLastViewportWidth.
{
             return DLastViewportWidth;
         };
PanEast()
void CViewportRenderer::PanEast (int pan)
Definition at line 68 of file ViewportRenderer.cpp.
References DViewportX, and ViewportX().
Referenced by DetailedPosition().
{
     ViewportX(DViewportX + pan);
 }
PanNorth()
void CViewportRenderer::PanNorth (int pan)
Definition at line 61 of file ViewportRenderer.cpp.
References DViewportY.
Referenced by DetailedPosition().
{
     DViewportY -= pan;
     if(0 > DViewportY){
         DViewportY = 0;
     }
 }
PanSouth()
void CViewportRenderer::PanSouth (int pan)
Definition at line 72 of file ViewportRenderer.cpp.
References DViewportY, and ViewportY().
Referenced by DetailedPosition().
{
     ViewportY(DViewportY + pan);
 }
PanWest()
void CViewportRenderer::PanWest (int pan)
Definition at line 76 of file ViewportRenderer.cpp.
References DViewportX.
Referenced by DetailedPosition().
{
     DViewportX -= pan;
     if(0 > DViewportX){
         DViewportX = 0;
     }
 }
ViewportX() [1/2]
int CViewportRenderer::ViewportX () const inline
Definition at line 42 of file ViewportRenderer.h.
References DViewportX.
Referenced by CenterViewport(), and PanEast().
{
             return DViewportX;
         };
ViewportX() [2/2]
int CViewportRenderer::ViewportX (int x)
Definition at line 34 of file ViewportRenderer.cpp.
References DLastViewportWidth, DMapRenderer, and DViewportX.
{
     DViewportX = x;
     if(DViewportX + DLastViewportWidth >= DMapRenderer->DetailedMapWidth()){
         DViewportX = DMapRenderer->DetailedMapWidth() - DLastViewportWidth;
     }
     if(0 > DViewportX){
         DViewportX = 0;
     }
     return DViewportX;
 }
ViewportY() [1/2]
int CViewportRenderer::ViewportY () const inline
Definition at line 47 of file ViewportRenderer.h.
References DViewportY.
Referenced by CenterViewport(), and PanSouth().
{
             return DViewportY;
         };
ViewportY() [2/2]
int CViewportRenderer::ViewportY (int y)
Definition at line 45 of file ViewportRenderer.cpp.
References DLastViewportHeight, DMapRenderer, and DViewportY.
{
     DViewportY = y;
     if(DViewportY + DLastViewportHeight >= DMapRenderer->DetailedMapHeight()){
         DViewportY = DMapRenderer->DetailedMapHeight() - DLastViewportHeight;
     }
     if(0 > DViewportY){
         DViewportY = 0;
     }
     return DViewportY;
 }
Member Data Documentation
DAssetRenderer
std::shared_ptr< CAssetRenderer > CViewportRenderer::DAssetRenderer protected
Definition at line 26 of file ViewportRenderer.h.
Referenced by CViewportRenderer(), and DrawViewport().
DFogRenderer
std::shared_ptr< CFogRenderer > CViewportRenderer::DFogRenderer protected
Definition at line 27 of file ViewportRenderer.h.
Referenced by CViewportRenderer(), and DrawViewport().
DLastViewportHeight
gint CViewportRenderer::DLastViewportHeight protected
Definition at line 31 of file ViewportRenderer.h.
Referenced by CenterViewport(), CViewportRenderer(), DrawViewport(), LastViewportHeight(), and ViewportY().
DLastViewportWidth
gint CViewportRenderer::DLastViewportWidth protected
Definition at line 30 of file ViewportRenderer.h.
Referenced by CenterViewport(), CViewportRenderer(), DrawViewport(), LastViewportWidth(), and ViewportX().
DMapRenderer
std::shared_ptr< CMapRenderer > CViewportRenderer::DMapRenderer protected
Definition at line 25 of file ViewportRenderer.h.
Referenced by CViewportRenderer(), DrawViewport(), ViewportX(), and ViewportY().
DViewportX
int CViewportRenderer::DViewportX protected
Definition at line 28 of file ViewportRenderer.h.
Referenced by CViewportRenderer(), DetailedPosition(), DrawViewport(), PanEast(), PanWest(), and ViewportX().
DViewportY
int CViewportRenderer::DViewportY protected
Definition at line 29 of file ViewportRenderer.h.
Referenced by CViewportRenderer(), DetailedPosition(), DrawViewport(), PanNorth(), PanSouth(), and ViewportY().
The documentation for this class was generated from the following files:
include/ViewportRenderer.h
src/ViewportRenderer.cpp