ECS 160 Project: CPixelType Class Reference
CPixelType Class Reference
#include <PixelType.h>
Public Types
enum EAssetTerrainType {
attNone = 0, attGrass, attDirt, attRock,
attTree, attStump, attWater, attWall,
attWallDamaged, attRubble, attPeasant, attFootman,
attArcher, attRanger, attGoldMine, attTownHall,
attKeep, attCastle, attFarm, attBarracks,
attLumberMill, attBlacksmith, attScoutTower, attGuardTower,
attCannonTower, attMax
}
typedef enum CPixelType::EAssetTerrainType * EAssetTerrainTypeRef
Public Member Functions
CPixelType (int red, int green, int blue)
CPixelType (CTerrainMap::ETileType type)
CPixelType (const CPlayerAsset &asset)
CPixelType (const CPixelType &pixeltype)
CPixelType & operator= (const CPixelType &pixeltype)
EAssetTerrainType Type () const
EPlayerColor Color () const
guint32 ToPixelColor () const
EAssetType AssetType () const
Static Public Member Functions
static CPixelType GetPixelType (GdkDrawable *drawable, const CPosition &pos)
static CPixelType GetPixelType (GdkDrawable *drawable, gint xpos, gint ypos)
Protected Attributes
EAssetTerrainType DType
EPlayerColor DColor
Static Protected Attributes
static GdkPixbuf * DPixbufTranslater = nullptr
Detailed Description
Definition at line 23 of file PixelType.h.
Member Typedef Documentation
EAssetTerrainTypeRef
typedef enum CPixelType::EAssetTerrainType * CPixelType::EAssetTerrainTypeRef
Member Enumeration Documentation
EAssetTerrainType
enum CPixelType::EAssetTerrainType
Enumerator
attNone
attGrass
attDirt
attRock
attTree
attStump
attWater
attWall
attWallDamaged
attRubble
attPeasant
attFootman
attArcher
attRanger
attGoldMine
attTownHall
attKeep
attCastle
attFarm
attBarracks
attLumberMill
attBlacksmith
attScoutTower
attGuardTower
attCannonTower
attMax
Definition at line 25 of file PixelType.h.
                     {
             attNone = 0,
             attGrass,
             attDirt,
             attRock,
             attTree,
             attStump,
             attWater,
             attWall,
             attWallDamaged,
             attRubble,
             attPeasant,
             attFootman,
             attArcher,
             attRanger,
             attGoldMine,
             attTownHall,
             attKeep,
             attCastle,
             attFarm,
             attBarracks,
             attLumberMill,
             attBlacksmith,
             attScoutTower,
             attGuardTower,
             attCannonTower,
             attMax
         } EAssetTerrainType, *EAssetTerrainTypeRef;
Constructor & Destructor Documentation
CPixelType() [1/4]
CPixelType::CPixelType (int red, int green, int blue)
Definition at line 21 of file PixelType.cpp.
References DColor, and DType.
Referenced by GetPixelType().
{
     DColor = (EPlayerColor)red;
     DType = (EAssetTerrainType)green;
 }
CPixelType() [2/4]
CPixelType::CPixelType (CTerrainMap::ETileType type)
Definition at line 26 of file PixelType.cpp.
References attDirt, attGrass, attNone, attRock, attRubble, attStump, attTree, attWall, attWallDamaged, attWater, DColor, DType, pcNone, CTerrainMap::ttDirt, CTerrainMap::ttGrass, CTerrainMap::ttRock, CTerrainMap::ttRubble, CTerrainMap::ttStump, CTerrainMap::ttTree, CTerrainMap::ttWall, CTerrainMap::ttWallDamaged, and CTerrainMap::ttWater.
{
     DColor = pcNone;
     switch(type){
         case CTerrainMap::ttGrass:          DType = attGrass;
                                             break;
         case CTerrainMap::ttDirt:           DType = attDirt;
                                             break;
         case CTerrainMap::ttRock:           DType = attRock;
                                             break;
         case CTerrainMap::ttTree:           DType = attTree;
                                             break;
         case CTerrainMap::ttStump:          DType = attStump;
                                             break;
         case CTerrainMap::ttWater:          DType = attWater;
                                             break;
         case CTerrainMap::ttWall:           DType = attWall;
                                             break;
         case CTerrainMap::ttWallDamaged:    DType = attWallDamaged;
                                             break;
         case CTerrainMap::ttRubble:         DType = attRubble;
                                             break;
         default:                            DType = attNone;
                                             break;
     }
 }
CPixelType() [3/4]
CPixelType::CPixelType (const CPlayerAsset & asset)
Definition at line 52 of file PixelType.cpp.
References atArcher, atBarracks, atBlacksmith, atCannonTower, atCastle, atFarm, atFootman, atGoldMine, atGuardTower, atKeep, atLumberMill, atPeasant, atRanger, atScoutTower, attArcher, attBarracks, attBlacksmith, attCannonTower, attCastle, attFarm, attFootman, attGoldMine, attGuardTower, attKeep, attLumberMill, attNone, atTownHall, attPeasant, attRanger, attScoutTower, attTownHall, CPlayerAsset::Color(), DColor, DType, and CPlayerAsset::Type().
{
     switch(asset.Type()){
         case atPeasant:         DType = attPeasant;
                                 break;
         case atFootman:         DType = attFootman;
                                 break;
         case atArcher:          DType = attArcher;
                                 break;
         case atRanger:          DType = attRanger;
                                 break;
         case atGoldMine:        DType = attGoldMine;
                                 break;
         case atTownHall:        DType = attTownHall;
                                 break;
         case atKeep:            DType = attKeep;
                                 break;
         case atCastle:          DType = attCastle;
                                 break;
         case atFarm:            DType = attFarm;
                                 break;
         case atBarracks:        DType = attBarracks;
                                 break;
         case atLumberMill:      DType = attLumberMill;
                                 break;
         case atBlacksmith:      DType = attBlacksmith;
                                 break;
         case atScoutTower:      DType = attScoutTower;
                                 break;
         case atGuardTower:      DType = attGuardTower;
                                 break;
         case atCannonTower:     DType = attCannonTower;
                                 break;
         default:                DType = attNone;
                                 break;
     }
     DColor = asset.Color();
 }
CPixelType() [4/4]
CPixelType::CPixelType (const CPixelType & pixeltype)
Definition at line 90 of file PixelType.cpp.
References DColor, and DType.
{
     DType = pixeltype.DType;
     DColor = pixeltype.DColor;
 }
Member Function Documentation
AssetType()
EAssetType CPixelType::AssetType () const
Definition at line 112 of file PixelType.cpp.
References atArcher, atBarracks, atBlacksmith, atCannonTower, atCastle, atFarm, atFootman, atGoldMine, atGuardTower, atKeep, atLumberMill, atNone, atPeasant, atRanger, atScoutTower, attArcher, attBarracks, attBlacksmith, attCannonTower, attCastle, attFarm, attFootman, attGoldMine, attGuardTower, attKeep, attLumberMill, atTownHall, attPeasant, attRanger, attScoutTower, attTownHall, and DType.
Referenced by Color(), CApplicationData::ProcessInputGameMode(), and CApplicationData::RenderGameMode().
{
     switch(DType){
         case attPeasant:        return atPeasant;
         case attFootman:        return atFootman;
         case attArcher:         return atArcher;
         case attRanger:         return atRanger;
         case attGoldMine:       return atGoldMine;
         case attTownHall:       return atTownHall;
         case attKeep:           return atKeep;
         case attCastle:         return atCastle;
         case attFarm:           return atFarm;
         case attBarracks:       return atBarracks;
         case attLumberMill:     return atLumberMill;
         case attBlacksmith:     return atBlacksmith;
         case attScoutTower:     return atScoutTower;
         case attGuardTower:     return atGuardTower;
         case attCannonTower:    return atCannonTower;
         default:                return atNone;
     }
 }
Color()
EPlayerColor CPixelType::Color () const inline
Definition at line 71 of file PixelType.h.
References AssetType(), DColor, GetPixelType(), and ToPixelColor().
Referenced by CApplicationData::ProcessInputGameMode(), and CApplicationData::RenderGameMode().
{
             return DColor;
         };
GetPixelType() [1/2]
CPixelType CPixelType::GetPixelType (GdkDrawable * drawable, const CPosition & pos) static
Definition at line 133 of file PixelType.cpp.
References CPosition::X(), and CPosition::Y().
Referenced by Color(), CApplicationData::ProcessInputGameMode(), and CApplicationData::RenderGameMode().
{
     return GetPixelType(drawable, pos.X(), pos.Y());
 }
GetPixelType() [2/2]
CPixelType CPixelType::GetPixelType (GdkDrawable * drawable, gint xpos, gint ypos) static
Definition at line 137 of file PixelType.cpp.
References CPixelType(), and DPixbufTranslater.
{
     guchar *Pixel;
     DPixbufTranslater = gdk_pixbuf_get_from_drawable(DPixbufTranslater, drawable, nullptr, xpos, ypos, 0, 0, 1, 1);
     Pixel = gdk_pixbuf_get_pixels(DPixbufTranslater);
     return CPixelType(Pixel[0], Pixel[1], Pixel[2]);
 }
operator=()
CPixelType & CPixelType::operator= (const CPixelType & pixeltype)
Definition at line 95 of file PixelType.cpp.
References DColor, and DType.
{
     if(this != &pixeltype){
         DType = pixeltype.DType;
         DColor = pixeltype.DColor;
     }
     return *this;
 }
ToPixelColor()
guint32 CPixelType::ToPixelColor () const
Definition at line 104 of file PixelType.cpp.
References DColor, and DType.
Referenced by Color(), CAssetRenderer::DrawAssets(), and CMapRenderer::DrawMap().
{
     guint32 RetVal = DColor;
     RetVal <<= 16;
     RetVal |= ((guint32)DType)<<8;
     return RetVal;
 }
Type()
EAssetTerrainType CPixelType::Type () const inline
Definition at line 67 of file PixelType.h.
References DType.
Referenced by CApplicationData::ProcessInputGameMode().
{
             return DType;
         };
Member Data Documentation
DColor
EPlayerColor CPixelType::DColor protected
Definition at line 55 of file PixelType.h.
Referenced by Color(), CPixelType(), operator=(), and ToPixelColor().
DPixbufTranslater
GdkPixbuf * CPixelType::DPixbufTranslater = nullptr static protected
Definition at line 56 of file PixelType.h.
Referenced by GetPixelType().
DType
EAssetTerrainType CPixelType::DType protected
Definition at line 54 of file PixelType.h.
Referenced by AssetType(), CPixelType(), operator=(), ToPixelColor(), and Type().
The documentation for this class was generated from the following files:
include/PixelType.h
src/PixelType.cpp