ECS 160 Project: CPlayerCapabilityBuildRanger Class Reference
CPlayerCapabilityBuildRanger Class Reference
Classes
class CActivatedCapability
class CRegistrant
Public Member Functions
virtual ~CPlayerCapabilityBuildRanger ()
bool CanInitiate (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata)
bool CanApply (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
bool ApplyCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
Public Member Functions inherited from CPlayerCapability
virtual ~CPlayerCapability ()
std::string Name () const
EAssetCapabilityType AssetCapabilityType () const
ETargetType TargetType () const
Protected Member Functions
CPlayerCapabilityBuildRanger (const std::string &unitname)
Protected Member Functions inherited from CPlayerCapability
CPlayerCapability (const std::string &name, ETargetType targettype)
Protected Attributes
std::string DUnitName
Protected Attributes inherited from CPlayerCapability
std::string DName
EAssetCapabilityType DAssetCapabilityType
ETargetType DTargetType
Static Protected Attributes
static CRegistrant DRegistrant
Additional Inherited Members
Public Types inherited from CPlayerCapability
enum ETargetType {
ttNone = 0, ttAsset, ttTerrain, ttTerrainOrAsset,
ttPlayer
}
typedef enum CPlayerCapability::ETargetType * ETargetTypeRef
Static Public Member Functions inherited from CPlayerCapability
static std::shared_ptr< CPlayerCapability > FindCapability (EAssetCapabilityType type)
static std::shared_ptr< CPlayerCapability > FindCapability (const std::string &name)
static EAssetCapabilityType NameToType (const std::string &name)
static std::string TypeToName (EAssetCapabilityType type)
Static Protected Member Functions inherited from CPlayerCapability
static std::unordered_map< std::string, std::shared_ptr< CPlayerCapability > > & NameRegistry ()
static std::unordered_map< int, std::shared_ptr< CPlayerCapability > > & TypeRegistry ()
static bool Register (std::shared_ptr< CPlayerCapability > capability)
Detailed Description
Definition at line 161 of file UnitUpgradeCapabilities.cpp.
Constructor & Destructor Documentation
CPlayerCapabilityBuildRanger()
CPlayerCapabilityBuildRanger::CPlayerCapabilityBuildRanger (const std::string & unitname) protected
Definition at line 203 of file UnitUpgradeCapabilities.cpp.
References DUnitName.
                                                                                     : CPlayerCapability(std::string("Build") + unitname, ttNone){
     DUnitName = unitname;
 }
~CPlayerCapabilityBuildRanger()
virtual CPlayerCapabilityBuildRanger::~CPlayerCapabilityBuildRanger () inline virtual
Definition at line 190 of file UnitUpgradeCapabilities.cpp.
References CPlayerCapabilityUnitUpgrade::ApplyCapability(), CPlayerCapabilityUnitUpgrade::CanApply(), CPlayerCapabilityUnitUpgrade::CanInitiate(), and DRegistrant.
 {};
Member Function Documentation
ApplyCapability()
bool CPlayerCapabilityBuildRanger::ApplyCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target) virtual
Implements CPlayerCapability.
Definition at line 249 of file UnitUpgradeCapabilities.cpp.
References aaCapability, CPlayerCapability::AssetCapabilityType(), atBarracks, atLumberMill, SAssetCommand::DAction, SAssetCommand::DActivatedCapability, SAssetCommand::DAssetTarget, SAssetCommand::DCapability, DUnitName, CPlayerUpgrade::FindUpgradeFromName(), CPosition::SetToTile(), and CPlayerAsset::UpdateFrequency().
{
     if(atLumberMill == actor->Type()){
         auto Upgrade = CPlayerUpgrade::FindUpgradeFromName(std::string("Build") + DUnitName);
         if(Upgrade){
             SAssetCommand NewCommand;
             actor->ClearCommand();
             NewCommand.DAction = aaCapability;
             NewCommand.DCapability = AssetCapabilityType();
             NewCommand.DAssetTarget = target;
             NewCommand.DActivatedCapability = std::make_shared< CActivatedCapability >(actor, playerdata, target, actor->AssetType(), DUnitName, Upgrade->LumberCost(), Upgrade->GoldCost(), CPlayerAsset::UpdateFrequency() * Upgrade->ResearchTime());
             actor->PushCommand(NewCommand);
             return true;
         }
     }
     else if(atBarracks == actor->Type()){
         auto AssetIterator = playerdata->AssetTypes()->find(DUnitName);
         if(AssetIterator != playerdata->AssetTypes()->end()){
             auto AssetType = AssetIterator->second;
             auto NewAsset = playerdata->CreateAsset(DUnitName);
             SAssetCommand NewCommand;
             CPosition TilePosition;
             TilePosition.SetToTile(actor->Position());
             NewAsset->TilePosition(TilePosition);
             NewAsset->HitPoints(1);
             NewCommand.DAction = aaCapability;
             NewCommand.DCapability = AssetCapabilityType();
             NewCommand.DAssetTarget = NewAsset;
             NewCommand.DActivatedCapability = std::make_shared< CActivatedCapability >(actor, playerdata, NewAsset, actor->AssetType(), DUnitName, AssetType->LumberCost(), AssetType->GoldCost(), CPlayerAsset::UpdateFrequency() * AssetType->BuildTime());
             actor->PushCommand(NewCommand);
         }
     }
     return false;
 }
CanApply()
bool CPlayerCapabilityBuildRanger::CanApply (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target) virtual
Implements CPlayerCapability.
Definition at line 245 of file UnitUpgradeCapabilities.cpp.
References CanInitiate().
{
     return CanInitiate(actor, playerdata);
 }
CanInitiate()
bool CPlayerCapabilityBuildRanger::CanInitiate (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata) virtual
Implements CPlayerCapability.
Definition at line 207 of file UnitUpgradeCapabilities.cpp.
References atBarracks, atLumberMill, DUnitName, and CPlayerUpgrade::FindUpgradeFromName().
Referenced by CanApply().
{
     if(atLumberMill == actor->Type()){
         auto Upgrade = CPlayerUpgrade::FindUpgradeFromName(std::string("Build") + DUnitName);
         if(Upgrade){
             if(Upgrade->LumberCost() > playerdata->Lumber()){
                 return false;
             }
             if(Upgrade->GoldCost() > playerdata->Gold()){
                 return false;
             }
             if(!playerdata->AssetRequirementsMet(DUnitName)){
                 return false;
             }
         }
     }
     else if(atBarracks == actor->Type()){
         auto AssetIterator = playerdata->AssetTypes()->find(DUnitName);
         if(AssetIterator != playerdata->AssetTypes()->end()){
             auto AssetType = AssetIterator->second;
             if(AssetType->LumberCost() > playerdata->Lumber()){
                 return false;
             }
             if(AssetType->GoldCost() > playerdata->Gold()){
                 return false;
             }
             if((AssetType->FoodConsumption() + playerdata->FoodConsumption()) > playerdata->FoodProduction()){
                 return false;
             }
         }
     }
     return true;
 }
Member Data Documentation
DRegistrant
CPlayerCapabilityBuildRanger::CRegistrant CPlayerCapabilityBuildRanger::DRegistrant static protected
Definition at line 167 of file UnitUpgradeCapabilities.cpp.
Referenced by ~CPlayerCapabilityBuildRanger().
DUnitName
std::string CPlayerCapabilityBuildRanger::DUnitName protected
Definition at line 186 of file UnitUpgradeCapabilities.cpp.
Referenced by ApplyCapability(), CanInitiate(), and CPlayerCapabilityBuildRanger().
The documentation for this class was generated from the following file:
src/UnitUpgradeCapabilities.cpp