ECS 160 Project: CPlayerCapabilityBuildNormal Class Reference
CPlayerCapabilityBuildNormal Class Reference
Classes
class CActivatedCapability
class CRegistrant
Public Member Functions
virtual ~CPlayerCapabilityBuildNormal ()
bool CanInitiate (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata)
bool CanApply (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
bool ApplyCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
Public Member Functions inherited from CPlayerCapability
virtual ~CPlayerCapability ()
std::string Name () const
EAssetCapabilityType AssetCapabilityType () const
ETargetType TargetType () const
Protected Member Functions
CPlayerCapabilityBuildNormal (const std::string &buildingname)
Protected Member Functions inherited from CPlayerCapability
CPlayerCapability (const std::string &name, ETargetType targettype)
Protected Attributes
std::string DBuildingName
Protected Attributes inherited from CPlayerCapability
std::string DName
EAssetCapabilityType DAssetCapabilityType
ETargetType DTargetType
Static Protected Attributes
static CRegistrant DRegistrant
Additional Inherited Members
Public Types inherited from CPlayerCapability
enum ETargetType {
ttNone = 0, ttAsset, ttTerrain, ttTerrainOrAsset,
ttPlayer
}
typedef enum CPlayerCapability::ETargetType * ETargetTypeRef
Static Public Member Functions inherited from CPlayerCapability
static std::shared_ptr< CPlayerCapability > FindCapability (EAssetCapabilityType type)
static std::shared_ptr< CPlayerCapability > FindCapability (const std::string &name)
static EAssetCapabilityType NameToType (const std::string &name)
static std::string TypeToName (EAssetCapabilityType type)
Static Protected Member Functions inherited from CPlayerCapability
static std::unordered_map< std::string, std::shared_ptr< CPlayerCapability > > & NameRegistry ()
static std::unordered_map< int, std::shared_ptr< CPlayerCapability > > & TypeRegistry ()
static bool Register (std::shared_ptr< CPlayerCapability > capability)
Detailed Description
Definition at line 21 of file BuildCapabilities.cpp.
Constructor & Destructor Documentation
CPlayerCapabilityBuildNormal()
CPlayerCapabilityBuildNormal::CPlayerCapabilityBuildNormal (const std::string & buildingname) protected
Definition at line 66 of file BuildCapabilities.cpp.
References DBuildingName.
Referenced by CPlayerCapabilityBuildNormal::CRegistrant::CRegistrant().
                                                                                         : CPlayerCapability(std::string("Build") + buildingname, ttTerrainOrAsset){
     DBuildingName = buildingname;
 }
~CPlayerCapabilityBuildNormal()
virtual CPlayerCapabilityBuildNormal::~CPlayerCapabilityBuildNormal () inline virtual
Definition at line 48 of file BuildCapabilities.cpp.
References ApplyCapability(), CanApply(), CanInitiate(), and DRegistrant.
 {};
Member Function Documentation
ApplyCapability()
bool CPlayerCapabilityBuildNormal::ApplyCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target) virtual
Implements CPlayerCapability.
Definition at line 109 of file BuildCapabilities.cpp.
References aaCapability, aaWalk, CPlayerCapability::AssetCapabilityType(), SAssetCommand::DAction, SAssetCommand::DActivatedCapability, SAssetCommand::DAssetTarget, DBuildingName, SAssetCommand::DCapability, CPosition::SetToTile(), and CPlayerAsset::UpdateFrequency().
Referenced by ~CPlayerCapabilityBuildNormal().
{
     auto Iterator = playerdata->AssetTypes()->find(DBuildingName);
     if(Iterator != playerdata->AssetTypes()->end()){
         SAssetCommand NewCommand;
         actor->ClearCommand();
         if(actor->TilePosition() == target->TilePosition()){
             auto AssetType = Iterator->second;
             auto NewAsset = playerdata->CreateAsset(DBuildingName);
             CPosition TilePosition;
             TilePosition.SetToTile(target->Position());
             NewAsset->TilePosition(TilePosition);
             NewAsset->HitPoints(1);
             NewCommand.DAction = aaCapability;
             NewCommand.DCapability = AssetCapabilityType();
             NewCommand.DAssetTarget = NewAsset;
             NewCommand.DActivatedCapability = std::make_shared< CActivatedCapability >(actor, playerdata, NewAsset, AssetType->LumberCost(), AssetType->GoldCost(), CPlayerAsset::UpdateFrequency() * AssetType->BuildTime());
             actor->PushCommand(NewCommand);
         }
         else{
             NewCommand.DAction = aaCapability;
             NewCommand.DCapability = AssetCapabilityType();
             NewCommand.DAssetTarget = target;
             actor->PushCommand(NewCommand);
             NewCommand.DAction = aaWalk;
             actor->PushCommand(NewCommand);
         }
         return true;
     }
     return false;
 }
CanApply()
bool CPlayerCapabilityBuildNormal::CanApply (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target) virtual
Implements CPlayerCapability.
Definition at line 86 of file BuildCapabilities.cpp.
References atNone, and DBuildingName.
Referenced by ~CPlayerCapabilityBuildNormal().
{
     auto Iterator = playerdata->AssetTypes()->find(DBuildingName);
     if((actor != target)&&(atNone != target->Type())){
         return false;
     }
     if(Iterator != playerdata->AssetTypes()->end()){
         auto AssetType = Iterator->second;
         if(AssetType->LumberCost() > playerdata->Lumber()){
             return false;
         }
         if(AssetType->GoldCost() > playerdata->Gold()){
             return false;
         }
         if(!playerdata->PlayerMap()->CanPlaceAsset(target->TilePosition(), AssetType->Size(), actor)){
             return false;
         }
     }
     return true;
 }
CanInitiate()
bool CPlayerCapabilityBuildNormal::CanInitiate (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata) virtual
Implements CPlayerCapability.
Definition at line 70 of file BuildCapabilities.cpp.
References DBuildingName.
Referenced by ~CPlayerCapabilityBuildNormal().
{
     auto Iterator = playerdata->AssetTypes()->find(DBuildingName);
     if(Iterator != playerdata->AssetTypes()->end()){
         auto AssetType = Iterator->second;
         if(AssetType->LumberCost() > playerdata->Lumber()){
             return false;
         }
         if(AssetType->GoldCost() > playerdata->Gold()){
             return false;
         }
     }
     return true;
 }
Member Data Documentation
DBuildingName
std::string CPlayerCapabilityBuildNormal::DBuildingName protected
Definition at line 44 of file BuildCapabilities.cpp.
Referenced by ApplyCapability(), CanApply(), CanInitiate(), and CPlayerCapabilityBuildNormal().
DRegistrant
CPlayerCapabilityBuildNormal::CRegistrant CPlayerCapabilityBuildNormal::DRegistrant static protected
Definition at line 27 of file BuildCapabilities.cpp.
Referenced by ~CPlayerCapabilityBuildNormal().
The documentation for this class was generated from the following file:
src/BuildCapabilities.cpp