ECS 160 Project: CPlayerCapabilityRepair::CActivatedCapability Class Reference
CPlayerCapabilityRepair::CActivatedCapability Class Reference
Public Member Functions
CActivatedCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
virtual ~CActivatedCapability ()
int PercentComplete (int max)
bool IncrementStep ()
void Cancel ()
Public Member Functions inherited from CActivatedPlayerCapability
CActivatedPlayerCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
virtual ~CActivatedPlayerCapability ()
Additional Inherited Members
Protected Attributes inherited from CActivatedPlayerCapability
std::shared_ptr< CPlayerAsset > DActor
std::shared_ptr< CPlayerData > DPlayerData
std::shared_ptr< CPlayerAsset > DTarget
Detailed Description
Definition at line 754 of file BasicCapabilities.cpp.
Constructor & Destructor Documentation
CActivatedCapability()
CPlayerCapabilityRepair::CActivatedCapability::CActivatedCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
Definition at line 816 of file BasicCapabilities.cpp.
                                                                                                                                                                                     :
 CActivatedPlayerCapability(actor, playerdata, target){
 }
~CActivatedCapability()
virtual CPlayerCapabilityRepair::CActivatedCapability::~CActivatedCapability () inline virtual
Definition at line 759 of file BasicCapabilities.cpp.
References CPlayerCapabilityAttack::CActivatedCapability::Cancel(), CPlayerCapabilityAttack::CActivatedCapability::IncrementStep(), and CPlayerCapabilityAttack::CActivatedCapability::PercentComplete().
 {};
Member Function Documentation
Cancel()
void CPlayerCapabilityRepair::CActivatedCapability::Cancel () virtual
Implements CActivatedPlayerCapability.
Definition at line 847 of file BasicCapabilities.cpp.
References CActivatedPlayerCapability::DActor.
{
     DActor->PopCommand();
 }
IncrementStep()
bool CPlayerCapabilityRepair::CActivatedCapability::IncrementStep () virtual
Implements CActivatedPlayerCapability.
Definition at line 826 of file BasicCapabilities.cpp.
References aaRepair, aaWalk, SAssetCommand::DAction, CActivatedPlayerCapability::DActor, SGameEvent::DAsset, SAssetCommand::DAssetTarget, dMax, CActivatedPlayerCapability::DPlayerData, CActivatedPlayerCapability::DTarget, SGameEvent::DType, and etAcknowledge.
{
     SAssetCommand AssetCommand;
     SGameEvent TempEvent;
     TempEvent.DType = etAcknowledge;
     TempEvent.DAsset = DActor;
     DPlayerData->AddGameEvent(TempEvent);
     AssetCommand.DAction = aaRepair;
     AssetCommand.DAssetTarget = DTarget;
     DActor->ClearCommand();
     DActor->PushCommand(AssetCommand);
     AssetCommand.DAction = aaWalk;
     if(!DActor->TileAligned()){
         DActor->Direction((EDirection)((DActor->Position().TileOctant() + dMax/2) % dMax));
     }
     DActor->PushCommand(AssetCommand);
     return true;
 }
PercentComplete()
int CPlayerCapabilityRepair::CActivatedCapability::PercentComplete (int max) virtual
Implements CActivatedPlayerCapability.
Definition at line 822 of file BasicCapabilities.cpp.
{
     return 0;
 }
The documentation for this class was generated from the following file:
src/BasicCapabilities.cpp