ECS 160 Project: CPlayerCapabilityMineHarvest Class Reference
CPlayerCapabilityMineHarvest Class Reference
Classes
class CActivatedCapability
class CRegistrant
Public Member Functions
virtual ~CPlayerCapabilityMineHarvest ()
bool CanInitiate (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata)
bool CanApply (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
bool ApplyCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
Public Member Functions inherited from CPlayerCapability
virtual ~CPlayerCapability ()
std::string Name () const
EAssetCapabilityType AssetCapabilityType () const
ETargetType TargetType () const
Protected Member Functions
CPlayerCapabilityMineHarvest ()
Protected Member Functions inherited from CPlayerCapability
CPlayerCapability (const std::string &name, ETargetType targettype)
Static Protected Attributes
static CRegistrant DRegistrant
Additional Inherited Members
Public Types inherited from CPlayerCapability
enum ETargetType {
ttNone = 0, ttAsset, ttTerrain, ttTerrainOrAsset,
ttPlayer
}
typedef enum CPlayerCapability::ETargetType * ETargetTypeRef
Static Public Member Functions inherited from CPlayerCapability
static std::shared_ptr< CPlayerCapability > FindCapability (EAssetCapabilityType type)
static std::shared_ptr< CPlayerCapability > FindCapability (const std::string &name)
static EAssetCapabilityType NameToType (const std::string &name)
static std::string TypeToName (EAssetCapabilityType type)
Static Protected Member Functions inherited from CPlayerCapability
static std::unordered_map< std::string, std::shared_ptr< CPlayerCapability > > & NameRegistry ()
static std::unordered_map< int, std::shared_ptr< CPlayerCapability > > & TypeRegistry ()
static bool Register (std::shared_ptr< CPlayerCapability > capability)
Protected Attributes inherited from CPlayerCapability
std::string DName
EAssetCapabilityType DAssetCapabilityType
ETargetType DTargetType
Detailed Description
Definition at line 117 of file BasicCapabilities.cpp.
Constructor & Destructor Documentation
CPlayerCapabilityMineHarvest()
CPlayerCapabilityMineHarvest::CPlayerCapabilityMineHarvest () protected
Definition at line 152 of file BasicCapabilities.cpp.
                                                            : CPlayerCapability(std::string("Mine"), ttTerrainOrAsset){
 }
~CPlayerCapabilityMineHarvest()
virtual CPlayerCapabilityMineHarvest::~CPlayerCapabilityMineHarvest () inline virtual
Definition at line 139 of file BasicCapabilities.cpp.
References CPlayerCapabilityMove::ApplyCapability(), CPlayerCapabilityMove::CanApply(), CPlayerCapabilityMove::CanInitiate(), and DRegistrant.
 {};
Member Function Documentation
ApplyCapability()
bool CPlayerCapabilityMineHarvest::ApplyCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target) virtual
Implements CPlayerCapability.
Definition at line 177 of file BasicCapabilities.cpp.
References aaCapability, CPlayerCapability::AssetCapabilityType(), SAssetCommand::DAction, SAssetCommand::DActivatedCapability, SAssetCommand::DAssetTarget, and SAssetCommand::DCapability.
Referenced by CPlayerCapabilityStandGround::~CPlayerCapabilityStandGround().
{
     SAssetCommand NewCommand;
     NewCommand.DAction = aaCapability;
     NewCommand.DCapability = AssetCapabilityType();
     NewCommand.DAssetTarget = target;
     NewCommand.DActivatedCapability = std::make_shared< CActivatedCapability >(actor, playerdata, target);
     actor->ClearCommand();
     actor->PushCommand(NewCommand);
     return true;
 }
CanApply()
bool CPlayerCapabilityMineHarvest::CanApply (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target) virtual
Implements CPlayerCapability.
Definition at line 160 of file BasicCapabilities.cpp.
References actMine, atGoldMine, atNone, and CTerrainMap::ttTree.
Referenced by CPlayerCapabilityStandGround::~CPlayerCapabilityStandGround().
{
     if(!actor->HasCapability(actMine)){
         return false;
     }
     if(actor->Lumber()||actor->Gold()){
         return false;
     }
     if(atGoldMine == target->Type()){
         return true;
     }
     if(atNone != target->Type()){
         return false;
     }
     return CTerrainMap::ttTree == playerdata->PlayerMap()->TileType(target->TilePosition());
 }
CanInitiate()
bool CPlayerCapabilityMineHarvest::CanInitiate (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata) virtual
Implements CPlayerCapability.
Definition at line 156 of file BasicCapabilities.cpp.
References actMine.
Referenced by CPlayerCapabilityStandGround::~CPlayerCapabilityStandGround().
{
     return actor->HasCapability(actMine);
 }
Member Data Documentation
DRegistrant
CPlayerCapabilityMineHarvest::CRegistrant CPlayerCapabilityMineHarvest::DRegistrant static protected
Definition at line 123 of file BasicCapabilities.cpp.
Referenced by ~CPlayerCapabilityMineHarvest().
The documentation for this class was generated from the following file:
src/BasicCapabilities.cpp