ECS 160 Project: CPlayerData Class Reference
CPlayerData Class Reference
#include <GameModel.h>
Public Member Functions
CPlayerData (std::shared_ptr< CAssetDecoratedMap > map, EPlayerColor color)
int GameCycle () const
void IncrementCycle ()
EPlayerColor Color () const
bool IsAI () const
bool IsAI (bool isai)
bool IsAlive () const
int Gold () const
int Lumber () const
int IncrementGold (int gold)
int DecrementGold (int gold)
int IncrementLumber (int lumber)
int DecrementLumber (int lumber)
int FoodConsumption () const
int FoodProduction () const
std::shared_ptr< CVisibilityMap > VisibilityMap () const
std::shared_ptr< CAssetDecoratedMap > PlayerMap () const
std::list< std::weak_ptr< CPlayerAsset > > Assets () const
std::shared_ptr< std::unordered_map< std::string, std::shared_ptr< CPlayerAssetType > > > & AssetTypes ()
std::shared_ptr< CPlayerAsset > CreateMarker (const CPosition &pos, bool addtomap)
std::shared_ptr< CPlayerAsset > CreateAsset (const std::string &assettypename)
void DeleteAsset (std::shared_ptr< CPlayerAsset > asset)
bool AssetRequirementsMet (const std::string &assettypename)
void UpdateVisibility ()
std::list< std::weak_ptr< CPlayerAsset > > SelectAssets (const SRectangle &selectarea, EAssetType assettype, bool selectidentical=false)
std::weak_ptr< CPlayerAsset > SelectAsset (const CPosition &pos, EAssetType assettype)
std::weak_ptr< CPlayerAsset > FindNearestOwnedAsset (const CPosition &pos, const std::vector< EAssetType > assettypes)
std::shared_ptr< CPlayerAsset > FindNearestAsset (const CPosition &pos, EAssetType assettype)
std::weak_ptr< CPlayerAsset > FindNearestEnemy (const CPosition &pos, int range)
CPosition FindBestAssetPlacement (const CPosition &pos, std::shared_ptr< CPlayerAsset > builder, EAssetType assettype, int buffer)
std::list< std::weak_ptr< CPlayerAsset > > IdleAssets () const
int PlayerAssetCount (EAssetType type)
int FoundAssetCount (EAssetType type)
void AddUpgrade (const std::string &upgradename)
bool HasUpgrade (EAssetCapabilityType upgrade) const
const std::vector< SGameEvent > & GameEvents () const
void ClearGameEvents ()
void AddGameEvent (const SGameEvent &event)
void AppendGameEvents (const std::vector< SGameEvent > &events)
Protected Attributes
bool DIsAI
EPlayerColor DColor
std::shared_ptr< CVisibilityMap > DVisibilityMap
std::shared_ptr< CAssetDecoratedMap > DActualMap
std::shared_ptr< CAssetDecoratedMap > DPlayerMap
std::shared_ptr< std::unordered_map< std::string, std::shared_ptr< CPlayerAssetType > > > DAssetTypes
std::list< std::weak_ptr< CPlayerAsset > > DAssets
std::vector< bool > DUpgrades
std::vector< SGameEvent > DGameEvents
int DGold
int DLumber
int DGameCycle
Detailed Description
Definition at line 48 of file GameModel.h.
Constructor & Destructor Documentation
CPlayerData()
CPlayerData::CPlayerData (std::shared_ptr< CAssetDecoratedMap > map, EPlayerColor color)
Definition at line 34 of file GameModel.cpp.
References actMax, atGoldMine, CreateAsset(), DActualMap, DAssetTypes, DColor, DEBUG_LOW, DGameCycle, DGold, DIsAI, DLumber, DPlayerMap, DUpgrades, CPlayerAssetType::DuplicateRegistry(), DVisibilityMap, CPlayerAssetType::NameToType(), and PrintDebug.
{
     DIsAI = true;
     DGameCycle = 0;
     DColor = color;
     DActualMap = map;
     DAssetTypes = CPlayerAssetType::DuplicateRegistry(color);
     DPlayerMap = DActualMap->CreateInitializeMap();
     DVisibilityMap = DActualMap->CreateVisibilityMap();
     DGold = 0;
     DLumber = 0;
     DUpgrades.resize(actMax);
     for(int Index = 0; Index < DUpgrades.size(); Index++){
         DUpgrades[Index] = false;
     }
     for(auto &ResourceInit : DActualMap->ResourceInitializationList()){
         if(ResourceInit.DColor == color){
             DGold = ResourceInit.DGold;
             DLumber = ResourceInit.DLumber;
         }
     }
     for(auto &AssetInit : DActualMap->AssetInitializationList()){
         if(AssetInit.DColor == color){
             PrintDebug(DEBUG_LOW, "Init %s %d (%d, %d)\n", AssetInit.DType.c_str(), AssetInit.DColor, AssetInit.DTilePosition.X(), AssetInit.DTilePosition.Y());
             std::shared_ptr< CPlayerAsset > InitAsset = CreateAsset(AssetInit.DType);
             InitAsset->TilePosition(AssetInit.DTilePosition);
             if(atGoldMine == CPlayerAssetType::NameToType(AssetInit.DType)){
                 InitAsset->Gold(DGold);
             }
         }
     }
 }
Member Function Documentation
AddGameEvent()
void CPlayerData::AddGameEvent (const SGameEvent & event) inline
Definition at line 154 of file GameModel.h.
{
             DGameEvents.push_back(event);
         };
AddUpgrade()
void CPlayerData::AddUpgrade (const std::string & upgradename)
Definition at line 439 of file GameModel.cpp.
References DAssetTypes, DUpgrades, CPlayerUpgrade::FindUpgradeFromName(), CPlayerCapability::NameToType(), and CPlayerAssetType::TypeToName().
Referenced by AssetTypes().
{
     auto Upgrade = CPlayerUpgrade::FindUpgradeFromName(upgradename);
     if(Upgrade){
         for(auto AssetType : Upgrade->AffectedAssets()){
             std::string AssetName = CPlayerAssetType::TypeToName(AssetType);
             auto AssetIterator = DAssetTypes->find(AssetName);
             if(AssetIterator != DAssetTypes->end()){
                 AssetIterator->second->AddUpgrade(Upgrade);
             }
         }
         DUpgrades[CPlayerCapability::NameToType(upgradename)] = true;
     }
 }
AppendGameEvents()
void CPlayerData::AppendGameEvents (const std::vector< SGameEvent > & events) inline
Definition at line 157 of file GameModel.h.
{
             DGameEvents.insert(DGameEvents.end(), events.begin(), events.end());
         };
AssetRequirementsMet()
bool CPlayerData::AssetRequirementsMet (const std::string & assettypename)
Definition at line 129 of file GameModel.cpp.
References aaConstruct, atCastle, atKeep, atMax, atTownHall, DAssets, and DAssetTypes.
Referenced by AssetTypes().
{
     std::vector< int > AssetCount;
     AssetCount.resize(atMax);
     for(auto WeakAsset : DAssets){
         if(auto Asset = WeakAsset.lock()){
             if(aaConstruct != Asset->Action()){
                 AssetCount[Asset->Type()]++;
             }
         }
     }
     for(auto Requirement : (*DAssetTypes)[assettypename]->AssetRequirements()){
         if(0 == AssetCount[Requirement]){
             if((atKeep == Requirement)&&(AssetCount[atCastle])){
                 continue;
             }
             if((atTownHall == Requirement)&&(AssetCount[atKeep]||AssetCount[atCastle])){
                 continue;
             }
             return false;
         }
     }
     return true;
 }
Assets()
std::list< std::weak_ptr< CPlayerAsset > > CPlayerData::Assets () const inline
Definition at line 120 of file GameModel.h.
References DAssets.
{
             return DAssets;
         };
AssetTypes()
std::shared_ptr< std::unordered_map< std::string, std::shared_ptr< CPlayerAssetType > > >& CPlayerData::AssetTypes () inline
Definition at line 123 of file GameModel.h.
References AddUpgrade(), AssetRequirementsMet(), CreateAsset(), CreateMarker(), DAssetTypes, DeleteAsset(), FindBestAssetPlacement(), FindNearestAsset(), FindNearestEnemy(), FindNearestOwnedAsset(), FoundAssetCount(), IdleAssets(), PlayerAssetCount(), SelectAsset(), SelectAssets(), and UpdateVisibility().
{
             return DAssetTypes;
         };
ClearGameEvents()
void CPlayerData::ClearGameEvents () inline
Definition at line 151 of file GameModel.h.
Referenced by CGameModel::Map().
{
             DGameEvents.clear();
         };
Color()
EPlayerColor CPlayerData::Color () const inline
Definition at line 74 of file GameModel.h.
References DColor.
{
             return DColor;
         };
CreateAsset()
std::shared_ptr< CPlayerAsset > CPlayerData::CreateAsset (const std::string & assettypename)
Definition at line 108 of file GameModel.cpp.
References DActualMap, DAssets, and DGameCycle.
Referenced by AssetTypes(), and CPlayerData().
{
     std::shared_ptr< CPlayerAsset > CreatedAsset = (*DAssetTypes)[assettypename]->Construct();
     CreatedAsset->CreationCycle(DGameCycle);
     DAssets.push_back(CreatedAsset);
     DActualMap->AddAsset(CreatedAsset);
     return CreatedAsset;
 }
CreateMarker()
std::shared_ptr< CPlayerAsset > CPlayerData::CreateMarker (const CPosition & pos, bool addtomap)
Definition at line 95 of file GameModel.cpp.
References DPlayerMap, and CPosition::SetToTile().
Referenced by AssetTypes().
{
     std::shared_ptr< CPlayerAsset > NewMarker = (*DAssetTypes)["None"]->Construct();
     CPosition TilePosition;
     TilePosition.SetToTile(pos);
     NewMarker->TilePosition(TilePosition);
     if(addtomap){
         DPlayerMap->AddAsset(NewMarker);
     }
     return NewMarker;
 }
DecrementGold()
int CPlayerData::DecrementGold (int gold) inline
Definition at line 99 of file GameModel.h.
References DGold.
{
             DGold -= gold;
             return DGold;
         };
DecrementLumber()
int CPlayerData::DecrementLumber (int lumber) inline
Definition at line 107 of file GameModel.h.
References DLumber, FoodConsumption(), and FoodProduction().
{
             DLumber -= lumber;
             return DLumber;
         };
DeleteAsset()
void CPlayerData::DeleteAsset (std::shared_ptr< CPlayerAsset > asset)
Definition at line 117 of file GameModel.cpp.
References DActualMap, and DAssets.
Referenced by AssetTypes().
{
     auto Iterator = DAssets.begin();
     while(Iterator != DAssets.end()){
         if(Iterator->lock() == asset){
             DAssets.erase(Iterator);
             break;
         }
         Iterator++;
     }
     DActualMap->RemoveAsset(asset);
 }
FindBestAssetPlacement()
CPosition CPlayerData::FindBestAssetPlacement (const CPosition & pos, std::shared_ptr< CPlayerAsset > builder, EAssetType assettype, int buffer)
Definition at line 312 of file GameModel.cpp.
References DPlayerMap, MAX, CPlayerAssetType::TypeToName(), CPosition::X(), and CPosition::Y().
Referenced by AssetTypes().
{
     auto AssetType = (*DAssetTypes)[CPlayerAssetType::TypeToName(assettype)];
     int PlacementSize = AssetType->Size() + 2 * buffer;
     int MaxDistance = MAX(DPlayerMap->Width(), DPlayerMap->Height());
     for(int Distance = 1; Distance < MaxDistance; Distance++){
         CPosition BestPosition;
         int BestDistance = -1;
         int LeftX = pos.X() - Distance;
         int TopY = pos.Y() - Distance;
         int RightX = pos.X() + Distance;
         int BottomY = pos.Y() + Distance;
         bool LeftValid = true;
         bool RightValid = true;
         bool TopValid = true;
         bool BottomValid = true;
         if(0 > LeftX){
             LeftValid = false;
             LeftX = 0;
         }
         if(0 > TopY){
             TopValid = false;
             TopY = 0;
         }
         if(DPlayerMap->Width() <= RightX){
             RightValid = false;
             RightX = DPlayerMap->Width() - 1;
         }
         if(DPlayerMap->Height() <= BottomY){
             BottomValid = false;
             BottomY = DPlayerMap->Height() - 1;
         }
         if(TopValid){
            for(int Index = LeftX; Index <= RightX; Index++){
                 CPosition TempPosition(Index, TopY);
                 if(DPlayerMap->CanPlaceAsset(TempPosition, PlacementSize, builder)){
                     int CurrentDistance = builder->TilePosition().DistanceSquared(TempPosition);
                     if((-1 == BestDistance)||(CurrentDistance < BestDistance)){
                         BestDistance = CurrentDistance;
                         BestPosition = TempPosition;
                     }
                 }
             }
         }
         if(RightValid){
            for(int Index = TopY; Index <= BottomY; Index++){
                 CPosition TempPosition(RightX, Index);
                 if(DPlayerMap->CanPlaceAsset(TempPosition, PlacementSize, builder)){
                     int CurrentDistance = builder->TilePosition().DistanceSquared(TempPosition);
                     if((-1 == BestDistance)||(CurrentDistance < BestDistance)){
                         BestDistance = CurrentDistance;
                         BestPosition = TempPosition;
                     }
                 }
             }
         }
         if(BottomValid){
            for(int Index = LeftX; Index <= RightX; Index++){
                 CPosition TempPosition(Index, BottomY);
                 if(DPlayerMap->CanPlaceAsset(TempPosition, PlacementSize, builder)){
                     int CurrentDistance = builder->TilePosition().DistanceSquared(TempPosition);
                     if((-1 == BestDistance)||(CurrentDistance < BestDistance)){
                         BestDistance = CurrentDistance;
                         BestPosition = TempPosition;
                     }
                 }
             }
         }
         if(LeftValid){
            for(int Index = TopY; Index <= BottomY; Index++){
                 CPosition TempPosition(LeftX, Index);
                 if(DPlayerMap->CanPlaceAsset(TempPosition, PlacementSize, builder)){
                     int CurrentDistance = builder->TilePosition().DistanceSquared(TempPosition);
                     if((-1 == BestDistance)||(CurrentDistance < BestDistance)){
                         BestDistance = CurrentDistance;
                         BestPosition = TempPosition;
                     }
                 }
             }
         }
         if(-1 != BestDistance){
             return CPosition(BestPosition.X() + buffer, BestPosition.Y() + buffer);
         }
     }
     return CPosition(-1, -1);
 }
FindNearestAsset()
std::shared_ptr< CPlayerAsset > CPlayerData::FindNearestAsset (const CPosition & pos, EAssetType assettype)
Definition at line 264 of file GameModel.cpp.
References DPlayerMap.
Referenced by AssetTypes().
{
     std::shared_ptr< CPlayerAsset > BestAsset;
     int BestDistanceSquared = -1;
     for(auto &Asset : DPlayerMap->Assets()){
         if(Asset->Type() == assettype){
             int CurrentDistance = Asset->Position().DistanceSquared(pos);
             if((-1 == BestDistanceSquared)||(CurrentDistance < BestDistanceSquared)){
                 BestDistanceSquared = CurrentDistance;
                 BestAsset = Asset;
             }
         }
     }
     return BestAsset;
 }
FindNearestEnemy()
std::weak_ptr< CPlayerAsset > CPlayerData::FindNearestEnemy (const CPosition & pos, int range)
Definition at line 281 of file GameModel.cpp.
References aaCapability, aaConstruct, aaConveyGold, aaConveyLumber, aaMineGold, DColor, DPlayerMap, pcNone, and RangeToDistanceSquared().
Referenced by AssetTypes().
{
     std::shared_ptr< CPlayerAsset > BestAsset;
     int BestDistanceSquared = -1;
     // Assume tile width == tile height
     if(0 < range){
         range = RangeToDistanceSquared(range);
     }
     for(auto Asset : DPlayerMap->Assets()){
         if((Asset->Color() != DColor)&&(Asset->Color() != pcNone)&&(Asset->Alive())){
             auto Command = Asset->CurrentCommand();
             if(aaCapability == Command.DAction){
                 if((Command.DAssetTarget)&&(aaConstruct == Command.DAssetTarget->Action())){
                     continue;
                 }
             }
             if((aaConveyGold != Command.DAction)&&(aaConveyLumber != Command.DAction)&&(aaMineGold != Command.DAction)){
                 int CurrentDistance = Asset->ClosestPosition(pos).DistanceSquared( pos );//Asset->Position().DistanceSquared(pos);
                 if((0 > range)||(CurrentDistance <= range)){
                     if((-1 == BestDistanceSquared)||(CurrentDistance < BestDistanceSquared)){
                         BestDistanceSquared = CurrentDistance;
                         BestAsset = Asset;
                     }
                 }
             }
         }
     }
     return BestAsset;
 }
FindNearestOwnedAsset()
std::weak_ptr< CPlayerAsset > CPlayerData::FindNearestOwnedAsset (const CPosition & pos, const std::vector< EAssetType > assettypes)
Definition at line 242 of file GameModel.cpp.
References aaConstruct, atCastle, atKeep, and DAssets.
Referenced by AssetTypes().
{
     std::shared_ptr< CPlayerAsset > BestAsset;
     int BestDistanceSquared = -1;
     for(auto &WeakAsset : DAssets){
         if(auto Asset = WeakAsset.lock()){
             for(auto &AssetType : assettypes){
                 if((Asset->Type() == AssetType)&&((aaConstruct != Asset->Action())||(atKeep == AssetType)||(atCastle == AssetType))){
                     int CurrentDistance = Asset->Position().DistanceSquared(pos);
                     if((-1 == BestDistanceSquared)||(CurrentDistance < BestDistanceSquared)){
                         BestDistanceSquared = CurrentDistance;
                         BestAsset = Asset;
                     }
                     break;
                 }
             }
         }
     }
     return BestAsset;
 }
FoodConsumption()
int CPlayerData::FoodConsumption () const
Definition at line 67 of file GameModel.cpp.
References DAssets.
Referenced by DecrementLumber().
{
     int TotalConsumption = 0;
     for(auto &WeakAsset : DAssets){
         if(auto Asset = WeakAsset.lock()){
             int AssetConsumption = Asset->FoodConsumption();
             if(0 < AssetConsumption){
                 TotalConsumption += AssetConsumption;
             }
         }
     }
     return TotalConsumption;
 }
FoodProduction()
int CPlayerData::FoodProduction () const
Definition at line 81 of file GameModel.cpp.
References aaConstruct, and DAssets.
Referenced by DecrementLumber().
{
     int TotalProduction = 0;
     for(auto &WeakAsset : DAssets){
         if(auto Asset = WeakAsset.lock()){
             int AssetConsumption = Asset->FoodConsumption();
             if((0 > AssetConsumption)&&((aaConstruct != Asset->Action())||(!Asset->CurrentCommand().DAssetTarget))){
                 TotalProduction += -AssetConsumption;
             }
         }
     }
     return TotalProduction;
 }
FoundAssetCount()
int CPlayerData::FoundAssetCount (EAssetType type)
Definition at line 413 of file GameModel.cpp.
References DPlayerMap.
Referenced by AssetTypes().
{
     int Count = 0;
     for(auto Asset : DPlayerMap->Assets()){
         if(type == Asset->Type()){
             Count++;
         }
     }
     return Count;
 }
GameCycle()
int CPlayerData::GameCycle () const inline
Definition at line 66 of file GameModel.h.
References DGameCycle.
{
             return DGameCycle;
         };
GameEvents()
const std::vector< SGameEvent >& CPlayerData::GameEvents () const inline
Definition at line 148 of file GameModel.h.
References DGameEvents.
{
             return DGameEvents;
         };
Gold()
int CPlayerData::Gold () const inline
Definition at line 89 of file GameModel.h.
References DGold.
Referenced by CGameModel::Timestep().
{
             return DGold;
         };
HasUpgrade()
bool CPlayerData::HasUpgrade (EAssetCapabilityType upgrade) const inline
Definition at line 141 of file GameModel.h.
{
             if((0 > upgrade)||(DUpgrades.size() <= upgrade)){
                 return false;
             }
             return DUpgrades[upgrade];
         };
IdleAssets()
std::list< std::weak_ptr< CPlayerAsset > > CPlayerData::IdleAssets () const
Definition at line 425 of file GameModel.cpp.
References aaNone, atNone, and DAssets.
Referenced by AssetTypes().
{
     std::list< std::weak_ptr< CPlayerAsset > > AssetList;
     for(auto WeakAsset : DAssets){
         if(auto Asset = WeakAsset.lock()){
             if((aaNone == Asset->Action())&&(atNone != Asset->Type())){
                 AssetList.push_back(Asset);
             }
         }
     }
     return AssetList;
 }
IncrementCycle()
void CPlayerData::IncrementCycle () inline
Definition at line 70 of file GameModel.h.
{
             DGameCycle++;
         };
IncrementGold()
int CPlayerData::IncrementGold (int gold) inline
Definition at line 95 of file GameModel.h.
References DGold.
{
             DGold += gold;
             return DGold;
         };
IncrementLumber()
int CPlayerData::IncrementLumber (int lumber) inline
Definition at line 103 of file GameModel.h.
References DLumber.
{
             DLumber += lumber;
             return DLumber;
         };
IsAI() [1/2]
bool CPlayerData::IsAI () const inline
Definition at line 78 of file GameModel.h.
References DIsAI.
{
             return DIsAI;
         };
IsAI() [2/2]
bool CPlayerData::IsAI (bool isai) inline
Definition at line 82 of file GameModel.h.
{
             return DIsAI = isai;
         };
IsAlive()
bool CPlayerData::IsAlive () const inline
Definition at line 86 of file GameModel.h.
Referenced by CGameModel::Timestep().
{
             return DAssets.size();
         };
Lumber()
int CPlayerData::Lumber () const inline
Definition at line 92 of file GameModel.h.
References DLumber.
{
             return DLumber;
         };
PlayerAssetCount()
int CPlayerData::PlayerAssetCount (EAssetType type)
Definition at line 401 of file GameModel.cpp.
References DColor, and DPlayerMap.
Referenced by AssetTypes().
{
     int Count = 0;
     for(auto Asset : DPlayerMap->Assets()){
         if((Asset->Color() == DColor)&&(type == Asset->Type())){
             Count++;
         }
     }
     return Count;
 }
PlayerMap()
std::shared_ptr< CAssetDecoratedMap > CPlayerData::PlayerMap () const inline
Definition at line 117 of file GameModel.h.
References DPlayerMap.
{
             return DPlayerMap;
         };
SelectAsset()
std::weak_ptr< CPlayerAsset > CPlayerData::SelectAsset (const CPosition & pos, EAssetType assettype)
Definition at line 221 of file GameModel.cpp.
References atNone, and DAssets.
Referenced by AssetTypes(), and SelectAssets().
{
     std::shared_ptr< CPlayerAsset > BestAsset;
     int BestDistanceSquared = -1;
     if(atNone != assettype){
         for(auto &WeakAsset : DAssets){
             if(auto Asset = WeakAsset.lock()){
                 if(Asset->Type() == assettype){
                     int CurrentDistance = Asset->Position().DistanceSquared(pos);
                     if((-1 == BestDistanceSquared)||(CurrentDistance < BestDistanceSquared)){
                         BestDistanceSquared = CurrentDistance;
                         BestAsset = Asset;
                     }
                 }
             }
         }
     }
     return BestAsset;
 }
SelectAssets()
std::list< std::weak_ptr< CPlayerAsset > > CPlayerData::SelectAssets (const SRectangle & selectarea, EAssetType assettype, bool selectidentical = false)
Definition at line 174 of file GameModel.cpp.
References DAssets, SRectangle::DHeight, SRectangle::DWidth, SRectangle::DXPosition, SRectangle::DYPosition, and SelectAsset().
Referenced by AssetTypes().
{
     std::list< std::weak_ptr< CPlayerAsset > > ReturnList;
     if((!selectarea.DWidth)||(!selectarea.DHeight)){
         std::weak_ptr< CPlayerAsset > BestAsset = SelectAsset(CPosition(selectarea.DXPosition, selectarea.DYPosition), assettype);
         if(auto LockedAsset = BestAsset.lock()){
             ReturnList.push_back(BestAsset);
             if(selectidentical && LockedAsset->Speed()){
                 for(auto &WeakAsset : DAssets){
                     if(auto Asset = WeakAsset.lock()){
                         if((LockedAsset != Asset)&&(Asset->Type() == assettype)){
                             ReturnList.push_back(Asset);
                         }
                     }
                 }
             }
         }
     }
     else{
         bool AnyMovable = false;
         for(auto &WeakAsset : DAssets){
             if(auto Asset = WeakAsset.lock()){
                 if((selectarea.DXPosition <= Asset->PositionX())&&(Asset->PositionX() < selectarea.DXPosition + selectarea.DWidth)&&(selectarea.DYPosition <= Asset->PositionY())&&(Asset->PositionY() < selectarea.DYPosition + selectarea.DHeight)){
                     if(AnyMovable){
                         if(Asset->Speed()){
                             ReturnList.push_back(Asset);
                         }
                     }
                     else{
                         if(Asset->Speed()){
                             ReturnList.clear();
                             ReturnList.push_back(Asset);
                             AnyMovable = true;
                         }
                         else{
                             if(ReturnList.empty()){
                                 ReturnList.push_back(Asset);
                             }
                         }
                     }
                 }
             }
         }
     }
     return ReturnList;
 }
UpdateVisibility()
void CPlayerData::UpdateVisibility ()
Definition at line 155 of file GameModel.cpp.
References aaNone, atNone, DActualMap, DAssets, DPlayerMap, DVisibilityMap, and CPlayerAsset::UpdateFrequency().
Referenced by AssetTypes().
{
     std::list< std::shared_ptr< CPlayerAsset > > RemoveList;
     DVisibilityMap->Update(DAssets);
     DPlayerMap->UpdateMap(*DVisibilityMap, *DActualMap);
     for(auto &Asset : DPlayerMap->Assets()){
         if((atNone == Asset->Type())&&(aaNone == Asset->Action())){
             Asset->IncrementStep();
             if(CPlayerAsset::UpdateFrequency() < Asset->Step() * 2){
                 RemoveList.push_back(Asset);
             }
         }
     }
     for(auto &Asset : RemoveList){
         DPlayerMap->RemoveAsset(Asset);
     }
 }
VisibilityMap()
std::shared_ptr< CVisibilityMap > CPlayerData::VisibilityMap () const inline
Definition at line 114 of file GameModel.h.
References DVisibilityMap.
{
             return DVisibilityMap;
         };
Member Data Documentation
DActualMap
std::shared_ptr< CAssetDecoratedMap > CPlayerData::DActualMap protected
Definition at line 53 of file GameModel.h.
Referenced by CGameModel::CGameModel(), CPlayerData(), CreateAsset(), DeleteAsset(), CGameModel::Map(), CGameModel::Timestep(), UpdateVisibility(), and CGameModel::ValidAsset().
DAssets
std::list< std::weak_ptr< CPlayerAsset > > CPlayerData::DAssets protected
Definition at line 56 of file GameModel.h.
Referenced by AssetRequirementsMet(), Assets(), CreateAsset(), DeleteAsset(), FindNearestOwnedAsset(), FoodConsumption(), FoodProduction(), IdleAssets(), SelectAsset(), SelectAssets(), and UpdateVisibility().
DAssetTypes
std::shared_ptr< std::unordered_map< std::string, std::shared_ptr< CPlayerAssetType > > > CPlayerData::DAssetTypes protected
Definition at line 55 of file GameModel.h.
Referenced by AddUpgrade(), AssetRequirementsMet(), AssetTypes(), and CPlayerData().
DColor
EPlayerColor CPlayerData::DColor protected
Definition at line 51 of file GameModel.h.
Referenced by Color(), CPlayerData(), FindNearestEnemy(), and PlayerAssetCount().
DGameCycle
int CPlayerData::DGameCycle protected
Definition at line 61 of file GameModel.h.
Referenced by CPlayerData(), CreateAsset(), GameCycle(), CGameModel::GameCycle(), and CGameModel::Timestep().
DGameEvents
std::vector< SGameEvent > CPlayerData::DGameEvents protected
Definition at line 58 of file GameModel.h.
Referenced by GameEvents().
DGold
int CPlayerData::DGold protected
Definition at line 59 of file GameModel.h.
Referenced by CPlayerData(), DecrementGold(), Gold(), and IncrementGold().
DIsAI
bool CPlayerData::DIsAI protected
Definition at line 50 of file GameModel.h.
Referenced by CPlayerData(), and IsAI().
DLumber
int CPlayerData::DLumber protected
Definition at line 60 of file GameModel.h.
Referenced by CPlayerData(), DecrementLumber(), IncrementLumber(), and Lumber().
DPlayerMap
std::shared_ptr< CAssetDecoratedMap > CPlayerData::DPlayerMap protected
Definition at line 54 of file GameModel.h.
Referenced by CPlayerData(), CreateMarker(), FindBestAssetPlacement(), FindNearestAsset(), FindNearestEnemy(), FoundAssetCount(), PlayerAssetCount(), PlayerMap(), and UpdateVisibility().
DUpgrades
std::vector< bool > CPlayerData::DUpgrades protected
Definition at line 57 of file GameModel.h.
Referenced by AddUpgrade(), and CPlayerData().
DVisibilityMap
std::shared_ptr< CVisibilityMap > CPlayerData::DVisibilityMap protected
Definition at line 52 of file GameModel.h.
Referenced by CPlayerData(), UpdateVisibility(), and VisibilityMap().
The documentation for this class was generated from the following files:
include/GameModel.h
src/GameModel.cpp