ECS 160 Project: CTerrainMap Class Reference
CTerrainMap Class Reference
#include <TerrainMap.h>
Public Types
enum ETileType {
ttNone = 0, ttGrass, ttDirt, ttRock,
ttTree, ttStump, ttWater, ttWall,
ttWallDamaged, ttRubble, ttMax
}
typedef enum CTerrainMap::ETileType * ETileTypeRef
Public Member Functions
CTerrainMap ()
CTerrainMap (const CTerrainMap &map)
~CTerrainMap ()
CTerrainMap & operator= (const CTerrainMap &map)
std::string MapName () const
int Width () const
int Height () const
ETileType TileType (int xindex, int yindex) const
ETileType TileType (const CPosition &pos) const
CPosition FindNearestTileType (const CPosition &pos, ETileType type)
void ChangeTileType (int xindex, int yindex, ETileType type)
void ChangeTileType (const CPosition &pos, ETileType type)
virtual bool LoadMap (std::shared_ptr< CDataSource > source)
Protected Attributes
std::vector< std::vector< ETileType > > DMap
std::vector< std::string > DStringMap
int DPlayerCount
std::string DMapName
Detailed Description
Definition at line 24 of file TerrainMap.h.
Member Typedef Documentation
ETileTypeRef
typedef enum CTerrainMap::ETileType * CTerrainMap::ETileTypeRef
Member Enumeration Documentation
ETileType
enum CTerrainMap::ETileType
Enumerator
ttNone
ttGrass
ttDirt
ttRock
ttTree
ttStump
ttWater
ttWall
ttWallDamaged
ttRubble
ttMax
Definition at line 26 of file TerrainMap.h.
                     {
             ttNone = 0,
             ttGrass,
             ttDirt,
             ttRock,
             ttTree,
             ttStump,
             ttWater,
             ttWall,
             ttWallDamaged,
             ttRubble,
             ttMax
         } ETileType, *ETileTypeRef;
Constructor & Destructor Documentation
CTerrainMap() [1/2]
CTerrainMap::CTerrainMap ()
Definition at line 24 of file TerrainMap.cpp.
{
 }
CTerrainMap() [2/2]
CTerrainMap::CTerrainMap (const CTerrainMap & map)
Definition at line 28 of file TerrainMap.cpp.
References DMap, DMapName, DPlayerCount, and DStringMap.
{
     DMap = map.DMap;
     DStringMap = map.DStringMap;
     DPlayerCount = map.DPlayerCount;
     DMapName = map.DMapName;
 }
~CTerrainMap()
CTerrainMap::~CTerrainMap ()
Definition at line 35 of file TerrainMap.cpp.
{
 }
Member Function Documentation
ChangeTileType() [1/2]
void CTerrainMap::ChangeTileType (int xindex, int yindex, ETileType type)
Definition at line 130 of file TerrainMap.cpp.
References DMap.
Referenced by ChangeTileType(), and TileType().
{
     if((-1 > xindex)||(-1 > yindex)){
         return;
     }
     if(DMap.size() <= yindex+1){
         return;
     }
     if(DMap[yindex+1].size() <= xindex+1){
         return;
     }
     DMap[yindex+1][xindex+1] = type;
 }
ChangeTileType() [2/2]
void CTerrainMap::ChangeTileType (const CPosition & pos, ETileType type) inline
Definition at line 75 of file TerrainMap.h.
References ChangeTileType(), LoadMap(), CPosition::X(), and CPosition::Y().
{
             ChangeTileType(pos.X(), pos.Y(), type);
         };
FindNearestTileType()
CPosition CTerrainMap::FindNearestTileType (const CPosition & pos, ETileType type)
Definition at line 64 of file TerrainMap.cpp.
References DMap, Height(), Width(), CPosition::X(), and CPosition::Y().
Referenced by TileType().
{
     int MaxDistance = Width() > Height() ? Width() : Height();
     int XOffset = pos.X() + 1;
     int YOffset = pos.Y() + 1;
     for(int SearchDistance = 0; SearchDistance < MaxDistance; SearchDistance++){
         int PositiveX = XOffset + SearchDistance;
         int NegativeX = XOffset - SearchDistance;
         int PositiveY = YOffset + SearchDistance;
         int NegativeY = YOffset - SearchDistance;
         bool SearchPX = true;
         bool SearchNX = true;
         bool SearchPY = true;
         bool SearchNY = true;
         if(0 >= NegativeX){
             NegativeX = 1;
             SearchNX = false;
         }
         if(PositiveX + 1 >= DMap[0].size()){
             PositiveX = DMap[0].size() - 2;
             SearchPX = false;
         }
         if(0 >= NegativeY){
             NegativeY = 1;
             SearchNY = false;
         }
         if(PositiveY + 1 >= DMap.size()){
             PositiveY = DMap.size() - 2;
             SearchPY = false;
         }
         if(!SearchNX && !SearchNY && !SearchPX && !SearchPY){
             break;
         }
         if(SearchNY){
             for(int XOff = NegativeX; XOff <= PositiveX; XOff++){
                 if(type == DMap[NegativeY][XOff]){
                     return CPosition(XOff-1, NegativeY-1);
                 }
             }
         }
         if(SearchPX){
             for(int YOff = NegativeY; YOff <= PositiveY; YOff++){
                 if(type == DMap[YOff][PositiveX]){
                     return CPosition(PositiveX-1, YOff-1);
                 }
             }
         }
         if(SearchPY){
             for(int XOff = PositiveX; XOff >= NegativeX; XOff--){
                 if(type == DMap[PositiveY][XOff]){
                     return CPosition(XOff-1, PositiveY-1);
                 }
             }
         }
         if(SearchNX){
             for(int YOff = PositiveY; YOff >= NegativeY; YOff--){
                 if(type == DMap[YOff][NegativeX]){
                     return CPosition(NegativeX-1, YOff-1);
                 }
             }
         }
     }
     return CPosition(-1, -1);
 }
Height()
int CTerrainMap::Height () const
Definition at line 60 of file TerrainMap.cpp.
References DMap.
Referenced by CAssetDecoratedMap::CanPlaceAsset(), CAssetDecoratedMap::CreateVisibilityMap(), CAssetDecoratedMap::FindAssetPlacement(), CAssetDecoratedMap::FindNearestReachableTileType(), FindNearestTileType(), CRouterMap::FindRoute(), and CAssetDecoratedMap::LoadMap().
{
     return DMap.size()-2;
 }
LoadMap()
bool CTerrainMap::LoadMap (std::shared_ptr< CDataSource > source) virtual
Reimplemented in CAssetDecoratedMap.
Definition at line 143 of file TerrainMap.cpp.
References DEBUG_LOW, DMap, DMapName, DStringMap, PrintDebug, PrintError, CLineDataSource::Read(), CTokenizer::Tokenize(), ttDirt, ttGrass, ttRock, ttTree, ttWall, ttWallDamaged, and ttWater.
Referenced by ChangeTileType(), and CAssetDecoratedMap::LoadMap().
{
     CLineDataSource LineSource(source);
     std::string TempString;
     std::vector< std::string > Tokens;
     int MapWidth, MapHeight;
     bool ReturnStatus = false;
     //int PlayerColorsFound = 0;
     DMap.clear();
     if(!LineSource.Read(DMapName)){
         PrintError("Failed to read map line.\n");
         goto LoadMapExit;
     }
     if(!LineSource.Read(TempString)){
         PrintError("Failed to read map line.\n");
         goto LoadMapExit;
     }
     CTokenizer::Tokenize(Tokens, TempString);
     if(2 != Tokens.size()){
         PrintError("Invalid map dimensions %s (%zd).\n",TempString.c_str(), Tokens.size());
         for(int I = 0; I < Tokens.size(); I++){
             PrintError("Tokens[%d] = %s\n",I,Tokens[I].c_str());
         }
         goto LoadMapExit;
     }
     try{
         MapWidth = std::stoi(Tokens[0]);
         MapHeight = std::stoi(Tokens[1]);
         PrintDebug(DEBUG_LOW, "Map %s is %d x %d\n",DMapName.c_str(), MapWidth, MapHeight);
         if((8 > MapWidth)||(8 > MapHeight)){
             PrintError("Invalid map dimensions.\n");
             goto LoadMapExit;
         }
         while(DStringMap.size() < MapHeight + 2){
             if(!LineSource.Read(TempString)){
                 PrintError("Failed to read map line.\n");
                 goto LoadMapExit;
             }
             DStringMap.push_back(TempString);
             if(MapWidth + 2 > DStringMap.back().length()){
                 PrintError("Map line %zd too short!\n", DStringMap.size());
                 goto LoadMapExit;
             }
         }
         if(MapHeight + 2 > DStringMap.size()){
             PrintError("Map has too few lines!\n");
             goto LoadMapExit;
         }
         DMap.resize(MapHeight+2);
         for(int Index = 0; Index < DMap.size(); Index++){
             DMap[Index].resize(MapWidth+2);
             for(int Inner = 0; Inner < MapWidth+2; Inner++){
                 switch(DStringMap[Index][Inner]){
                     case 'G':   DMap[Index][Inner] = ttGrass;
                                 break;
                     case 'F':   DMap[Index][Inner] = ttTree;
                                 break;
                     case 'D':   DMap[Index][Inner] = ttDirt;
                                 break;
                     case 'W':   DMap[Index][Inner] = ttWall;
                                 break;
                     case 'w':   DMap[Index][Inner] = ttWallDamaged;
                                 break;
                     case 'R':   DMap[Index][Inner] = ttRock;
                                 break;
                     case ' ':   DMap[Index][Inner] = ttWater;
                                 break;
                     default:    PrintError("Unknwon tile type '%c'on line %d\n", DStringMap[Index][Inner],Index+2);
                                 goto LoadMapExit;
                                 break;
                 }
             }
         }
         ReturnStatus = true;
     }
     catch(std::exception &E){
         PrintError("%s\n",E.what());
     }
 LoadMapExit:
     return ReturnStatus;
 }
MapName()
std::string CTerrainMap::MapName () const
Definition at line 49 of file TerrainMap.cpp.
References DMapName.
{
     return DMapName;
 }
operator=()
CTerrainMap & CTerrainMap::operator= (const CTerrainMap & map)
Definition at line 39 of file TerrainMap.cpp.
References DMap, DMapName, DPlayerCount, and DStringMap.
Referenced by CAssetDecoratedMap::operator=().
{
     if(this != &map){
         DMap = map.DMap;
         DStringMap = map.DStringMap;
         DPlayerCount = map.DPlayerCount;
         DMapName = map.DMapName;
     }
     return *this;
 }
TileType() [1/2]
ETileType CTerrainMap::TileType (int xindex, int yindex) const inline
Definition at line 58 of file TerrainMap.h.
References ttNone.
Referenced by CAssetDecoratedMap::CanPlaceAsset(), CRouterMap::FindRoute(), and TileType().
{
             if((-1 > xindex)||(-1 > yindex)){
                 return ttNone;
             }
             if(DMap.size() <= yindex+1){
                 return ttNone;
             }
             if(DMap[yindex+1].size() <= xindex+1){
                 return ttNone;
             }
             return DMap[yindex+1][xindex+1];
         };
TileType() [2/2]
ETileType CTerrainMap::TileType (const CPosition & pos) const inline
Definition at line 70 of file TerrainMap.h.
References ChangeTileType(), FindNearestTileType(), TileType(), CPosition::X(), and CPosition::Y().
{
             return TileType(pos.X(), pos.Y());
         };
Width()
int CTerrainMap::Width () const
Definition at line 53 of file TerrainMap.cpp.
References DMap.
Referenced by CAssetDecoratedMap::CanPlaceAsset(), CAssetDecoratedMap::CreateVisibilityMap(), CAssetDecoratedMap::FindAssetPlacement(), CAssetDecoratedMap::FindNearestReachableTileType(), FindNearestTileType(), CRouterMap::FindRoute(), and CAssetDecoratedMap::LoadMap().
{
     if(DMap.size()){
         return DMap[0].size()-2;
     }
     return 0;
 }
Member Data Documentation
DMap
std::vector< std::vector< ETileType > > CTerrainMap::DMap protected
Definition at line 41 of file TerrainMap.h.
Referenced by ChangeTileType(), CAssetDecoratedMap::CreateInitializeMap(), CTerrainMap(), CAssetDecoratedMap::FindNearestReachableTileType(), FindNearestTileType(), Height(), LoadMap(), operator=(), CAssetDecoratedMap::UpdateMap(), and Width().
DMapName
std::string CTerrainMap::DMapName protected
Definition at line 44 of file TerrainMap.h.
Referenced by CTerrainMap(), LoadMap(), MapName(), and operator=().
DPlayerCount
int CTerrainMap::DPlayerCount protected
Definition at line 43 of file TerrainMap.h.
Referenced by CTerrainMap(), and operator=().
DStringMap
std::vector< std::string > CTerrainMap::DStringMap protected
Definition at line 42 of file TerrainMap.h.
Referenced by CTerrainMap(), LoadMap(), and operator=().
The documentation for this class was generated from the following files:
include/TerrainMap.h
src/TerrainMap.cpp