ECS 160 Project: CPlayerCapabilityCancel::CActivatedCapability Class Reference
CPlayerCapabilityCancel::CActivatedCapability Class Reference
Public Member Functions
CActivatedCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
virtual ~CActivatedCapability ()
int PercentComplete (int max)
bool IncrementStep ()
void Cancel ()
Public Member Functions inherited from CActivatedPlayerCapability
CActivatedPlayerCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
virtual ~CActivatedPlayerCapability ()
Additional Inherited Members
Protected Attributes inherited from CActivatedPlayerCapability
std::shared_ptr< CPlayerAsset > DActor
std::shared_ptr< CPlayerData > DPlayerData
std::shared_ptr< CPlayerAsset > DTarget
Detailed Description
Definition at line 337 of file BasicCapabilities.cpp.
Constructor & Destructor Documentation
CActivatedCapability()
CPlayerCapabilityCancel::CActivatedCapability::CActivatedCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
Definition at line 388 of file BasicCapabilities.cpp.
                                                                                                                                                                                     :
 CActivatedPlayerCapability(actor, playerdata, target){
 }
~CActivatedCapability()
virtual CPlayerCapabilityCancel::CActivatedCapability::~CActivatedCapability () inline virtual
Definition at line 342 of file BasicCapabilities.cpp.
References CPlayerCapabilityStandGround::CActivatedCapability::Cancel(), CPlayerCapabilityStandGround::CActivatedCapability::IncrementStep(), and CPlayerCapabilityStandGround::CActivatedCapability::PercentComplete().
 {};
Member Function Documentation
Cancel()
void CPlayerCapabilityCancel::CActivatedCapability::Cancel () virtual
Implements CActivatedPlayerCapability.
Definition at line 421 of file BasicCapabilities.cpp.
References CActivatedPlayerCapability::DActor.
Referenced by CPlayerCapabilityConvey::CActivatedCapability::~CActivatedCapability().
{
     DActor->PopCommand();
 }
IncrementStep()
bool CPlayerCapabilityCancel::CActivatedCapability::IncrementStep () virtual
Implements CActivatedPlayerCapability.
Definition at line 398 of file BasicCapabilities.cpp.
References aaConstruct, aaNone, SAssetCommand::DAction, SAssetCommand::DActivatedCapability, CActivatedPlayerCapability::DActor, and SAssetCommand::DAssetTarget.
Referenced by CPlayerCapabilityConvey::CActivatedCapability::~CActivatedCapability().
{
     DActor->PopCommand();
     if(aaNone != DActor->Action()){
         SAssetCommand AssetCommand;
         AssetCommand = DActor->CurrentCommand();
         if(aaConstruct == AssetCommand.DAction){
             if(AssetCommand.DAssetTarget){
                 AssetCommand.DAssetTarget->CurrentCommand().DActivatedCapability->Cancel();
             }
             else if(AssetCommand.DActivatedCapability){
                 AssetCommand.DActivatedCapability->Cancel();
             }
         }
         else if(AssetCommand.DActivatedCapability){
             AssetCommand.DActivatedCapability->Cancel();
         }
     }
     return true;
 }
PercentComplete()
int CPlayerCapabilityCancel::CActivatedCapability::PercentComplete (int max) virtual
Implements CActivatedPlayerCapability.
Definition at line 394 of file BasicCapabilities.cpp.
Referenced by CPlayerCapabilityConvey::CActivatedCapability::~CActivatedCapability().
{
     return 0;
 }
The documentation for this class was generated from the following file:
src/BasicCapabilities.cpp