ECS 160 Project: CPlayerCapabilityPatrol::CActivatedCapability Class Reference
CPlayerCapabilityPatrol::CActivatedCapability Class Reference
Public Member Functions
CActivatedCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
virtual ~CActivatedCapability ()
int PercentComplete (int max)
bool IncrementStep ()
void Cancel ()
Public Member Functions inherited from CActivatedPlayerCapability
CActivatedPlayerCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
virtual ~CActivatedPlayerCapability ()
Additional Inherited Members
Protected Attributes inherited from CActivatedPlayerCapability
std::shared_ptr< CPlayerAsset > DActor
std::shared_ptr< CPlayerData > DPlayerData
std::shared_ptr< CPlayerAsset > DTarget
Detailed Description
Definition at line 550 of file BasicCapabilities.cpp.
Constructor & Destructor Documentation
CActivatedCapability()
CPlayerCapabilityPatrol::CActivatedCapability::CActivatedCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
Definition at line 605 of file BasicCapabilities.cpp.
                                                                                                                                                                                     :
 CActivatedPlayerCapability(actor, playerdata, target){
 }
~CActivatedCapability()
virtual CPlayerCapabilityPatrol::CActivatedCapability::~CActivatedCapability () inline virtual
Definition at line 555 of file BasicCapabilities.cpp.
References CPlayerCapabilityConvey::CActivatedCapability::Cancel(), CPlayerCapabilityConvey::CActivatedCapability::IncrementStep(), and CPlayerCapabilityConvey::CActivatedCapability::PercentComplete().
 {};
Member Function Documentation
Cancel()
void CPlayerCapabilityPatrol::CActivatedCapability::Cancel () virtual
Implements CActivatedPlayerCapability.
Definition at line 639 of file BasicCapabilities.cpp.
References CActivatedPlayerCapability::DActor.
Referenced by CPlayerCapabilityAttack::CActivatedCapability::~CActivatedCapability().
{
     DActor->PopCommand();
 }
IncrementStep()
bool CPlayerCapabilityPatrol::CActivatedCapability::IncrementStep () virtual
Implements CActivatedPlayerCapability.
Definition at line 615 of file BasicCapabilities.cpp.
References aaCapability, aaWalk, actPatrol, SAssetCommand::DAction, SAssetCommand::DActivatedCapability, CActivatedPlayerCapability::DActor, SGameEvent::DAsset, SAssetCommand::DAssetTarget, SAssetCommand::DCapability, dMax, CActivatedPlayerCapability::DPlayerData, CActivatedPlayerCapability::DTarget, SGameEvent::DType, and etAcknowledge.
Referenced by CPlayerCapabilityAttack::CActivatedCapability::~CActivatedCapability().
{
     SAssetCommand PatrolCommand, WalkCommand;
     SGameEvent TempEvent;
     TempEvent.DType = etAcknowledge;
     TempEvent.DAsset = DActor;
     DPlayerData->AddGameEvent(TempEvent);
     PatrolCommand.DAction = aaCapability;
     PatrolCommand.DCapability = actPatrol;
     PatrolCommand.DAssetTarget = DPlayerData->CreateMarker(DActor->Position(), false);
     PatrolCommand.DActivatedCapability = std::make_shared< CActivatedCapability >(DActor, DPlayerData, PatrolCommand.DAssetTarget);
     DActor->ClearCommand();
     DActor->PushCommand(PatrolCommand);
     WalkCommand.DAction = aaWalk;
     WalkCommand.DAssetTarget = DTarget;
     if(!DActor->TileAligned()){
         DActor->Direction((EDirection)((DActor->Position().TileOctant() + dMax/2) % dMax));
     }
     DActor->PushCommand(WalkCommand);
     return true;
 }
PercentComplete()
int CPlayerCapabilityPatrol::CActivatedCapability::PercentComplete (int max) virtual
Implements CActivatedPlayerCapability.
Definition at line 611 of file BasicCapabilities.cpp.
Referenced by CPlayerCapabilityAttack::CActivatedCapability::~CActivatedCapability().
{
     return 0;
 }
The documentation for this class was generated from the following file:
src/BasicCapabilities.cpp