ECS 160 Project: CPath Class Reference
CPath Class Reference
#include <Path.h>
Public Member Functions
CPath ()
CPath (const CPath &path)
CPath (const std::string &path)
CPath & operator= (const CPath &path)
CPath Containing () const
bool IsRelative () const
bool IsAbsolute () const
bool IsValid () const
int ComponentCount () const
std::string Component (int index) const
std::string ToString () const
operator std::string () const
CPath Simplify (const CPath &destpath) const
CPath Relative (const CPath &destpath) const
Static Public Member Functions
static CPath SimplifyPath (const CPath &srcpath, const CPath &destpath)
static CPath RelativePath (const CPath &srcpath, const CPath &destpath)
static CPath CurrentPath ()
static CPath CurrentPath (const CPath &path)
Static Protected Member Functions
static bool DecomposePath (std::vector< std::string > &decomp, const std::string &path)
Protected Attributes
std::vector< std::string > DDecomposedPath
bool DIsRelative
bool DIsValid
Static Protected Attributes
static const char DDelimiter = '/'
static const std::string DDelimiterString = "/"
Detailed Description
Definition at line 23 of file Path.h.
Constructor & Destructor Documentation
CPath() [1/3]
CPath::CPath ()
Definition at line 24 of file Path.cpp.
References DIsRelative, and DIsValid.
Referenced by CurrentPath().
             {
     DIsRelative = true;
     DIsValid = false;
 }
CPath() [2/3]
CPath::CPath (const CPath & path)
Definition at line 29 of file Path.cpp.
References DDecomposedPath, DIsRelative, and DIsValid.
{
     DDecomposedPath = path.DDecomposedPath;
     DIsRelative = path.DIsRelative;
     DIsValid = path.DIsValid;
 }
CPath() [3/3]
CPath::CPath (const std::string & path)
Definition at line 35 of file Path.cpp.
References DDecomposedPath, DDelimiter, DecomposePath(), DIsRelative, and DIsValid.
{
     DIsValid = DecomposePath(DDecomposedPath, path);
     DIsRelative = true;
     if(path.length()){
         if(path[0] == DDelimiter){
             DIsRelative = false;
         }
     }
 }
Member Function Documentation
Component()
std::string CPath::Component (int index) const inline
Definition at line 58 of file Path.h.
References CurrentPath(), Relative(), RelativePath(), Simplify(), SimplifyPath(), and ToString().
{
             if((0 > index)||(index >= DDecomposedPath.size())){
                 return "";
             }
             return DDecomposedPath[index];
         };
ComponentCount()
int CPath::ComponentCount () const inline
Definition at line 54 of file Path.h.
{
             return DDecomposedPath.size();
         };
Containing()
CPath CPath::Containing () const
Definition at line 54 of file Path.cpp.
References DDecomposedPath, DIsRelative, and DIsValid.
Referenced by CFileDataSource::Container(), and CDirectoryDataSourceContainer::Container().
{
     CPath ReturnPath(*this);
     if(ReturnPath.DDecomposedPath.size()){
         ReturnPath.DDecomposedPath.pop_back();
     }
     else if(ReturnPath.DIsRelative){
         ReturnPath.DDecomposedPath.push_back("..");
     }
     else{
         ReturnPath.DIsValid = false;
     }
     return ReturnPath;
 }
CurrentPath() [1/2]
CPath CPath::CurrentPath () static
Definition at line 235 of file Path.cpp.
References CPath().
Referenced by CDirectoryDataSourceContainer::CDirectoryDataSourceContainer(), CFileDataSource::CFileDataSource(), Component(), CurrentPath(), and RelativePath().
{
     std::vector< char > CurrentPathName;
     CurrentPathName.resize(1024);
     while(NULL == getcwd(CurrentPathName.data(), CurrentPathName.size())){
         CurrentPathName.resize(CurrentPathName.size() * 2);
     }
     return CPath(CurrentPathName.data());
 }
CurrentPath() [2/2]
CPath CPath::CurrentPath (const CPath & path) static
Definition at line 245 of file Path.cpp.
References CurrentPath(), SimplifyPath(), and ToString().
{
     CPath NewPath = SimplifyPath(CurrentPath(), path);
     chdir(NewPath.ToString().c_str());
     return CurrentPath();
 }
DecomposePath()
bool CPath::DecomposePath (std::vector< std::string > & decomp, const std::string & path) static protected
Definition at line 107 of file Path.cpp.
References DDelimiter, and DDelimiterString.
Referenced by CPath().
{
     size_t Anchor, DelimiterLocation;
     bool PathIsRelative = true;
     size_t Index = 0;
     if(0 == path.length()){
         return false;
     }
     if(path[0] == DDelimiter){
         PathIsRelative = false;
     }
     decomp.clear();
     Anchor = 0;
     while((Anchor + 1 < path.length()) && (-1 != (DelimiterLocation = path.find(DDelimiterString, Anchor)))){
         decomp.push_back(path.substr(Anchor, DelimiterLocation - Anchor));
         Anchor = DelimiterLocation + 1;
     }
     if(Anchor < path.length()){
         std::string TempString = path.substr(Anchor, path.length() - Anchor);
         if(TempString != DDelimiterString){
             decomp.push_back(TempString);
         }
     }
     if(decomp.size()){
         if(!decomp[0].length()){
             decomp.erase(decomp.begin());
         }
     }
     while(Index  < decomp.size()){
         if(decomp[Index] == "."){
             decomp.erase(decomp.begin());
         }
         else if(decomp[Index] == ".."){
             if(Index){
                 Index--;
                 decomp.erase(decomp.begin() + Index);
                 decomp.erase(decomp.begin() + Index);
             }
             else if(!PathIsRelative){
                 return false;
             }
             else{
                 Index++;
             }
         }
         else{
             Index++;
         }
     }
     return true;
 }
IsAbsolute()
bool CPath::IsAbsolute () const inline
Definition at line 46 of file Path.h.
References DIsRelative.
Referenced by SimplifyPath().
{
             return !DIsRelative;
         };
IsRelative()
bool CPath::IsRelative () const inline
Definition at line 42 of file Path.h.
References DIsRelative.
{
             return DIsRelative;
         };
IsValid()
bool CPath::IsValid () const inline
Definition at line 50 of file Path.h.
References DIsValid.
{
             return DIsValid;
         };
operator std::string()
CPath::operator std::string () const
Definition at line 95 of file Path.cpp.
References ToString().
{
     return this->ToString();
 }
operator=()
CPath & CPath::operator= (const CPath & path)
Definition at line 45 of file Path.cpp.
References DDecomposedPath, DIsRelative, and DIsValid.
{
     if(&path != this){
         DDecomposedPath = path.DDecomposedPath;
         DIsRelative = path.DIsRelative;
         DIsValid = path.DIsValid;
     }
     return *this;
 }
Relative()
CPath CPath::Relative (const CPath & destpath) const
Definition at line 103 of file Path.cpp.
References RelativePath().
Referenced by Component().
{
     return RelativePath(*this, destpath);
 }
RelativePath()
CPath CPath::RelativePath (const CPath & srcpath, const CPath & destpath) static
Definition at line 203 of file Path.cpp.
References CurrentPath(), DDecomposedPath, DIsRelative, Simplify(), and SimplifyPath().
Referenced by Component(), and Relative().
{
     CPath ReturnPath(destpath);
     std::vector< std::string > BasePath;
     ReturnPath.DIsRelative = true;
     if(srcpath.DIsRelative){
         if(destpath.DIsRelative){
             return SimplifyPath(srcpath,destpath);
         }
         else{
             return RelativePath(CurrentPath().Simplify(srcpath), destpath);
         }
     }
     else{
         BasePath = srcpath.DDecomposedPath;
         while(ReturnPath.DDecomposedPath.size() && BasePath.size()){
             if(ReturnPath.DDecomposedPath[0] == BasePath[0]){
                 ReturnPath.DDecomposedPath.erase(ReturnPath.DDecomposedPath.begin());
                 BasePath.erase(BasePath.begin());
             }
             else{
                 break;
             }
         }
         while(BasePath.size()){
             ReturnPath.DDecomposedPath.insert(ReturnPath.DDecomposedPath.begin(), "..");
             BasePath.erase(BasePath.begin());
         }
     }
     return ReturnPath;
 }
Simplify()
CPath CPath::Simplify (const CPath & destpath) const
Definition at line 99 of file Path.cpp.
References SimplifyPath().
Referenced by CDirectoryDataSourceContainer::CDirectoryDataSourceContainer(), CFileDataSource::CFileDataSource(), Component(), CDirectoryDataSourceContainer::DataSource(), CDirectoryDataSourceContainer::DataSourceContainer(), and RelativePath().
{
     return SimplifyPath(*this, destpath);
 }
SimplifyPath()
CPath CPath::SimplifyPath (const CPath & srcpath, const CPath & destpath) static
Definition at line 161 of file Path.cpp.
References DDecomposedPath, DIsRelative, DIsValid, and IsAbsolute().
Referenced by Component(), CurrentPath(), RelativePath(), and Simplify().
{
     CPath ReturnPath;
     std::vector< std::string > BasePath;
     std::vector< std::string > RelPath;
     size_t Index = 0;
     ReturnPath.DIsValid = true;
     if(destpath.IsAbsolute()){
        ReturnPath.DIsRelative = false;
     }
     else{
         ReturnPath.DIsRelative = srcpath.DIsRelative;
         ReturnPath.DDecomposedPath = srcpath.DDecomposedPath;
     }
     RelPath = destpath.DDecomposedPath;
     while(Index  < RelPath.size()){
         if(RelPath[Index] == "."){
             RelPath.erase(RelPath.begin());
         }
         else if(RelPath[Index] == ".."){
             if(Index){
                 Index--;
                 RelPath.erase(RelPath.begin() + Index);
                 RelPath.erase(RelPath.begin() + Index);
             }
             else if(ReturnPath.DDecomposedPath.size()){
                 ReturnPath.DDecomposedPath.erase(ReturnPath.DDecomposedPath.end() - 1);
                 RelPath.erase(RelPath.begin());
             }
             else{
                 ReturnPath.DIsValid = false;
                 return ReturnPath;
             }
         }
         else{
             Index++;
         }
     }
     ReturnPath.DDecomposedPath.insert(ReturnPath.DDecomposedPath.end(), RelPath.begin(), RelPath.end());
     return ReturnPath;
 }
ToString()
std::string CPath::ToString () const
Definition at line 70 of file Path.cpp.
References DDecomposedPath, DDelimiterString, DIsRelative, and DIsValid.
Referenced by CDirectoryDataSourceContainer::CDirectoryDataSourceContainer(), CFileDataSource::CFileDataSource(), Component(), CFileDataSource::Container(), CDirectoryDataSourceContainer::Container(), CurrentPath(), CDirectoryDataSourceContainer::DataSource(), CDirectoryDataSourceContainer::DataSourceContainer(), and operator std::string().
{
     std::string TempString;
     size_t StartIndex = 0;
     if(!DIsValid){
         return "";
     }
     if(DIsRelative){
         if(DDecomposedPath.size()){
             if(DDecomposedPath[0] != ".."){
                 TempString = ".";
             }
             else{
                 TempString = "..";
             }
             StartIndex = 1;
         }
     }
     while(StartIndex < DDecomposedPath.size()){
         TempString += DDelimiterString + DDecomposedPath[StartIndex];
         StartIndex++;
     }
     return TempString;
 }
Member Data Documentation
DDecomposedPath
std::vector< std::string > CPath::DDecomposedPath protected
Definition at line 25 of file Path.h.
Referenced by Containing(), CPath(), operator=(), RelativePath(), SimplifyPath(), and ToString().
DDelimiter
const char CPath::DDelimiter = '/' static protected
Definition at line 30 of file Path.h.
Referenced by CPath(), and DecomposePath().
DDelimiterString
const std::string CPath::DDelimiterString = "/" static protected
Definition at line 31 of file Path.h.
Referenced by DecomposePath(), and ToString().
DIsRelative
bool CPath::DIsRelative protected
Definition at line 26 of file Path.h.
Referenced by Containing(), CPath(), IsAbsolute(), IsRelative(), operator=(), RelativePath(), SimplifyPath(), and ToString().
DIsValid
bool CPath::DIsValid protected
Definition at line 27 of file Path.h.
Referenced by Containing(), CPath(), IsValid(), operator=(), SimplifyPath(), and ToString().
The documentation for this class was generated from the following files:
include/Path.h
src/Path.cpp