ECS 160 Project: CGameModel Class Reference
CGameModel Class Reference
#include <GameModel.h>
Public Member Functions
CGameModel (int mapindex, uint64_t seed, EPlayerColor newcolors[pcMax])
int GameCycle () const
bool ValidAsset (std::shared_ptr< CPlayerAsset > asset)
std::shared_ptr< CAssetDecoratedMap > Map () const
std::shared_ptr< CPlayerData > Player (EPlayerColor color) const
void Timestep ()
void ClearGameEvents ()
Protected Attributes
CRandomNumberGenerator DRandomNumberGenerator
std::shared_ptr< CAssetDecoratedMap > DActualMap
std::vector< std::vector< std::shared_ptr< CPlayerAsset > > > DAssetOccupancyMap
std::vector< std::vector< bool > > DDiagonalOccupancyMap
CRouterMap DRouterMap
std::shared_ptr< CPlayerData > DPlayers [pcMax]
std::vector< std::vector< int > > DLumberAvailable
int DGameCycle
int DHarvestTime
int DHarvestSteps
int DMineTime
int DMineSteps
int DConveyTime
int DConveySteps
int DDeathTime
int DDeathSteps
int DDecayTime
int DDecaySteps
int DLumberPerHarvest
int DGoldPerMining
Detailed Description
Definition at line 163 of file GameModel.h.
Constructor & Destructor Documentation
CGameModel()
CGameModel::CGameModel (int mapindex, uint64_t seed, EPlayerColor newcolors[pcMax])
Definition at line 456 of file GameModel.cpp.
References CPlayerData::DActualMap, CAssetDecoratedMap::DuplicateMap(), pcMax, CTerrainMap::ttTree, and CPlayerAsset::UpdateFrequency().
{
     DHarvestTime = 5;
     DHarvestSteps = CPlayerAsset::UpdateFrequency() * DHarvestTime;
     DMineTime = 5;
     DMineSteps = CPlayerAsset::UpdateFrequency() * DMineTime;
     DConveyTime = 1;
     DConveySteps = CPlayerAsset::UpdateFrequency() * DConveyTime;
     DDeathTime = 1;
     DDeathSteps = CPlayerAsset::UpdateFrequency() * DDeathTime;
     DDecayTime = 4;
     DDecaySteps = CPlayerAsset::UpdateFrequency() * DDecayTime;
     DLumberPerHarvest = 100;
     DGoldPerMining = 100;
     DRandomNumberGenerator.Seed(seed);
     DActualMap = CAssetDecoratedMap::DuplicateMap(mapindex, newcolors);
     for(int PlayerIndex = 0; PlayerIndex < pcMax; PlayerIndex++){
         DPlayers[PlayerIndex] = std::make_shared< CPlayerData > (DActualMap, (EPlayerColor)PlayerIndex);
     }
     DAssetOccupancyMap.resize(DActualMap->Height());
     for(auto &Row : DAssetOccupancyMap){
         Row.resize(DActualMap->Width());
     }
     DDiagonalOccupancyMap.resize(DActualMap->Height());
     for(auto &Row : DDiagonalOccupancyMap){
         Row.resize(DActualMap->Width());
     }
     DLumberAvailable.resize(DActualMap->Height());
     for(auto &Row : DLumberAvailable){
         Row.resize(DActualMap->Width());
     }
     for(int Row = 0; Row < DActualMap->Height(); Row++){
         for(int Col = 0; Col < DActualMap->Width(); Col++){
             if(CTerrainMap::ttTree == DActualMap->TileType(Col, Row)){
                 DLumberAvailable[Row][Col] = DPlayers[0]->Lumber();
             }
             else{
                 DLumberAvailable[Row][Col] = 0;
             }
         }
     }
 }
Member Function Documentation
ClearGameEvents()
void CGameModel::ClearGameEvents ()
Definition at line 1107 of file GameModel.cpp.
References pcMax.
{
     for(int PlayerIndex = 0; PlayerIndex < pcMax; PlayerIndex++){
         DPlayers[PlayerIndex]->ClearGameEvents();
     }
 }
GameCycle()
int CGameModel::GameCycle () const inline
Definition at line 189 of file GameModel.h.
References CPlayerData::DGameCycle.
{
             return DGameCycle;
         };
Map()
std::shared_ptr< CAssetDecoratedMap > CGameModel::Map () const inline
Definition at line 194 of file GameModel.h.
References CPlayerData::ClearGameEvents(), and CPlayerData::DActualMap.
{
             return DActualMap;
         };
Player()
std::shared_ptr< CPlayerData > CGameModel::Player (EPlayerColor color) const
Definition at line 512 of file GameModel.cpp.
References pcMax.
{
     if((0 > color)||(pcMax <= color)){
         return nullptr;
     }
     return DPlayers[color];
 }
Timestep()
void CGameModel::Timestep ()
Definition at line 519 of file GameModel.cpp.
References aaAttack, aaBuild, aaCapability, aaConstruct, aaConveyGold, aaConveyLumber, aaDeath, aaDecay, aaHarvestLumber, aaMineGold, aaNone, aaRepair, aaStandGround, aaWalk, actNone, atCastle, atKeep, atLumberMill, atNone, atTownHall, SAssetCommand::DAction, SAssetCommand::DActivatedCapability, CPlayerData::DActualMap, SGameEvent::DAsset, SAssetCommand::DAssetTarget, SAssetCommand::DCapability, CPlayerData::DGameCycle, CPosition::DistanceSquared(), dMax, SGameEvent::DType, etAttacked, etDeath, etHarvest, etMeleeHit, etMissleFire, etMissleHit, etWorkComplete, CPlayerCapability::FindCapability(), CPlayerData::Gold(), CPosition::HalfTileHeight(), CPosition::HalfTileWidth(), CPlayerData::IsAlive(), pcMax, pcNone, RangeToDistanceSquared(), CPosition::SetFromTile(), CPosition::SetToTile(), CPosition::TileWidth(), CTerrainMap::ttStump, CTerrainMap::ttTree, CPlayerAsset::UpdateFrequency(), CPosition::X(), and CPosition::Y().
{
     std::vector< SGameEvent > CurrentEvents;
     SGameEvent TempEvent;
     for(auto &Row : DAssetOccupancyMap){
         for(auto &Cell : Row){
             Cell = nullptr;
         }
     }
     for(auto &Row : DDiagonalOccupancyMap){
         for(int Index = 0; Index < Row.size(); Index++){
             Row[Index] = false;
         }
     }
     for(auto &Asset : DActualMap->Assets()){
         if((aaConveyGold != Asset->Action())&&(aaConveyLumber != Asset->Action())&&(aaMineGold != Asset->Action())){
             DAssetOccupancyMap[Asset->TilePositionY()][Asset->TilePositionX()] = Asset;
         }
     }
     for(int PlayerIndex = 1; PlayerIndex < pcMax; PlayerIndex++){
         if(DPlayers[PlayerIndex]->IsAlive()){
             DPlayers[PlayerIndex]->UpdateVisibility();
         }
     }
     auto AllAssets = DActualMap->Assets();
     for(auto &Asset : AllAssets){
         if(aaNone == Asset->Action()){
             Asset->PopCommand();
         }
         if(aaCapability == Asset->Action()){
             SAssetCommand Command = Asset->CurrentCommand();
             if(Command.DActivatedCapability){
                 if(Command.DActivatedCapability->IncrementStep()){
                     // All Done
                 }
             }
             else{
                 auto PlayerCapability = CPlayerCapability::FindCapability(Command.DCapability);
                 Asset->PopCommand();
                 if(PlayerCapability->CanApply(Asset, DPlayers[Asset->Color()], Command.DAssetTarget)){
                     PlayerCapability->ApplyCapability(Asset, DPlayers[Asset->Color()], Command.DAssetTarget);
                 }
                 else{
                     // Can't apply notify problem
                 }
             }
         }
         else if(aaHarvestLumber == Asset->Action()){
             SAssetCommand Command = Asset->CurrentCommand();
             CPosition TilePosition = Command.DAssetTarget->TilePosition();
             EDirection HarvestDirection = Asset->TilePosition().AdjacentTileDirection(TilePosition);
             if(CTerrainMap::ttTree != DActualMap->TileType(TilePosition)){
                 HarvestDirection = dMax;
                 TilePosition = Asset->TilePosition();
             }
             if(dMax == HarvestDirection){
                 if(TilePosition == Asset->TilePosition()){
                     CPosition NewPosition = DPlayers[Asset->Color()]->PlayerMap()->FindNearestReachableTileType(Asset->TilePosition(), CTerrainMap::ttTree);
                     // Find new lumber
                     Asset->PopCommand();
                     if(0 <= NewPosition.X()){
                         NewPosition.SetFromTile(NewPosition);
                         Command.DAssetTarget = DPlayers[Asset->Color()]->CreateMarker(NewPosition, false);
                         Asset->PushCommand(Command);
                         Command.DAction = aaWalk;
                         Asset->PushCommand(Command);
                         Asset->ResetStep();
                     }
                 }
                 else{
                     SAssetCommand NewCommand = Command;
                     NewCommand.DAction = aaWalk;
                     Asset->PushCommand(NewCommand);
                     Asset->ResetStep();
                 }
             }
             else{
                 TempEvent.DType = etHarvest;
                 TempEvent.DAsset = Asset;
                 CurrentEvents.push_back(TempEvent);
                 Asset->Direction(HarvestDirection);
                 Asset->IncrementStep();
                 if(DHarvestSteps <= Asset->Step()){
                     std::weak_ptr< CPlayerAsset > NearestRepository = DPlayers[Asset->Color()]->FindNearestOwnedAsset(Asset->Position(), {atTownHall, atKeep, atCastle, atLumberMill});
                     DLumberAvailable[TilePosition.Y()][TilePosition.X()] -= DLumberPerHarvest;
                     if(0 >= DLumberAvailable[TilePosition.Y()][TilePosition.X()]){
                         DActualMap->ChangeTileType(TilePosition, CTerrainMap::ttStump);
                     }
                     if(!NearestRepository.expired()){
                         Command.DAction = aaConveyLumber;
                         Command.DAssetTarget = NearestRepository.lock();
                         Asset->PushCommand(Command);
                         Command.DAction = aaWalk;
                         Asset->PushCommand(Command);
                         Asset->Lumber(DLumberPerHarvest);
                         Asset->ResetStep();
                     }
                     else{
                         Asset->PopCommand();
                         Asset->Lumber(DLumberPerHarvest);
                         Asset->ResetStep();
                     }
                 }
             }
         }
         else if(aaMineGold == Asset->Action()){
             SAssetCommand Command = Asset->CurrentCommand();
             CPosition ClosestPosition = Command.DAssetTarget->ClosestPosition(Asset->Position());
             CPosition TilePosition;
             EDirection MineDirection;
             TilePosition.SetToTile(ClosestPosition);
             MineDirection = Asset->TilePosition().AdjacentTileDirection(TilePosition);
             if((dMax == MineDirection)&&(TilePosition != Asset->TilePosition())){
                 SAssetCommand NewCommand = Command;
                 NewCommand.DAction = aaWalk;
                 Asset->PushCommand(NewCommand);
                 Asset->ResetStep();
             }
             else{
                 if(0 == Asset->Step()){
                     if((Command.DAssetTarget->CommandCount() + 1) * DGoldPerMining <=  Command.DAssetTarget->Gold()){
                         SAssetCommand NewCommand;
                         NewCommand.DAction = aaBuild; // Pretend active
                         NewCommand.DAssetTarget = Asset;
                         Command.DAssetTarget->EnqueueCommand(NewCommand);
                         Asset->IncrementStep();
                         Asset->TilePosition(Command.DAssetTarget->TilePosition());
                     }
                     else{
                         // Look for new mine or give up?
                         Asset->PopCommand();
                     }
                 }
                 else{
                     Asset->IncrementStep();
                     if(DMineSteps <= Asset->Step()){
                         std::shared_ptr< CPlayerAsset > OldTarget = Command.DAssetTarget;
                         std::weak_ptr< CPlayerAsset > NearestRepository = DPlayers[Asset->Color()]->FindNearestOwnedAsset(Asset->Position(), {atTownHall, atKeep, atCastle});
                         CPosition NextTarget(DPlayers[Asset->Color()]->PlayerMap()->Width()-1,DPlayers[Asset->Color()]->PlayerMap()->Height()-1);
                         Command.DAssetTarget->DecrementGold(DGoldPerMining);
                         Command.DAssetTarget->PopCommand();
                         if(0 >= Command.DAssetTarget->Gold()){
                             SAssetCommand NewCommand;
                             NewCommand.DAction = aaDeath;
                             Command.DAssetTarget->ClearCommand();
                             Command.DAssetTarget->PushCommand(NewCommand);
                             Command.DAssetTarget->ResetStep();
                         }
                         Asset->Gold(DGoldPerMining);
                         if(!NearestRepository.expired()){
                             Command.DAction = aaConveyGold;
                             Command.DAssetTarget = NearestRepository.lock();
                             Asset->PushCommand(Command);
                             Command.DAction = aaWalk;
                             Asset->PushCommand(Command);
                             Asset->ResetStep();
                             NextTarget = Command.DAssetTarget->TilePosition();
                         }
                         else{
                             Asset->PopCommand();
                         }
                         Asset->TilePosition(DPlayers[Asset->Color()]->PlayerMap()->FindAssetPlacement(Asset, OldTarget, NextTarget));
                     }
                 }
             }
         }
         else if(aaStandGround == Asset->Action()){
             SAssetCommand Command = Asset->CurrentCommand();
             auto NewTarget = DPlayers[Asset->Color()]->FindNearestEnemy(Asset->Position(), Asset->EffectiveRange());
             if(NewTarget.expired()){
                 Command.DAction = aaNone;
             }
             else{
                 Command.DAction = aaAttack;
                 Command.DAssetTarget = NewTarget.lock();
             }
             Asset->PushCommand(Command);
             Asset->ResetStep();
         }
         else if(aaRepair == Asset->Action()){
             SAssetCommand CurrentCommand = Asset->CurrentCommand();
             if(CurrentCommand.DAssetTarget->Alive()){
                 EDirection RepairDirection = Asset->TilePosition().AdjacentTileDirection(CurrentCommand.DAssetTarget->TilePosition(), CurrentCommand.DAssetTarget->Size());
                 if(dMax == RepairDirection){
                     SAssetCommand NextCommand = Asset->NextCommand();
                     CurrentCommand.DAction = aaWalk;
                     Asset->PushCommand(CurrentCommand);
                     Asset->ResetStep();
                 }
                 else{
                     Asset->Direction(RepairDirection);
                     Asset->IncrementStep();
                     // Assume same movement as attack
                     if(Asset->Step() == Asset->AttackSteps()){
                         if(DPlayers[Asset->Color()]->Gold() && DPlayers[Asset->Color()]->Lumber()){
                             int RepairPoints = (CurrentCommand.DAssetTarget->MaxHitPoints() * (Asset->AttackSteps() + Asset->ReloadSteps())) / (CPlayerAsset::UpdateFrequency() * CurrentCommand.DAssetTarget->BuildTime());
                             if(0 == RepairPoints){
                                 RepairPoints = 1;
                             }
                             DPlayers[Asset->Color()]->DecrementGold(1);
                             DPlayers[Asset->Color()]->DecrementLumber(1);
                             CurrentCommand.DAssetTarget->IncrementHitPoints(RepairPoints);
                             if(CurrentCommand.DAssetTarget->HitPoints() == CurrentCommand.DAssetTarget->MaxHitPoints()){
                                 TempEvent.DType = etWorkComplete;
                                 TempEvent.DAsset = Asset;
                                 DPlayers[Asset->Color()]->AddGameEvent(TempEvent);
                                 Asset->PopCommand();
                             }
                         }
                         else{
                             // Stop repair
                             Asset->PopCommand();
                         }
                     }
                     if(Asset->Step() >= (Asset->AttackSteps() + Asset->ReloadSteps())){
                        Asset->ResetStep();
                     }
                 }
             }
             else{
                 Asset->PopCommand();
             }
         }
         else if(aaAttack == Asset->Action()){
             SAssetCommand CurrentCommand = Asset->CurrentCommand();
             if(atNone == Asset->Type()){
                 CPosition ClosestTargetPosition = CurrentCommand.DAssetTarget->ClosestPosition(Asset->Position());
                 CPosition DeltaPosition(ClosestTargetPosition.X() - Asset->PositionX(), ClosestTargetPosition.Y() - Asset->PositionY());
                 int Movement = CPosition::TileWidth() * 5 / CPlayerAsset::UpdateFrequency();
                 int TargetDistance = Asset->Position().Distance(ClosestTargetPosition);
                 int Divisor = (TargetDistance + Movement - 1)/ Movement;
                 if(Divisor){
                     DeltaPosition.X( DeltaPosition.X() / Divisor);
                     DeltaPosition.Y( DeltaPosition.Y() / Divisor);
                 }
                 Asset->PositionX(Asset->PositionX() + DeltaPosition.X());
                 Asset->PositionY(Asset->PositionY() + DeltaPosition.Y());
                 Asset->Direction(Asset->Position().DirectionTo(ClosestTargetPosition));
                 if(CPosition::HalfTileWidth() * CPosition::HalfTileHeight() > Asset->Position().DistanceSquared(ClosestTargetPosition)){
                     TempEvent.DType = etMissleHit;
                     TempEvent.DAsset = Asset;
                     CurrentEvents.push_back(TempEvent);
                     if(CurrentCommand.DAssetTarget->Alive()){
                         SAssetCommand TargetCommand = CurrentCommand.DAssetTarget->CurrentCommand();
                         TempEvent.DType = etAttacked;
                         TempEvent.DAsset = CurrentCommand.DAssetTarget;
                         DPlayers[CurrentCommand.DAssetTarget->Color()]->AddGameEvent(TempEvent);
                         if(aaMineGold != TargetCommand.DAction){
                             if((aaConveyGold == TargetCommand.DAction)||(aaConveyLumber == TargetCommand.DAction)){
                                 // Damage the target
                                 CurrentCommand.DAssetTarget = TargetCommand.DAssetTarget;
                             }
                             else if((aaCapability == TargetCommand.DAction) && TargetCommand.DAssetTarget){
                                 if(CurrentCommand.DAssetTarget->Speed() && (aaConstruct == TargetCommand.DAssetTarget->Action())){
                                     CurrentCommand.DAssetTarget = TargetCommand.DAssetTarget;
                                 }
                             }
                             CurrentCommand.DAssetTarget->DecrementHitPoints(Asset->HitPoints());
                             if(!CurrentCommand.DAssetTarget->Alive()){
                                 SAssetCommand Command = CurrentCommand.DAssetTarget->CurrentCommand();
                                 TempEvent.DType = etDeath;
                                 TempEvent.DAsset = CurrentCommand.DAssetTarget;
                                 CurrentEvents.push_back(TempEvent);
                                 // Remove constructing
                                 if((aaCapability == Command.DAction)&&(Command.DAssetTarget)){
                                     if(aaConstruct == Command.DAssetTarget->Action()){
                                         DPlayers[Command.DAssetTarget->Color()]->DeleteAsset(Command.DAssetTarget);
                                     }
                                 }
                                 else if(aaConstruct == Command.DAction){
                                     if(Command.DAssetTarget){
                                         Command.DAssetTarget->ClearCommand();
                                     }
                                 }
                                 CurrentCommand.DAssetTarget->Direction((EDirection)((Asset->Direction() + dMax/2) % dMax));
                                 Command.DAction = aaDeath;
                                 CurrentCommand.DAssetTarget->ClearCommand();
                                 CurrentCommand.DAssetTarget->PushCommand(Command);
                                 CurrentCommand.DAssetTarget->ResetStep();
                             }
                         }
                     }
                     DPlayers[Asset->Color()]->DeleteAsset(Asset);
                 }
             }
             else if(CurrentCommand.DAssetTarget->Alive()){
                 if(1 == Asset->EffectiveRange()){
                     EDirection AttackDirection = Asset->TilePosition().AdjacentTileDirection(CurrentCommand.DAssetTarget->TilePosition(), CurrentCommand.DAssetTarget->Size());
                     if(dMax == AttackDirection){
                         SAssetCommand NextCommand = Asset->NextCommand();
                         if(aaStandGround != NextCommand.DAction){
                             CurrentCommand.DAction = aaWalk;
                             Asset->PushCommand(CurrentCommand);
                             Asset->ResetStep();
                         }
                         else{
                             Asset->PopCommand();
                         }
                     }
                     else{
                         Asset->Direction(AttackDirection);
                         Asset->IncrementStep();
                         if(Asset->Step() == Asset->AttackSteps()){
                             int Damage = Asset->EffectiveBasicDamage() - CurrentCommand.DAssetTarget->EffectiveArmor();
                             Damage = 0 > Damage ? 0 : Damage;
                             Damage += Asset->EffectivePiercingDamage();
                             if(DRandomNumberGenerator.Random() & 0x1){ // 50% chance half damage
                                 Damage /= 2;
                             }
                             CurrentCommand.DAssetTarget->DecrementHitPoints(Damage);
                             TempEvent.DType = etMeleeHit;
                             TempEvent.DAsset = Asset;
                             CurrentEvents.push_back(TempEvent);
                             TempEvent.DType = etAttacked;
                             TempEvent.DAsset = CurrentCommand.DAssetTarget;
                             DPlayers[CurrentCommand.DAssetTarget->Color()]->AddGameEvent(TempEvent);
                             if(!CurrentCommand.DAssetTarget->Alive()){
                                 SAssetCommand Command = CurrentCommand.DAssetTarget->CurrentCommand();
                                 TempEvent.DType = etDeath;
                                 TempEvent.DAsset = CurrentCommand.DAssetTarget;
                                 CurrentEvents.push_back(TempEvent);
                                 // Remove constructing
                                 if((aaCapability == Command.DAction)&&(Command.DAssetTarget)){
                                     if(aaConstruct == Command.DAssetTarget->Action()){
                                         DPlayers[Command.DAssetTarget->Color()]->DeleteAsset(Command.DAssetTarget);
                                     }
                                 }
                                 else if(aaConstruct == Command.DAction){
                                     if(Command.DAssetTarget){
                                         Command.DAssetTarget->ClearCommand();
                                     }
                                 }
                                 Command.DCapability = actNone;
                                 Command.DAssetTarget = nullptr;
                                 Command.DActivatedCapability = nullptr;
                                 CurrentCommand.DAssetTarget->Direction((EDirection)((AttackDirection + dMax/2) % dMax));
                                 Command.DAction = aaDeath;
                                 CurrentCommand.DAssetTarget->ClearCommand();
                                 CurrentCommand.DAssetTarget->PushCommand(Command);
                                 CurrentCommand.DAssetTarget->ResetStep();
                             }
                         }
                         if(Asset->Step() >= (Asset->AttackSteps() + Asset->ReloadSteps())){
                            Asset->ResetStep();
                         }
                     }
                 }
                 else{ // EffectiveRanged
                     CPosition ClosestTargetPosition = CurrentCommand.DAssetTarget->ClosestPosition(Asset->Position());
                     if(ClosestTargetPosition.DistanceSquared( Asset->Position() ) > RangeToDistanceSquared(Asset->EffectiveRange())){
                         SAssetCommand NextCommand = Asset->NextCommand();
                         if(aaStandGround != NextCommand.DAction){
                             CurrentCommand.DAction = aaWalk;
                             Asset->PushCommand(CurrentCommand);
                             Asset->ResetStep();
                         }
                         else{
                             Asset->PopCommand();
                         }
                     }
                     else{
                         /*
                         CPosition DeltaPosition(ClosestTargetPosition.X() - Asset->PositionX(), ClosestTargetPosition.Y() - Asset->PositionY());
                         int DivX = DeltaPosition.X() / CPosition::HalfTileWidth();
                         int DivY = DeltaPosition.Y() / CPosition::HalfTileHeight();
                         int Div;
                         EDirection AttackDirection;
                         DivX = 0 > DivX ? -DivX : DivX;
                         DivY = 0 > DivY ? -DivY : DivY;
                         Div = DivX > DivY ? DivX : DivY;
                         if(Div){
                             DeltaPosition.X(DeltaPosition.X() / Div);
                             DeltaPosition.Y(DeltaPosition.Y() / Div);
                         }
                         DeltaPosition.IncrementX(CPosition::HalfTileWidth());
                         DeltaPosition.IncrementY(CPosition::HalfTileHeight());
                         if(0 > DeltaPosition.X()){
                             DeltaPosition.X(0);
                         }
                         if(0 > DeltaPosition.Y()){
                             DeltaPosition.Y(0);
                         }
                         if(CPosition::TileWidth() <= DeltaPosition.X()){
                             DeltaPosition.X(CPosition::TileWidth() - 1);
                         }
                         if(CPosition::TileHeight() <= DeltaPosition.Y()){
                             DeltaPosition.Y(CPosition::TileHeight() - 1);
                         }
                         AttackDirection = DeltaPosition.TileOctant();
                         */
                         EDirection AttackDirection = Asset->Position().DirectionTo(ClosestTargetPosition);
                         Asset->Direction(AttackDirection);
                         Asset->IncrementStep();
                         if(Asset->Step() == Asset->AttackSteps()){
                             SAssetCommand AttackCommand; // Create missle
                             auto ArrowAsset = DPlayers[pcNone]->CreateAsset("None");
                             int Damage = Asset->EffectiveBasicDamage() - CurrentCommand.DAssetTarget->EffectiveArmor();
                             Damage = 0 > Damage ? 0 : Damage;
                             Damage += Asset->EffectivePiercingDamage();
                             if(DRandomNumberGenerator.Random() & 0x1){ // 50% chance half damage
                                 Damage /= 2;
                             }
                             TempEvent.DType = etMissleFire;
                             TempEvent.DAsset = Asset;
                             CurrentEvents.push_back(TempEvent);
                             ArrowAsset->HitPoints(Damage);
                             ArrowAsset->Position(Asset->Position());
                             if(ArrowAsset->PositionX() < ClosestTargetPosition.X()){
                                 ArrowAsset->PositionX(ArrowAsset->PositionX() + CPosition::HalfTileWidth());
                             }
                             else if(ArrowAsset->PositionX() > ClosestTargetPosition.X()){
                                 ArrowAsset->PositionX(ArrowAsset->PositionX() - CPosition::HalfTileWidth());
                             }
                             if(ArrowAsset->PositionY() < ClosestTargetPosition.Y()){
                                 ArrowAsset->PositionY(ArrowAsset->PositionY() + CPosition::HalfTileHeight());
                             }
                             else if(ArrowAsset->PositionY() > ClosestTargetPosition.Y()){
                                 ArrowAsset->PositionY(ArrowAsset->PositionY() - CPosition::HalfTileHeight());
                             }
                             ArrowAsset->Direction(AttackDirection);
                             AttackCommand.DAction = aaConstruct;
                             AttackCommand.DAssetTarget = Asset;
                             ArrowAsset->PushCommand(AttackCommand);
                             AttackCommand.DAction = aaAttack;
                             AttackCommand.DAssetTarget = CurrentCommand.DAssetTarget;
                             ArrowAsset->PushCommand(AttackCommand);
                         }
                         if(Asset->Step() >= (Asset->AttackSteps() + Asset->ReloadSteps())){
                            Asset->ResetStep();
                         }
                     }
                 }
             }
             else{
                 SAssetCommand NextCommand = Asset->NextCommand();
                 Asset->PopCommand();
                 if(aaStandGround != NextCommand.DAction){
                     auto NewTarget = DPlayers[Asset->Color()]->FindNearestEnemy(Asset->Position(), Asset->EffectiveSight());
                     if(!NewTarget.expired()){
                         CurrentCommand.DAssetTarget = NewTarget.lock();
                         Asset->PushCommand(CurrentCommand);
                         Asset->ResetStep();
                     }
                 }
             }
         }
         else if((aaConveyLumber == Asset->Action())||(aaConveyGold == Asset->Action())){
             Asset->IncrementStep();
             if(DConveySteps <= Asset->Step()){
                 SAssetCommand Command = Asset->CurrentCommand();
                 CPosition NextTarget(DPlayers[Asset->Color()]->PlayerMap()->Width()-1,DPlayers[Asset->Color()]->PlayerMap()->Height()-1);
                 DPlayers[Asset->Color()]->IncrementGold(Asset->Gold());
                 DPlayers[Asset->Color()]->IncrementLumber(Asset->Lumber());
                 Asset->Gold(0);
                 Asset->Lumber(0);
                 Asset->PopCommand();
                 Asset->ResetStep();
                 if(aaNone != Asset->Action()){
                     NextTarget = Asset->CurrentCommand().DAssetTarget->TilePosition();
                 }
                 Asset->TilePosition(DPlayers[Asset->Color()]->PlayerMap()->FindAssetPlacement(Asset, Command.DAssetTarget, NextTarget));
             }
         }
         else if(aaConstruct == Asset->Action()){
             SAssetCommand Command = Asset->CurrentCommand();
             if(Command.DActivatedCapability){
                 if(Command.DActivatedCapability->IncrementStep()){
                     // All Done
                 }
             }
         }
         else if(aaDeath == Asset->Action()){
             Asset->IncrementStep();
             if(Asset->Step() > DDeathSteps){
                 if(Asset->Speed()){
                     SAssetCommand DecayCommand;
                     // Create corpse
                     auto CorpseAsset = DPlayers[pcNone]->CreateAsset("None");
                     DecayCommand.DAction = aaDecay;
                     CorpseAsset->Position(Asset->Position());
                     CorpseAsset->Direction(Asset->Direction());
                     CorpseAsset->PushCommand(DecayCommand);
                 }
                 DPlayers[Asset->Color()]->DeleteAsset(Asset);
             }
         }
         else if(aaDecay == Asset->Action()){
             Asset->IncrementStep();
             if(Asset->Step() > DDecaySteps){
                 DPlayers[Asset->Color()]->DeleteAsset(Asset);
             }
         }
         if(aaWalk == Asset->Action()){
             if(Asset->TileAligned()){
                 SAssetCommand Command = Asset->CurrentCommand();
                 SAssetCommand NextCommand = Asset->NextCommand();
                 EDirection TravelDirection;
                 CPosition MapTarget = Command.DAssetTarget->ClosestPosition(Asset->Position());
                 if(aaAttack == NextCommand.DAction){
                     // Check to see if can attack now
                     if(NextCommand.DAssetTarget->ClosestPosition(Asset->Position()).DistanceSquared( Asset->Position() ) <= RangeToDistanceSquared(Asset->EffectiveRange())){
                         Asset->PopCommand();
                         Asset->ResetStep();
                         continue;
                     }
                 }
                 TravelDirection = DRouterMap.FindRoute(*DPlayers[Asset->Color()]->PlayerMap(), *Asset, MapTarget);
                 if(dMax != TravelDirection){
                     Asset->Direction(TravelDirection);
                 }
                 else{
                     CPosition TilePosition;
                     TilePosition.SetToTile(MapTarget);
                     if((TilePosition == Asset->TilePosition())||(dMax != Asset->TilePosition().AdjacentTileDirection(TilePosition))){
                         Asset->PopCommand();
                         Asset->ResetStep();
                         continue;
                     }
                     else if(aaHarvestLumber == NextCommand.DAction){
                         CPosition NewPosition = DPlayers[Asset->Color()]->PlayerMap()->FindNearestReachableTileType(Asset->TilePosition(), CTerrainMap::ttTree);
                         // Find new lumber
                         Asset->PopCommand();
                         Asset->PopCommand();
                         if(0 <= NewPosition.X()){
                             NewPosition.SetFromTile(NewPosition);
                             Command.DAction = aaHarvestLumber;
                             Command.DAssetTarget = DPlayers[Asset->Color()]->CreateMarker(NewPosition, false);
                             Asset->PushCommand(Command);
                             Command.DAction = aaWalk;
                             Asset->PushCommand(Command);
                             Asset->ResetStep();
                             continue;
                         }
                     }
                     else{
                         Command.DAction = aaNone;
                         Asset->PushCommand(Command);
                         Asset->ResetStep();
                         continue;
                     }
                 }
             }
             if(!Asset->MoveStep(DAssetOccupancyMap, DDiagonalOccupancyMap)){
                 Asset->Direction((EDirection)((Asset->Position().TileOctant() + dMax/2) % dMax));
             }
         }
     }
     DGameCycle++;
     for(int PlayerIndex = 0; PlayerIndex < pcMax; PlayerIndex++){
         DPlayers[PlayerIndex]->IncrementCycle();
         DPlayers[PlayerIndex]->AppendGameEvents(CurrentEvents);
     }
 }
ValidAsset()
bool CGameModel::ValidAsset (std::shared_ptr< CPlayerAsset > asset)
Definition at line 503 of file GameModel.cpp.
References CPlayerData::DActualMap.
{
     for(auto &Asset : DActualMap->Assets()){
         if(asset == Asset){
             return true;
         }
     }
     return false;
 }
Member Data Documentation
DActualMap
std::shared_ptr< CAssetDecoratedMap > CGameModel::DActualMap protected
Definition at line 166 of file GameModel.h.
DAssetOccupancyMap
std::vector< std::vector< std::shared_ptr< CPlayerAsset > > > CGameModel::DAssetOccupancyMap protected
Definition at line 167 of file GameModel.h.
DConveySteps
int CGameModel::DConveySteps protected
Definition at line 178 of file GameModel.h.
DConveyTime
int CGameModel::DConveyTime protected
Definition at line 177 of file GameModel.h.
DDeathSteps
int CGameModel::DDeathSteps protected
Definition at line 180 of file GameModel.h.
DDeathTime
int CGameModel::DDeathTime protected
Definition at line 179 of file GameModel.h.
DDecaySteps
int CGameModel::DDecaySteps protected
Definition at line 182 of file GameModel.h.
DDecayTime
int CGameModel::DDecayTime protected
Definition at line 181 of file GameModel.h.
DDiagonalOccupancyMap
std::vector< std::vector< bool > > CGameModel::DDiagonalOccupancyMap protected
Definition at line 168 of file GameModel.h.
DGameCycle
int CGameModel::DGameCycle protected
Definition at line 172 of file GameModel.h.
DGoldPerMining
int CGameModel::DGoldPerMining protected
Definition at line 184 of file GameModel.h.
DHarvestSteps
int CGameModel::DHarvestSteps protected
Definition at line 174 of file GameModel.h.
DHarvestTime
int CGameModel::DHarvestTime protected
Definition at line 173 of file GameModel.h.
DLumberAvailable
std::vector< std::vector< int > > CGameModel::DLumberAvailable protected
Definition at line 171 of file GameModel.h.
DLumberPerHarvest
int CGameModel::DLumberPerHarvest protected
Definition at line 183 of file GameModel.h.
DMineSteps
int CGameModel::DMineSteps protected
Definition at line 176 of file GameModel.h.
DMineTime
int CGameModel::DMineTime protected
Definition at line 175 of file GameModel.h.
DPlayers
std::shared_ptr< CPlayerData > CGameModel::DPlayers[pcMax] protected
Definition at line 170 of file GameModel.h.
DRandomNumberGenerator
CRandomNumberGenerator CGameModel::DRandomNumberGenerator protected
Definition at line 165 of file GameModel.h.
DRouterMap
CRouterMap CGameModel::DRouterMap protected
Definition at line 169 of file GameModel.h.
The documentation for this class was generated from the following files:
include/GameModel.h
src/GameModel.cpp