ECS 160 Project: CPlayerCapability Class Reference
CPlayerCapability Class Reference abstract
#include <PlayerAsset.h>
Public Types
enum ETargetType {
ttNone = 0, ttAsset, ttTerrain, ttTerrainOrAsset,
ttPlayer
}
typedef enum CPlayerCapability::ETargetType * ETargetTypeRef
Public Member Functions
virtual ~CPlayerCapability ()
std::string Name () const
EAssetCapabilityType AssetCapabilityType () const
ETargetType TargetType () const
virtual bool CanInitiate (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata)=0
virtual bool CanApply (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)=0
virtual bool ApplyCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)=0
Static Public Member Functions
static std::shared_ptr< CPlayerCapability > FindCapability (EAssetCapabilityType type)
static std::shared_ptr< CPlayerCapability > FindCapability (const std::string &name)
static EAssetCapabilityType NameToType (const std::string &name)
static std::string TypeToName (EAssetCapabilityType type)
Protected Member Functions
CPlayerCapability (const std::string &name, ETargetType targettype)
Static Protected Member Functions
static std::unordered_map< std::string, std::shared_ptr< CPlayerCapability > > & NameRegistry ()
static std::unordered_map< int, std::shared_ptr< CPlayerCapability > > & TypeRegistry ()
static bool Register (std::shared_ptr< CPlayerCapability > capability)
Protected Attributes
std::string DName
EAssetCapabilityType DAssetCapabilityType
ETargetType DTargetType
Detailed Description
Definition at line 43 of file PlayerAsset.h.
Member Typedef Documentation
ETargetTypeRef
typedef enum CPlayerCapability::ETargetType * CPlayerCapability::ETargetTypeRef
Member Enumeration Documentation
ETargetType
enum CPlayerCapability::ETargetType
Enumerator
ttNone
ttAsset
ttTerrain
ttTerrainOrAsset
ttPlayer
Definition at line 45 of file PlayerAsset.h.
                     {
               ttNone = 0,
               ttAsset,
               ttTerrain,
               ttTerrainOrAsset,
               ttPlayer
         } ETargetType, *ETargetTypeRef;
Constructor & Destructor Documentation
CPlayerCapability()
CPlayerCapability::CPlayerCapability (const std::string & name, ETargetType targettype) protected
Definition at line 70 of file PlayerAsset.cpp.
{
     DName = name;
     DAssetCapabilityType = NameToType(name);
     DTargetType = targettype;
 }
~CPlayerCapability()
virtual CPlayerCapability::~CPlayerCapability () inline virtual
Definition at line 65 of file PlayerAsset.h.
 {};
Member Function Documentation
ApplyCapability()
virtual bool CPlayerCapability::ApplyCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target) pure virtual
Implemented in CPlayerCapabilityRepair, CPlayerCapabilityAttack, CPlayerCapabilityPatrol, CPlayerCapabilityConvey, CPlayerCapabilityCancel, CPlayerCapabilityStandGround, CPlayerCapabilityBuildRanger, CPlayerCapabilityMineHarvest, CPlayerCapabilityBuildingUpgrade, CPlayerCapabilityUnitUpgrade, CPlayerCapabilityBuildNormal, CPlayerCapabilityTrainNormal, and CPlayerCapabilityMove.
AssetCapabilityType()
EAssetCapabilityType CPlayerCapability::AssetCapabilityType () const inline
Definition at line 71 of file PlayerAsset.h.
Referenced by CPlayerCapabilityMove::ApplyCapability(), CPlayerCapabilityBuildNormal::ApplyCapability(), CPlayerCapabilityTrainNormal::ApplyCapability(), CPlayerCapabilityBuildingUpgrade::ApplyCapability(), CPlayerCapabilityUnitUpgrade::ApplyCapability(), CPlayerCapabilityMineHarvest::ApplyCapability(), CPlayerCapabilityBuildRanger::ApplyCapability(), CPlayerCapabilityStandGround::ApplyCapability(), CPlayerCapabilityCancel::ApplyCapability(), CPlayerCapabilityConvey::ApplyCapability(), CPlayerCapabilityPatrol::ApplyCapability(), CPlayerCapabilityAttack::ApplyCapability(), and CPlayerCapabilityRepair::ApplyCapability().
{
             return DAssetCapabilityType;
         };
CanApply()
virtual bool CPlayerCapability::CanApply (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target) pure virtual
Implemented in CPlayerCapabilityRepair, CPlayerCapabilityAttack, CPlayerCapabilityPatrol, CPlayerCapabilityConvey, CPlayerCapabilityCancel, CPlayerCapabilityStandGround, CPlayerCapabilityBuildRanger, CPlayerCapabilityMineHarvest, CPlayerCapabilityBuildingUpgrade, CPlayerCapabilityUnitUpgrade, CPlayerCapabilityBuildNormal, CPlayerCapabilityTrainNormal, and CPlayerCapabilityMove.
CanInitiate()
virtual bool CPlayerCapability::CanInitiate (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata) pure virtual
Implemented in CPlayerCapabilityRepair, CPlayerCapabilityAttack, CPlayerCapabilityPatrol, CPlayerCapabilityConvey, CPlayerCapabilityCancel, CPlayerCapabilityStandGround, CPlayerCapabilityBuildRanger, CPlayerCapabilityMineHarvest, CPlayerCapabilityBuildingUpgrade, CPlayerCapabilityUnitUpgrade, CPlayerCapabilityBuildNormal, CPlayerCapabilityTrainNormal, and CPlayerCapabilityMove.
FindCapability() [1/2]
std::shared_ptr< CPlayerCapability > CPlayerCapability::FindCapability (EAssetCapabilityType type) static
Definition at line 97 of file PlayerAsset.cpp.
Referenced by CAIPlayer::ActivatePeasants(), CAIPlayer::BuildBuilding(), CApplicationData::CalculateGameMode(), CUnitActionRenderer::DrawUnitAction(), CApplicationData::ProcessInputGameMode(), CApplicationData::RenderGameMode(), CGameModel::Timestep(), CAIPlayer::TrainArcher(), and CAIPlayer::TrainFootman().
{
     auto Iterator = TypeRegistry().find((int)type);
     if(Iterator != TypeRegistry().end()){
         return Iterator->second;
     }
     return std::shared_ptr< CPlayerCapability >();
 }
FindCapability() [2/2]
std::shared_ptr< CPlayerCapability > CPlayerCapability::FindCapability (const std::string & name) static
Definition at line 106 of file PlayerAsset.cpp.
{
     auto Iterator = NameRegistry().find(name);
     if(Iterator != NameRegistry().end()){
         return Iterator->second;
     }
     return std::shared_ptr< CPlayerCapability >();
 }
Name()
std::string CPlayerCapability::Name () const inline
Definition at line 67 of file PlayerAsset.h.
{
             return DName;
         };
NameRegistry()
std::unordered_map< std::string, std::shared_ptr< CPlayerCapability > > & CPlayerCapability::NameRegistry () static protected
Definition at line 76 of file PlayerAsset.cpp.
{
     static std::unordered_map< std::string, std::shared_ptr< CPlayerCapability > > TheRegistry;
     return TheRegistry;
 }
NameToType()
EAssetCapabilityType CPlayerCapability::NameToType (const std::string & name) static
Definition at line 115 of file PlayerAsset.cpp.
References actArmorUpgrade1, actArmorUpgrade2, actArmorUpgrade3, actArrowUpgrade1, actArrowUpgrade2, actArrowUpgrade3, actAttack, actBuildAdvanced, actBuildArcher, actBuildBarracks, actBuildBlacksmith, actBuildCannonTower, actBuildCastle, actBuildFarm, actBuildFootman, actBuildGuardTower, actBuildKeep, actBuildLumberMill, actBuildPeasant, actBuildRanger, actBuildScoutTower, actBuildSimple, actBuildTownHall, actBuildWall, actCancel, actConvey, actLongbow, actMarksmanship, actMine, actMove, actNone, actPatrol, actRangerScouting, actRepair, actStandGround, actWeaponUpgrade1, actWeaponUpgrade2, actWeaponUpgrade3, and PrintError.
Referenced by CPlayerData::AddUpgrade(), CPlayerCapabilityUnitUpgrade::CActivatedCapability::CActivatedCapability(), CPlayerCapabilityBuildRanger::CActivatedCapability::CActivatedCapability(), CPlayerCapabilityUnitUpgrade::CActivatedCapability::Cancel(), CPlayerCapabilityBuildRanger::CActivatedCapability::Cancel(), CPlayerCapabilityUnitUpgrade::CActivatedCapability::IncrementStep(), CPlayerUpgrade::Load(), and CPlayerAssetType::Load().
{
     static std::unordered_map< std::string, EAssetCapabilityType > NameTypeTranslation({
         {"None",actNone},
         {"BuildPeasant",actBuildPeasant},
         {"BuildFootman",actBuildFootman},
         {"BuildArcher",actBuildArcher},
         {"BuildRanger",actBuildRanger},
         {"BuildFarm",actBuildFarm},
         {"BuildTownHall",actBuildTownHall},
         {"BuildBarracks",actBuildBarracks},
         {"BuildLumberMill",actBuildLumberMill},
         {"BuildBlacksmith",actBuildBlacksmith},
         {"BuildKeep",actBuildKeep},
         {"BuildCastle",actBuildCastle},
         {"BuildScoutTower",actBuildScoutTower},
         {"BuildGuardTower",actBuildGuardTower},
         {"BuildCannonTower",actBuildCannonTower},
         {"Move",actMove},
         {"Repair",actRepair},
         {"Mine",actMine},
         {"BuildSimple",actBuildSimple},
         {"BuildAdvanced",actBuildAdvanced},
         {"Convey",actConvey},
         {"Cancel",actCancel},
         {"BuildWall",actBuildWall},
         {"Attack",actAttack},
         {"StandGround",actStandGround},
         {"Patrol",actPatrol},
         {"WeaponUpgrade1",actWeaponUpgrade1},
         {"WeaponUpgrade2",actWeaponUpgrade2},
         {"WeaponUpgrade3",actWeaponUpgrade3},
         {"ArrowUpgrade1",actArrowUpgrade1},
         {"ArrowUpgrade2",actArrowUpgrade2},
         {"ArrowUpgrade3",actArrowUpgrade3},
         {"ArmorUpgrade1",actArmorUpgrade1},
         {"ArmorUpgrade2",actArmorUpgrade2},
         {"ArmorUpgrade3",actArmorUpgrade3},
         {"Longbow",actLongbow},
         {"RangerScouting",actRangerScouting},
         {"Marksmanship",actMarksmanship}
     });
     auto Iterator = NameTypeTranslation.find(name);
     if(Iterator != NameTypeTranslation.end()){
         return Iterator->second;
     }
     PrintError("Unknown capability name \"%s\"\n",name.c_str());
     return actNone;
 }
Register()
bool CPlayerCapability::Register (std::shared_ptr< CPlayerCapability > capability) static protected
Definition at line 88 of file PlayerAsset.cpp.
Referenced by CPlayerCapabilityMove::CRegistrant::CRegistrant(), CPlayerCapabilityBuildNormal::CRegistrant::CRegistrant(), CPlayerCapabilityBuildingUpgrade::CRegistrant::CRegistrant(), CPlayerCapabilityTrainNormal::CRegistrant::CRegistrant(), CPlayerCapabilityUnitUpgrade::CRegistrant::CRegistrant(), CPlayerCapabilityMineHarvest::CRegistrant::CRegistrant(), CPlayerCapabilityBuildRanger::CRegistrant::CRegistrant(), CPlayerCapabilityStandGround::CRegistrant::CRegistrant(), CPlayerCapabilityCancel::CRegistrant::CRegistrant(), CPlayerCapabilityConvey::CRegistrant::CRegistrant(), CPlayerCapabilityPatrol::CRegistrant::CRegistrant(), CPlayerCapabilityAttack::CRegistrant::CRegistrant(), and CPlayerCapabilityRepair::CRegistrant::CRegistrant().
{
     if(nullptr != FindCapability(capability->Name())){
         return false;
     }
     NameRegistry()[capability->Name()] = capability;
     TypeRegistry()[NameToType(capability->Name())] = capability;
     return true;
 }
TargetType()
ETargetType CPlayerCapability::TargetType () const inline
Definition at line 75 of file PlayerAsset.h.
{
             return DTargetType;
         };
TypeRegistry()
std::unordered_map< int, std::shared_ptr< CPlayerCapability > > & CPlayerCapability::TypeRegistry () static protected
Definition at line 82 of file PlayerAsset.cpp.
{
     static std::unordered_map< int, std::shared_ptr< CPlayerCapability > > TheRegistry;
     return TheRegistry;
 }
TypeToName()
std::string CPlayerCapability::TypeToName (EAssetCapabilityType type) static
Definition at line 165 of file PlayerAsset.cpp.
References CPlayerUpgrade::DRegistryByName, and CPlayerUpgrade::DRegistryByType.
Referenced by CPlayerUpgrade::Load().
{
     static std::vector< std::string > TypeStrings({
         "None",
         "BuildPeasant",
         "BuildFootman",
         "BuildArcher",
         "BuildRanger",
         "BuildFarm",
         "BuildTownHall",
         "BuildBarracks",
         "BuildLumberMill",
         "BuildBlacksmith",
         "BuildKeep",
         "BuildCastle",
         "BuildScoutTower",
         "BuildGuardTower",
         "BuildCannonTower",
         "Move",
         "Repair",
         "Mine",
         "BuildSimple",
         "BuildAdvanced",
         "Convey",
         "Cancel",
         "BuildWall",
         "Attack",
         "StandGround",
         "Patrol",
         "WeaponUpgrade1",
         "WeaponUpgrade2",
         "WeaponUpgrade3",
         "ArrowUpgrade1",
         "ArrowUpgrade2",
         "ArrowUpgrade3",
         "ArmorUpgrade1",
         "ArmorUpgrade2",
         "ArmorUpgrade3",
         "Longbow",
         "RangerScouting",
         "Marksmanship",});
     if((0 > type)||(type >= TypeStrings.size())){
         return "";
     }
     return TypeStrings[type];
 }
Member Data Documentation
DAssetCapabilityType
EAssetCapabilityType CPlayerCapability::DAssetCapabilityType protected
Definition at line 55 of file PlayerAsset.h.
DName
std::string CPlayerCapability::DName protected
Definition at line 54 of file PlayerAsset.h.
DTargetType
ETargetType CPlayerCapability::DTargetType protected
Definition at line 56 of file PlayerAsset.h.
The documentation for this class was generated from the following files:
include/PlayerAsset.h
src/PlayerAsset.cpp