ECS 160 Project: CSFVirtualIODataSource Class Reference
CSFVirtualIODataSource Class Reference
Public Member Functions
CSFVirtualIODataSource (std::shared_ptr< CDataSource > source)
SF_VIRTUAL_IO SFVirtualIO () const
Static Protected Member Functions
static sf_count_t GetFileLength (CSFVirtualIODataSource *iosource)
static sf_count_t Seek (sf_count_t offset, int whence, CSFVirtualIODataSource *iosource)
static sf_count_t Read (void *ptr, sf_count_t count, CSFVirtualIODataSource *iosource)
static sf_count_t Write (const void *ptr, sf_count_t count, CSFVirtualIODataSource *iosource)
static sf_count_t Tell (CSFVirtualIODataSource *iosource)
Protected Attributes
std::vector< uint8_t > DData
sf_count_t DOffset
Detailed Description
Definition at line 23 of file SoundClip.cpp.
Constructor & Destructor Documentation
CSFVirtualIODataSource()
CSFVirtualIODataSource::CSFVirtualIODataSource (std::shared_ptr< CDataSource > source)
Definition at line 40 of file SoundClip.cpp.
References DData, and DOffset.
{
     uint8_t TempByte;
     while(0 < source->Read(&TempByte, 1)){
         DData.push_back(TempByte);
     }
     DOffset = 0;
 }
Member Function Documentation
GetFileLength()
sf_count_t CSFVirtualIODataSource::GetFileLength (CSFVirtualIODataSource * iosource) static protected
Definition at line 60 of file SoundClip.cpp.
References DData.
Referenced by SFVirtualIO().
{
     return iosource->DData.size();
 }
Read()
sf_count_t CSFVirtualIODataSource::Read (void * ptr, sf_count_t count, CSFVirtualIODataSource * iosource) static protected
Definition at line 83 of file SoundClip.cpp.
References DData, and DOffset.
Referenced by SFVirtualIO().
{
     if(iosource->DOffset + count > iosource->DData.size()){
         count = iosource->DData.size() - iosource->DOffset;
     }
     memcpy(ptr, iosource->DData.data() + iosource->DOffset, count);
     iosource->DOffset += count;
     return count;
 }
Seek()
sf_count_t CSFVirtualIODataSource::Seek (sf_count_t offset, int whence, CSFVirtualIODataSource * iosource) static protected
Definition at line 64 of file SoundClip.cpp.
References DData, and DOffset.
Referenced by SFVirtualIO().
{
     if(SEEK_SET == whence){
         iosource->DOffset = offset;
     }
     else if(SEEK_CUR == whence){
         iosource->DOffset += offset;
     }
     else if(SEEK_END == whence){
         iosource->DOffset = iosource->DData.size() + offset;
     }
     if(0 > iosource->DOffset){
         iosource->DOffset = 0;
     }
     else if(iosource->DData.size() < iosource->DOffset){
         iosource->DOffset = iosource->DData.size();
     }
     return iosource->DOffset;
 }
SFVirtualIO()
SF_VIRTUAL_IO CSFVirtualIODataSource::SFVirtualIO () const
Definition at line 49 of file SoundClip.cpp.
References GetFileLength(), Read(), Seek(), Tell(), and Write().
Referenced by CSoundClip::Load().
{
     SF_VIRTUAL_IO ReturnIO;
     ReturnIO.get_filelen = (sf_vio_get_filelen)GetFileLength;
     ReturnIO.seek = (sf_vio_seek)Seek;
     ReturnIO.read = (sf_vio_read)Read;
     ReturnIO.write = (sf_vio_write)Write;
     ReturnIO.tell = (sf_vio_tell)Tell;
     return ReturnIO;
 }
Tell()
sf_count_t CSFVirtualIODataSource::Tell (CSFVirtualIODataSource * iosource) static protected
Definition at line 96 of file SoundClip.cpp.
References DOffset.
Referenced by SFVirtualIO().
{
     return iosource->DOffset;
 }
Write()
sf_count_t CSFVirtualIODataSource::Write (const void * ptr, sf_count_t count, CSFVirtualIODataSource * iosource) static protected
Definition at line 92 of file SoundClip.cpp.
Referenced by SFVirtualIO().
{
     return 0;
 }
Member Data Documentation
DData
std::vector< uint8_t > CSFVirtualIODataSource::DData protected
Definition at line 25 of file SoundClip.cpp.
Referenced by CSoundClip::CopyStereoClip(), CSFVirtualIODataSource(), CSoundClip::CSoundClip(), GetFileLength(), CSoundClip::Load(), CSoundClip::MixStereoClip(), CSoundClip::operator=(), Read(), Seek(), and CSoundClip::~CSoundClip().
DOffset
sf_count_t CSFVirtualIODataSource::DOffset protected
Definition at line 26 of file SoundClip.cpp.
Referenced by CSFVirtualIODataSource(), Read(), Seek(), and Tell().
The documentation for this class was generated from the following file:
src/SoundClip.cpp