ECS 160 Project: CPlayerAssetType Class Reference
CPlayerAssetType Class Reference
#include <PlayerAsset.h>
Public Member Functions
CPlayerAssetType ()
CPlayerAssetType (std::shared_ptr< CPlayerAssetType > res)
~CPlayerAssetType ()
std::string Name () const
EAssetType Type () const
EPlayerColor Color () const
int HitPoints () const
int Armor () const
int Sight () const
int ConstructionSight () const
int Size () const
int Speed () const
int GoldCost () const
int LumberCost () const
int FoodConsumption () const
int BuildTime () const
int AttackSteps () const
int ReloadSteps () const
int BasicDamage () const
int PiercingDamage () const
int Range () const
int ArmorUpgrade () const
int SightUpgrade () const
int SpeedUpgrade () const
int BasicDamageUpgrade () const
int PiercingDamageUpgrade () const
int RangeUpgrade () const
bool HasCapability (EAssetCapabilityType capability) const
std::vector< EAssetCapabilityType > Capabilities () const
void AddCapability (EAssetCapabilityType capability)
void RemoveCapability (EAssetCapabilityType capability)
void AddUpgrade (std::shared_ptr< CPlayerUpgrade > upgrade)
std::vector< EAssetType > AssetRequirements () const
std::shared_ptr< CPlayerAsset > Construct ()
Static Public Member Functions
static EAssetType NameToType (const std::string &name)
static std::string TypeToName (EAssetType type)
static int MaxSight ()
static bool LoadTypes (std::shared_ptr< CDataSourceContainer > container)
static bool Load (std::shared_ptr< CDataSource > source)
static std::shared_ptr< CPlayerAssetType > FindDefaultFromName (const std::string &name)
static std::shared_ptr< CPlayerAssetType > FindDefaultFromType (EAssetType type)
static std::shared_ptr< std::unordered_map< std::string, std::shared_ptr< CPlayerAssetType > > > DuplicateRegistry (EPlayerColor color)
Protected Attributes
std::weak_ptr< CPlayerAssetType > DThis
std::string DName
EAssetType DType
EPlayerColor DColor
std::vector< bool > DCapabilities
std::vector< EAssetType > DAssetRequirements
std::vector< std::shared_ptr< CPlayerUpgrade > > DAssetUpgrades
int DHitPoints
int DArmor
int DSight
int DConstructionSight
int DSize
int DSpeed
int DGoldCost
int DLumberCost
int DFoodConsumption
int DBuildTime
int DAttackSteps
int DReloadSteps
int DBasicDamage
int DPiercingDamage
int DRange
Static Protected Attributes
static std::unordered_map< std::string, std::shared_ptr< CPlayerAssetType > > DRegistry
static std::vector< std::string > DTypeStrings
static std::unordered_map< std::string, EAssetType > DNameTypeTranslation
Detailed Description
Definition at line 159 of file PlayerAsset.h.
Constructor & Destructor Documentation
CPlayerAssetType() [1/2]
CPlayerAssetType::CPlayerAssetType ()
Definition at line 358 of file PlayerAsset.cpp.
References actMax.
{
     DCapabilities.resize(actMax);
     for(int Index = 0; Index < DCapabilities.size(); Index++){
         DCapabilities[Index] = false;
     }
     DHitPoints = 1;
     DArmor = 0;
     DSight = 0;
     DConstructionSight = 0;
     DSize = 1;
     DSpeed = 0;
     DGoldCost = 0;
     DLumberCost = 0;
     DFoodConsumption = 0;
     DBuildTime = 0;
     DAttackSteps = 0;
     DReloadSteps = 0;
     DBasicDamage = 0;
     DPiercingDamage = 0;
     DRange = 0;
 }
CPlayerAssetType() [2/2]
CPlayerAssetType::CPlayerAssetType (std::shared_ptr< CPlayerAssetType > res)
Definition at line 380 of file PlayerAsset.cpp.
{
     if(nullptr != asset){
         DName = asset->DName;
         DType = asset->DType;
         DColor = asset->DColor;
         DCapabilities = asset->DCapabilities;
         DAssetRequirements = asset->DAssetRequirements;
         DHitPoints = asset->DHitPoints;
         DArmor = asset->DArmor;
         DSight = asset->DSight;
         DConstructionSight = asset->DConstructionSight;
         DSize = asset->DSize;
         DSpeed = asset->DSpeed;
         DGoldCost = asset->DGoldCost;
         DLumberCost = asset->DLumberCost;
         DFoodConsumption = asset->DFoodConsumption;
         DBuildTime = asset->DBuildTime;
         DAttackSteps = asset->DAttackSteps;
         DReloadSteps = asset->DReloadSteps;
         DBasicDamage = asset->DBasicDamage;
         DPiercingDamage = asset->DPiercingDamage;
         DRange = asset->DRange;
     }
 }
~CPlayerAssetType()
CPlayerAssetType::~CPlayerAssetType ()
Definition at line 405 of file PlayerAsset.cpp.
{
 }
Member Function Documentation
AddCapability()
void CPlayerAssetType::AddCapability (EAssetCapabilityType capability) inline
Definition at line 280 of file PlayerAsset.h.
{
             if((0 > capability)||(DCapabilities.size() <= capability)){
                 return;
             }
             DCapabilities[capability] = true;
         };
AddUpgrade()
void CPlayerAssetType::AddUpgrade (std::shared_ptr< CPlayerUpgrade > upgrade) inline
Definition at line 294 of file PlayerAsset.h.
{
             DAssetUpgrades.push_back(upgrade);
         };
Armor()
int CPlayerAssetType::Armor () const inline
Definition at line 208 of file PlayerAsset.h.
{
             return DArmor;
         };
ArmorUpgrade()
int CPlayerAssetType::ArmorUpgrade () const
Definition at line 409 of file PlayerAsset.cpp.
{
     int ReturnValue = 0;
     for(auto Upgrade : DAssetUpgrades){
         ReturnValue += Upgrade->Armor();
     }
     return ReturnValue;
 }
AssetRequirements()
std::vector< EAssetType > CPlayerAssetType::AssetRequirements () const inline
Definition at line 298 of file PlayerAsset.h.
{
             return DAssetRequirements;
         };
AttackSteps()
int CPlayerAssetType::AttackSteps () const inline
Definition at line 244 of file PlayerAsset.h.
{
             return DAttackSteps;
         };
BasicDamage()
int CPlayerAssetType::BasicDamage () const inline
Definition at line 252 of file PlayerAsset.h.
{
             return DBasicDamage;
         };
BasicDamageUpgrade()
int CPlayerAssetType::BasicDamageUpgrade () const
Definition at line 433 of file PlayerAsset.cpp.
{
     int ReturnValue = 0;
     for(auto Upgrade : DAssetUpgrades){
         ReturnValue += Upgrade->BasicDamage();
     }
     return ReturnValue;
 }
BuildTime()
int CPlayerAssetType::BuildTime () const inline
Definition at line 240 of file PlayerAsset.h.
{
             return DBuildTime;
         };
Capabilities()
std::vector< EAssetCapabilityType > CPlayerAssetType::Capabilities () const
Definition at line 457 of file PlayerAsset.cpp.
References actMax, and actNone.
{
     std::vector< EAssetCapabilityType > ReturnVector;
     for(int Index = actNone; Index < actMax; Index++){
         if(DCapabilities[Index]){
             ReturnVector.push_back((EAssetCapabilityType)Index);
         }
     }
     return ReturnVector;
 }
Color()
EPlayerColor CPlayerAssetType::Color () const inline
Definition at line 200 of file PlayerAsset.h.
{
             return DColor;
         };
Construct()
std::shared_ptr< CPlayerAsset > CPlayerAssetType::Construct ()
Definition at line 697 of file PlayerAsset.cpp.
References CPlayerAsset::DUpdateDivisor, and CPlayerAsset::DUpdateFrequency.
{
     if(auto ThisShared = DThis.lock()){
         return std::shared_ptr< CPlayerAsset >(new CPlayerAsset(ThisShared));
     }
     return nullptr;
 }
ConstructionSight()
int CPlayerAssetType::ConstructionSight () const inline
Definition at line 216 of file PlayerAsset.h.
{
             return DConstructionSight;
         };
DuplicateRegistry()
std::shared_ptr< std::unordered_map< std::string, std::shared_ptr< CPlayerAssetType > > > CPlayerAssetType::DuplicateRegistry (EPlayerColor color) static
Definition at line 684 of file PlayerAsset.cpp.
Referenced by CPlayerData::CPlayerData().
{
     std::shared_ptr< std::unordered_map< std::string, std::shared_ptr< CPlayerAssetType > > > ReturnRegistry( new std::unordered_map< std::string, std::shared_ptr< CPlayerAssetType > > );
     for(auto &It : DRegistry){
         std::shared_ptr< CPlayerAssetType > NewAssetType(new CPlayerAssetType(It.second));
         NewAssetType->DThis = NewAssetType;
         NewAssetType->DColor = color;
         (*ReturnRegistry)[It.first] = NewAssetType;
     }
     return ReturnRegistry;
 }
FindDefaultFromName()
std::shared_ptr< CPlayerAssetType > CPlayerAssetType::FindDefaultFromName (const std::string & name) static
Definition at line 671 of file PlayerAsset.cpp.
Referenced by CAssetRenderer::DrawMiniAssets().
{
     auto Iterator = DRegistry.find( name );
     if(Iterator != DRegistry.end()){
         return Iterator->second;
     }
     return std::shared_ptr< CPlayerAssetType >();
 }
FindDefaultFromType()
std::shared_ptr< CPlayerAssetType > CPlayerAssetType::FindDefaultFromType (EAssetType type) static
Definition at line 680 of file PlayerAsset.cpp.
Referenced by CAssetRenderer::DrawPlacement().
{
     return FindDefaultFromName( TypeToName(type) );
 }
FoodConsumption()
int CPlayerAssetType::FoodConsumption () const inline
Definition at line 236 of file PlayerAsset.h.
{
             return DFoodConsumption;
         };
GoldCost()
int CPlayerAssetType::GoldCost () const inline
Definition at line 228 of file PlayerAsset.h.
{
             return DGoldCost;
         };
HasCapability()
bool CPlayerAssetType::HasCapability (EAssetCapabilityType capability) const inline
Definition at line 271 of file PlayerAsset.h.
{
             if((0 > capability)||(DCapabilities.size() <= capability)){
                 return false;
             }
             return DCapabilities[capability];
         };
HitPoints()
int CPlayerAssetType::HitPoints () const inline
Definition at line 204 of file PlayerAsset.h.
{
             return DHitPoints;
         };
Load()
bool CPlayerAssetType::Load (std::shared_ptr< CDataSource > source) static
Definition at line 523 of file PlayerAsset.cpp.
References actMax, atNone, CPlayerCapability::NameToType(), pcNone, PrintError, and CLineDataSource::Read().
Referenced by LoadTypes().
{
     CLineDataSource LineSource(source);
     std::string Name, TempString;
     std::shared_ptr< CPlayerAssetType > PlayerAssetType;
     EAssetType AssetType;
     int CapabilityCount, AssetRequirementCount;
     bool ReturnStatus = false;
     if(nullptr == source){
         return false;
     }
     if(!LineSource.Read(Name)){
         PrintError("Failed to get resource type name.\n");
         return false;
     }
     AssetType = NameToType(Name);
     if((atNone == AssetType) && (Name != DTypeStrings[atNone])){
         PrintError("Unknown resource type %s.\n", Name.c_str());
         return false;
     }
     auto Iterator = DRegistry.find(Name);
     if(DRegistry.end() != Iterator){
         PlayerAssetType = Iterator->second;
     }
     else{
         PlayerAssetType = std::make_shared< CPlayerAssetType >();
         PlayerAssetType->DThis = PlayerAssetType;
         PlayerAssetType->DName = Name;
         DRegistry[Name] = PlayerAssetType;
     }
     PlayerAssetType->DType = AssetType;
     PlayerAssetType->DColor = pcNone;
     try{
         if(!LineSource.Read(TempString)){
             PrintError("Failed to get resource type hit points.\n");
             goto LoadExit;
         }
         PlayerAssetType->DHitPoints = std::stoi(TempString);
         if(!LineSource.Read(TempString)){
             PrintError("Failed to get resource type armor.\n");
             goto LoadExit;
         }
         PlayerAssetType->DArmor = std::stoi(TempString);
         if(!LineSource.Read(TempString)){
             PrintError("Failed to get resource type sight.\n");
             goto LoadExit;
         }
         PlayerAssetType->DSight = std::stoi(TempString);
         if(!LineSource.Read(TempString)){
             PrintError("Failed to get resource type construction sight.\n");
             goto LoadExit;
         }
         PlayerAssetType->DConstructionSight = std::stoi(TempString);
         if(!LineSource.Read(TempString)){
             PrintError("Failed to get resource type size.\n");
             goto LoadExit;
         }
         PlayerAssetType->DSize = std::stoi(TempString);
         if(!LineSource.Read(TempString)){
             PrintError("Failed to get resource type speed.\n");
             goto LoadExit;
         }
         PlayerAssetType->DSpeed = std::stoi(TempString);
         if(!LineSource.Read(TempString)){
             PrintError("Failed to get resource type gold cost.\n");
             goto LoadExit;
         }
         PlayerAssetType->DGoldCost = std::stoi(TempString);
         if(!LineSource.Read(TempString)){
             PrintError("Failed to get resource type lumber cost.\n");
             goto LoadExit;
         }
         PlayerAssetType->DLumberCost = std::stoi(TempString);
         if(!LineSource.Read(TempString)){
             PrintError("Failed to get resource type food consumption.\n");
             goto LoadExit;
         }
         PlayerAssetType->DFoodConsumption = std::stoi(TempString);
         if(!LineSource.Read(TempString)){
             PrintError("Failed to get resource type build time.\n");
             goto LoadExit;
         }
         PlayerAssetType->DBuildTime = std::stoi(TempString);
         if(!LineSource.Read(TempString)){
             PrintError("Failed to get resource type attack steps.\n");
             goto LoadExit;
         }
         PlayerAssetType->DAttackSteps = std::stoi(TempString);
         if(!LineSource.Read(TempString)){
             PrintError("Failed to get resource type reload steps.\n");
             goto LoadExit;
         }
         PlayerAssetType->DReloadSteps = std::stoi(TempString);
         if(!LineSource.Read(TempString)){
             PrintError("Failed to get resource type basic damage.\n");
             goto LoadExit;
         }
         PlayerAssetType->DBasicDamage = std::stoi(TempString);
         if(!LineSource.Read(TempString)){
             PrintError("Failed to get resource type piercing damage.\n");
             goto LoadExit;
         }
         PlayerAssetType->DPiercingDamage = std::stoi(TempString);
         if(!LineSource.Read(TempString)){
             PrintError("Failed to get resource type range.\n");
             goto LoadExit;
         }
         PlayerAssetType->DRange = std::stoi(TempString);
         if(!LineSource.Read(TempString)){
             PrintError("Failed to get capability count.\n");
             goto LoadExit;
         }
         CapabilityCount = std::stoi(TempString);
         PlayerAssetType->DCapabilities.resize(actMax);
         for(int Index = 0; Index < PlayerAssetType->DCapabilities.size(); Index++){
             PlayerAssetType->DCapabilities[Index] = false;
         }
         for(int Index = 0; Index < CapabilityCount; Index++){
             if(!LineSource.Read(TempString)){
                 PrintError("Failed to read capability %d.\n", Index);
                 goto LoadExit;
             }
             PlayerAssetType->AddCapability(CPlayerCapability::NameToType(TempString));
         }
         if(!LineSource.Read(TempString)){
             PrintError("Failed to get asset requirement count.\n");
             goto LoadExit;
         }
         AssetRequirementCount = std::stoi(TempString);
         for(int Index = 0; Index < AssetRequirementCount; Index++){
             if(!LineSource.Read(TempString)){
                 PrintError("Failed to read asset requirement %d.\n", Index);
                 goto LoadExit;
             }
             PlayerAssetType->DAssetRequirements.push_back(NameToType(TempString));
         }
         ReturnStatus = true;
     }
     catch(std::exception &E){
         PrintError("%s\n",E.what());
     }
 LoadExit:
     return ReturnStatus;
 }
LoadTypes()
bool CPlayerAssetType::LoadTypes (std::shared_ptr< CDataSourceContainer > container) static
Definition at line 492 of file PlayerAsset.cpp.
References atNone, DEBUG_LOW, Load(), pcNone, PrintDebug, and PrintError.
Referenced by CApplicationData::Init().
{
     auto FileIterator = container->First();
     if(FileIterator == nullptr){
         PrintError("FileIterator == nullptr\n");
         return false;
     }
     while((FileIterator != nullptr)&&(FileIterator->IsValid())){
         std::string Filename = FileIterator->Name();
         FileIterator->Next();
         if(Filename.rfind(".dat") == (Filename.length() - 4)){
             if(!CPlayerAssetType::Load(container->DataSource(Filename))){
                 PrintError("Failed to load resource \"%s\".\n",Filename.c_str());
                 continue;
             }
             else{
                 PrintDebug(DEBUG_LOW,"Loaded resource \"%s\".\n",Filename.c_str());
             }
         }
     }
     std::shared_ptr< CPlayerAssetType >  PlayerAssetType = std::make_shared< CPlayerAssetType >();
     PlayerAssetType->DThis = PlayerAssetType;
     PlayerAssetType->DName = "None";
     PlayerAssetType->DType = atNone;
     PlayerAssetType->DColor = pcNone;
     PlayerAssetType->DHitPoints = 256;
     DRegistry["None"] = PlayerAssetType;
     return true;
 }
LumberCost()
int CPlayerAssetType::LumberCost () const inline
Definition at line 232 of file PlayerAsset.h.
{
             return DLumberCost;
         };
MaxSight()
int CPlayerAssetType::MaxSight () static
Definition at line 483 of file PlayerAsset.cpp.
Referenced by CAssetDecoratedMap::CreateVisibilityMap().
{
     int MaxSightFound = 0;
     for(auto &ResType : DRegistry){
         MaxSightFound = MaxSightFound > ResType.second->DSight ? MaxSightFound : ResType.second->DSight;
     }
     return MaxSightFound;
 }
Name()
std::string CPlayerAssetType::Name () const inline
Definition at line 192 of file PlayerAsset.h.
{
             return DName;
         };
NameToType()
EAssetType CPlayerAssetType::NameToType (const std::string & name) static
Definition at line 468 of file PlayerAsset.cpp.
References atNone.
Referenced by CPlayerData::CPlayerData(), and CPlayerUpgrade::Load().
{
     auto Iterator = DNameTypeTranslation.find(name);
     if(Iterator != DNameTypeTranslation.end()){
         return Iterator->second;
     }
     return atNone;
 }
PiercingDamage()
int CPlayerAssetType::PiercingDamage () const inline
Definition at line 256 of file PlayerAsset.h.
{
             return DPiercingDamage;
         };
PiercingDamageUpgrade()
int CPlayerAssetType::PiercingDamageUpgrade () const
Definition at line 441 of file PlayerAsset.cpp.
{
     int ReturnValue = 0;
     for(auto Upgrade : DAssetUpgrades){
         ReturnValue += Upgrade->PiercingDamage();
     }
     return ReturnValue;
 }
Range()
int CPlayerAssetType::Range () const inline
Definition at line 260 of file PlayerAsset.h.
{
             return DRange;
         };
RangeUpgrade()
int CPlayerAssetType::RangeUpgrade () const
Definition at line 449 of file PlayerAsset.cpp.
{
     int ReturnValue = 0;
     for(auto Upgrade : DAssetUpgrades){
         ReturnValue += Upgrade->Range();
     }
     return ReturnValue;
 }
ReloadSteps()
int CPlayerAssetType::ReloadSteps () const inline
Definition at line 248 of file PlayerAsset.h.
{
             return DReloadSteps;
         };
RemoveCapability()
void CPlayerAssetType::RemoveCapability (EAssetCapabilityType capability) inline
Definition at line 287 of file PlayerAsset.h.
{
             if((0 > capability)||(DCapabilities.size() <= capability)){
                 return;
             }
             DCapabilities[capability] = false;
         };
Sight()
int CPlayerAssetType::Sight () const inline
Definition at line 212 of file PlayerAsset.h.
{
             return DSight;
         };
SightUpgrade()
int CPlayerAssetType::SightUpgrade () const
Definition at line 417 of file PlayerAsset.cpp.
{
     int ReturnValue = 0;
     for(auto Upgrade : DAssetUpgrades){
         ReturnValue += Upgrade->Sight();
     }
     return ReturnValue;
 }
Size()
int CPlayerAssetType::Size () const inline
Definition at line 220 of file PlayerAsset.h.
{
             return DSize;
         };
Speed()
int CPlayerAssetType::Speed () const inline
Definition at line 224 of file PlayerAsset.h.
{
             return DSpeed;
         };
SpeedUpgrade()
int CPlayerAssetType::SpeedUpgrade () const
Definition at line 425 of file PlayerAsset.cpp.
{
     int ReturnValue = 0;
     for(auto Upgrade : DAssetUpgrades){
         ReturnValue += Upgrade->Speed();
     }
     return ReturnValue;
 }
Type()
EAssetType CPlayerAssetType::Type () const inline
Definition at line 196 of file PlayerAsset.h.
{
             return DType;
         };
TypeToName()
std::string CPlayerAssetType::TypeToName (EAssetType type) static
Definition at line 476 of file PlayerAsset.cpp.
Referenced by CPlayerData::AddUpgrade(), CSoundEventRenderer::CSoundEventRenderer(), CUnitDescriptionRenderer::DrawUnitDescription(), and CPlayerData::FindBestAssetPlacement().
{
     if((0 > type)||(type >= DTypeStrings.size())){
         return "";
     }
     return DTypeStrings[type];
 }
Member Data Documentation
DArmor
int CPlayerAssetType::DArmor protected
Definition at line 169 of file PlayerAsset.h.
DAssetRequirements
std::vector< EAssetType > CPlayerAssetType::DAssetRequirements protected
Definition at line 166 of file PlayerAsset.h.
DAssetUpgrades
std::vector< std::shared_ptr< CPlayerUpgrade > > CPlayerAssetType::DAssetUpgrades protected
Definition at line 167 of file PlayerAsset.h.
DAttackSteps
int CPlayerAssetType::DAttackSteps protected
Definition at line 178 of file PlayerAsset.h.
DBasicDamage
int CPlayerAssetType::DBasicDamage protected
Definition at line 180 of file PlayerAsset.h.
DBuildTime
int CPlayerAssetType::DBuildTime protected
Definition at line 177 of file PlayerAsset.h.
DCapabilities
std::vector< bool > CPlayerAssetType::DCapabilities protected
Definition at line 165 of file PlayerAsset.h.
DColor
EPlayerColor CPlayerAssetType::DColor protected
Definition at line 164 of file PlayerAsset.h.
DConstructionSight
int CPlayerAssetType::DConstructionSight protected
Definition at line 171 of file PlayerAsset.h.
DFoodConsumption
int CPlayerAssetType::DFoodConsumption protected
Definition at line 176 of file PlayerAsset.h.
DGoldCost
int CPlayerAssetType::DGoldCost protected
Definition at line 174 of file PlayerAsset.h.
DHitPoints
int CPlayerAssetType::DHitPoints protected
Definition at line 168 of file PlayerAsset.h.
DLumberCost
int CPlayerAssetType::DLumberCost protected
Definition at line 175 of file PlayerAsset.h.
DName
std::string CPlayerAssetType::DName protected
Definition at line 162 of file PlayerAsset.h.
DNameTypeTranslation
std::unordered_map< std::string, EAssetType > CPlayerAssetType::DNameTypeTranslation static protected
Definition at line 185 of file PlayerAsset.h.
DPiercingDamage
int CPlayerAssetType::DPiercingDamage protected
Definition at line 181 of file PlayerAsset.h.
DRange
int CPlayerAssetType::DRange protected
Definition at line 182 of file PlayerAsset.h.
DRegistry
std::unordered_map< std::string, std::shared_ptr< CPlayerAssetType > > CPlayerAssetType::DRegistry static protected
Definition at line 183 of file PlayerAsset.h.
DReloadSteps
int CPlayerAssetType::DReloadSteps protected
Definition at line 179 of file PlayerAsset.h.
DSight
int CPlayerAssetType::DSight protected
Definition at line 170 of file PlayerAsset.h.
DSize
int CPlayerAssetType::DSize protected
Definition at line 172 of file PlayerAsset.h.
DSpeed
int CPlayerAssetType::DSpeed protected
Definition at line 173 of file PlayerAsset.h.
DThis
std::weak_ptr< CPlayerAssetType > CPlayerAssetType::DThis protected
Definition at line 161 of file PlayerAsset.h.
DType
EAssetType CPlayerAssetType::DType protected
Definition at line 163 of file PlayerAsset.h.
DTypeStrings
std::vector< std::string > CPlayerAssetType::DTypeStrings static protected
Definition at line 184 of file PlayerAsset.h.
The documentation for this class was generated from the following files:
include/PlayerAsset.h
src/PlayerAsset.cpp