ECS 160 Project: CPlayerCapabilityAttack Class Reference
CPlayerCapabilityAttack Class Reference
Classes
class CActivatedCapability
class CRegistrant
Public Member Functions
virtual ~CPlayerCapabilityAttack ()
bool CanInitiate (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata)
bool CanApply (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
bool ApplyCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
Public Member Functions inherited from CPlayerCapability
virtual ~CPlayerCapability ()
std::string Name () const
EAssetCapabilityType AssetCapabilityType () const
ETargetType TargetType () const
Protected Member Functions
CPlayerCapabilityAttack ()
Protected Member Functions inherited from CPlayerCapability
CPlayerCapability (const std::string &name, ETargetType targettype)
Static Protected Attributes
static CRegistrant DRegistrant
Additional Inherited Members
Public Types inherited from CPlayerCapability
enum ETargetType {
ttNone = 0, ttAsset, ttTerrain, ttTerrainOrAsset,
ttPlayer
}
typedef enum CPlayerCapability::ETargetType * ETargetTypeRef
Static Public Member Functions inherited from CPlayerCapability
static std::shared_ptr< CPlayerCapability > FindCapability (EAssetCapabilityType type)
static std::shared_ptr< CPlayerCapability > FindCapability (const std::string &name)
static EAssetCapabilityType NameToType (const std::string &name)
static std::string TypeToName (EAssetCapabilityType type)
Static Protected Member Functions inherited from CPlayerCapability
static std::unordered_map< std::string, std::shared_ptr< CPlayerCapability > > & NameRegistry ()
static std::unordered_map< int, std::shared_ptr< CPlayerCapability > > & TypeRegistry ()
static bool Register (std::shared_ptr< CPlayerCapability > capability)
Protected Attributes inherited from CPlayerCapability
std::string DName
EAssetCapabilityType DAssetCapabilityType
ETargetType DTargetType
Detailed Description
Definition at line 644 of file BasicCapabilities.cpp.
Constructor & Destructor Documentation
CPlayerCapabilityAttack()
CPlayerCapabilityAttack::CPlayerCapabilityAttack () protected
Definition at line 679 of file BasicCapabilities.cpp.
                                                  : CPlayerCapability(std::string("Attack"), ttAsset){
 }
~CPlayerCapabilityAttack()
virtual CPlayerCapabilityAttack::~CPlayerCapabilityAttack () inline virtual
Definition at line 666 of file BasicCapabilities.cpp.
References CPlayerCapabilityPatrol::ApplyCapability(), CPlayerCapabilityPatrol::CanApply(), CPlayerCapabilityPatrol::CanInitiate(), and DRegistrant.
 {};
Member Function Documentation
ApplyCapability()
bool CPlayerCapabilityAttack::ApplyCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target) virtual
Implements CPlayerCapability.
Definition at line 694 of file BasicCapabilities.cpp.
References aaCapability, CPlayerCapability::AssetCapabilityType(), SAssetCommand::DAction, SAssetCommand::DActivatedCapability, SAssetCommand::DAssetTarget, and SAssetCommand::DCapability.
Referenced by CPlayerCapabilityRepair::~CPlayerCapabilityRepair().
{
     if(actor->TilePosition() != target->TilePosition()){
         SAssetCommand NewCommand;
         NewCommand.DAction = aaCapability;
         NewCommand.DCapability = AssetCapabilityType();
         NewCommand.DAssetTarget = target;
         NewCommand.DActivatedCapability = std::make_shared< CActivatedCapability >(actor, playerdata, target);
         actor->ClearCommand();
         actor->PushCommand(NewCommand);
         return true;
     }
     return false;
 }
CanApply()
bool CPlayerCapabilityAttack::CanApply (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target) virtual
Implements CPlayerCapability.
Definition at line 687 of file BasicCapabilities.cpp.
References pcNone.
Referenced by CPlayerCapabilityRepair::~CPlayerCapabilityRepair().
{
     if((actor->Color() == target->Color())||(pcNone == target->Color())){
         return false;
     }
     return actor->Speed() > 0;
 }
CanInitiate()
bool CPlayerCapabilityAttack::CanInitiate (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata) virtual
Implements CPlayerCapability.
Definition at line 683 of file BasicCapabilities.cpp.
Referenced by CPlayerCapabilityRepair::~CPlayerCapabilityRepair().
{
     return actor->Speed() > 0;
 }
Member Data Documentation
DRegistrant
CPlayerCapabilityAttack::CRegistrant CPlayerCapabilityAttack::DRegistrant static protected
Definition at line 650 of file BasicCapabilities.cpp.
Referenced by ~CPlayerCapabilityAttack().
The documentation for this class was generated from the following file:
src/BasicCapabilities.cpp