ECS 160 Project: CFileDataSource Class Reference
CFileDataSource Class Reference
#include <FileDataSource.h>
Public Member Functions
CFileDataSource (const std::string &filename)
~CFileDataSource ()
int Read (void *data, int length)
std::shared_ptr< CDataSourceContainer > Container ()
Protected Attributes
int DFileHandle
std::string DFullPath
Detailed Description
Definition at line 23 of file FileDataSource.h.
Constructor & Destructor Documentation
CFileDataSource()
CFileDataSource::CFileDataSource (const std::string & filename)
Definition at line 23 of file FileDataSource.cpp.
References CPath::CurrentPath(), DFileHandle, DFullPath, CPath::Simplify(), and CPath::ToString().
                                                           : CDataSource(){
     DFullPath = CPath::CurrentPath().Simplify(filename).ToString();
     //printf("CFileDataSource::CFileDataSource(\"%s\");\n",DFullPath.c_str());
     if(DFullPath.length()){
         DFileHandle = open(DFullPath.c_str(), O_RDONLY);
     }
 }
~CFileDataSource()
CFileDataSource::~CFileDataSource ()
Definition at line 31 of file FileDataSource.cpp.
References DFileHandle.
{
     if(0 <= DFileHandle){
         close(DFileHandle);
     }
 }
Member Function Documentation
Container()
std::shared_ptr< CDataSourceContainer > CFileDataSource::Container () virtual
Reimplemented from CDataSource.
Definition at line 48 of file FileDataSource.cpp.
References CPath::Containing(), DFullPath, and CPath::ToString().
{
     std::string ContainerName = CPath(DFullPath).Containing().ToString();
     if(ContainerName.length()){
         return (std::shared_ptr< CDataSourceContainer >)(CDataSourceContainer *) new CDirectoryDataSourceContainer(ContainerName);
     }
     return nullptr;
 }
Read()
int CFileDataSource::Read (void * data, int length) virtual
Implements CDataSource.
Definition at line 37 of file FileDataSource.cpp.
References DFileHandle.
{
     if(0 <= DFileHandle){
         int BytesRead = read(DFileHandle, data, length);
         if(0 < BytesRead){
             return BytesRead;
         }
     }
     return -1;
 }
Member Data Documentation
DFileHandle
int CFileDataSource::DFileHandle protected
Definition at line 25 of file FileDataSource.h.
Referenced by CFileDataSource(), Read(), and ~CFileDataSource().
DFullPath
std::string CFileDataSource::DFullPath protected
Definition at line 26 of file FileDataSource.h.
Referenced by CFileDataSource(), and Container().
The documentation for this class was generated from the following files:
include/FileDataSource.h
src/FileDataSource.cpp