ECS 160 Project: CPlayerCapabilityStandGround::CActivatedCapability Class Reference
CPlayerCapabilityStandGround::CActivatedCapability Class Reference
Public Member Functions
CActivatedCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
virtual ~CActivatedCapability ()
int PercentComplete (int max)
bool IncrementStep ()
void Cancel ()
Public Member Functions inherited from CActivatedPlayerCapability
CActivatedPlayerCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
virtual ~CActivatedPlayerCapability ()
Additional Inherited Members
Protected Attributes inherited from CActivatedPlayerCapability
std::shared_ptr< CPlayerAsset > DActor
std::shared_ptr< CPlayerData > DPlayerData
std::shared_ptr< CPlayerAsset > DTarget
Detailed Description
Definition at line 238 of file BasicCapabilities.cpp.
Constructor & Destructor Documentation
CActivatedCapability()
CPlayerCapabilityStandGround::CActivatedCapability::CActivatedCapability (std::shared_ptr< CPlayerAsset > actor, std::shared_ptr< CPlayerData > playerdata, std::shared_ptr< CPlayerAsset > target)
Definition at line 291 of file BasicCapabilities.cpp.
                                                                                                                                                                                          :
 CActivatedPlayerCapability(actor, playerdata, target){
 }
~CActivatedCapability()
virtual CPlayerCapabilityStandGround::CActivatedCapability::~CActivatedCapability () inline virtual
Definition at line 243 of file BasicCapabilities.cpp.
References CPlayerCapabilityMineHarvest::CActivatedCapability::Cancel(), CPlayerCapabilityMineHarvest::CActivatedCapability::IncrementStep(), and CPlayerCapabilityMineHarvest::CActivatedCapability::PercentComplete().
 {};
Member Function Documentation
Cancel()
void CPlayerCapabilityStandGround::CActivatedCapability::Cancel () virtual
Implements CActivatedPlayerCapability.
Definition at line 324 of file BasicCapabilities.cpp.
References CActivatedPlayerCapability::DActor.
Referenced by CPlayerCapabilityCancel::CActivatedCapability::~CActivatedCapability().
{
     DActor->PopCommand();
 }
IncrementStep()
bool CPlayerCapabilityStandGround::CActivatedCapability::IncrementStep () virtual
Implements CActivatedPlayerCapability.
Definition at line 301 of file BasicCapabilities.cpp.
References aaStandGround, aaWalk, SAssetCommand::DAction, CActivatedPlayerCapability::DActor, SGameEvent::DAsset, SAssetCommand::DAssetTarget, dMax, CActivatedPlayerCapability::DPlayerData, SGameEvent::DType, and etAcknowledge.
Referenced by CPlayerCapabilityCancel::CActivatedCapability::~CActivatedCapability().
{
     SAssetCommand AssetCommand;
     SGameEvent TempEvent;
     TempEvent.DType = etAcknowledge;
     TempEvent.DAsset = DActor;
     DPlayerData->AddGameEvent(TempEvent);
     AssetCommand.DAssetTarget = DPlayerData->CreateMarker(DActor->Position(), false);
     AssetCommand.DAction = aaStandGround;
     DActor->ClearCommand();
     DActor->PushCommand(AssetCommand);
     if(!DActor->TileAligned()){
         AssetCommand.DAction = aaWalk;
         DActor->Direction((EDirection)((DActor->Position().TileOctant() + dMax/2) % dMax));
         DActor->PushCommand(AssetCommand);
     }
     return true;
 }
PercentComplete()
int CPlayerCapabilityStandGround::CActivatedCapability::PercentComplete (int max) virtual
Implements CActivatedPlayerCapability.
Definition at line 297 of file BasicCapabilities.cpp.
Referenced by CPlayerCapabilityCancel::CActivatedCapability::~CActivatedCapability().
{
     return 0;
 }
The documentation for this class was generated from the following file:
src/BasicCapabilities.cpp